import { useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Award, Bot, Check, ChevronRight, Clock3, Crosshair, Flag, Flame, Layers3, Loader2, LockKeyhole, ShieldCheck, Swords, Target, Trophy, Users, X } from 'lucide-react';

const surface = 'rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900';
const muted = 'text-slate-500 dark:text-slate-400';
const primary = 'inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-cyan-700 dark:bg-cyan-300 px-6 py-3 text-sm font-bold text-white dark:text-slate-950 shadow-[0_4px_24px_rgba(34,211,238,0.18)] transition hover:bg-cyan-800 dark:hover:bg-cyan-200 active:scale-[0.98] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-400 disabled:cursor-not-allowed disabled:opacity-50 motion-reduce:transition-none';
const secondary = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:border-cyan-400 hover:bg-cyan-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-500 disabled:cursor-not-allowed disabled:opacity-40 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 motion-reduce:transition-none';
const number = value => Number(value ?? 0).toLocaleString();
const duration = value => `${Math.floor(Math.max(0, value) / 60)}:${String(Math.max(0, value) % 60).padStart(2, '0')}`;

function ArenaArt({ searching = false }) {
  return <div className="relative isolate mx-auto flex aspect-square w-full max-w-[340px] items-center justify-center" aria-hidden="true">
    <div className="absolute inset-8 rounded-full bg-cyan-400/10 blur-3xl" />
    <div className="absolute inset-4 rounded-full border border-cyan-600/15 dark:border-cyan-200/10" />
    <div className="absolute inset-9 rounded-full border border-dashed border-cyan-600/25 dark:border-cyan-200/20 motion-safe:animate-[spin_60s_linear_infinite]" />
    <div className="absolute inset-16 rounded-full border border-cyan-600/20 dark:border-cyan-200/15" />
    <svg viewBox="0 0 340 340" className="absolute inset-0 h-full w-full text-cyan-600/40 dark:text-cyan-200/30" fill="none">
      <path d="M0 170h55l15-18 17 38 17-45 20 25h30M340 170h-55l-15-18-17 38-17-45-20 25h-30" stroke="currentColor" strokeWidth="1.5" />
      <path d="M170 4v22m0 288v22M4 170h22m288 0h22" stroke="currentColor" />
      <circle cx="170" cy="22" r="3" className="fill-cyan-600 dark:fill-cyan-200" /><circle cx="306" cy="244" r="3" className="fill-amber-500 dark:fill-amber-300" />
    </svg>
    <div className="absolute left-8 top-[86px] h-36 w-28 -rotate-[18deg] rounded-2xl border border-cyan-400/50 dark:border-cyan-300/30 bg-gradient-to-br from-cyan-100 dark:from-cyan-500/20 to-white dark:to-slate-900 shadow-lg shadow-cyan-900/10 dark:shadow-2xl dark:shadow-black/25" />
    <div className="absolute right-8 top-[86px] h-36 w-28 rotate-[18deg] rounded-2xl border border-amber-400/50 dark:border-amber-300/30 bg-gradient-to-bl from-amber-100 dark:from-amber-400/20 to-white dark:to-slate-900 shadow-lg shadow-cyan-900/10 dark:shadow-2xl dark:shadow-black/25" />
    <div className="relative flex h-36 w-32 flex-col items-center justify-center rounded-[28px] border border-cyan-200 dark:border-white/20 bg-gradient-to-b from-white dark:from-slate-700 to-cyan-50 dark:to-slate-950 shadow-[0_20px_50px_rgba(8,145,178,0.16)] dark:shadow-[0_20px_50px_#020617] motion-safe:animate-[arena-float_6s_ease-in-out_infinite]">
      <Swords size={48} strokeWidth={1.3} className="text-cyan-700 dark:text-cyan-200" />
      <span className="mt-2 text-3xl font-black italic tracking-tighter text-slate-900 dark:text-white">VS</span>
      <div className="absolute -bottom-3 h-1 w-12 rounded-full bg-cyan-600 dark:bg-cyan-300 shadow-[0_0_24px_#22d3ee]" />
    </div>
    <span className="absolute bottom-5 rounded-full border border-cyan-200/70 dark:border-white/10 bg-white/90 dark:bg-slate-950/80 px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-cyan-800 dark:text-cyan-100">{searching ? 'Finding your challenger' : 'Knowledge meets competition'}</span>
  </div>;
}

function Stat({ icon: Icon, label, value, accent = false }) {
  return <div className="flex items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${accent ? 'bg-amber-50 text-amber-600 dark:bg-amber-400/10 dark:text-amber-300' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400'}`}><Icon size={18} /></span><div><p className={`text-[11px] font-medium ${muted}`}>{label}</p><p className="mt-0.5 text-lg font-bold tabular-nums tracking-tight">{value}</p></div></div>;
}

export default function CompeteArena(p) {
  const reduced = useReducedMotion();
  const [starting, setStarting] = useState(null);
  const enter = reduced ? {} : { initial: { opacity: 0, y: 14 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -8 }, transition: { duration: 0.25 } };
  const launch = async (kind, action) => { if (starting) return; setStarting(kind); try { await action(); } finally { setStarting(null); } };
  const total = p.questions.length;
  const win = p.result?.verdict === 'win' && !p.result?.forfeited;
  const question = p.questions[p.index];

  return <section className="mx-auto w-full max-w-[1180px] space-y-6 pb-8 pt-5 text-slate-900 dark:text-slate-100" aria-label="Compete arena">
    <header className="flex flex-wrap items-center justify-between gap-4">
      <div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-700 dark:text-cyan-300"><span className="h-1.5 w-1.5 rounded-full bg-cyan-500" />The Medulla arena</div><h2 className="text-3xl font-extrabold tracking-tight sm:text-4xl">A little rivalry.<br className="sm:hidden" /> A lot of growth.</h2></div>
      <button className={secondary} onClick={p.onLeaderboard}><Trophy size={16} />Leaderboard<ArrowUpRight size={15} /></button>
    </header>

    <AnimatePresence mode="wait" initial={false}><motion.div key={p.status} {...enter} className="space-y-5">
      {p.status === 'idle' && <>
        <div className="grid gap-5 xl:grid-cols-[1fr_290px]">
          <article className="relative isolate overflow-hidden rounded-[24px] border border-cyan-200 dark:border-slate-700 bg-gradient-to-br from-white via-cyan-50/70 to-sky-100/70 dark:bg-[#0b162b] dark:from-transparent dark:via-transparent dark:to-transparent p-6 text-slate-900 dark:text-white sm:p-8">
            <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_85%_35%,rgba(8,145,178,0.2),transparent_65%)]" />
            <div className="grid items-center gap-1 md:grid-cols-[1.15fr_1fr]">
              <div className="relative z-10"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-600/20 dark:border-cyan-300/20 bg-cyan-600/5 dark:bg-cyan-300/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-200"><Swords size={13} />The 1v1 challenge</span>
                <h3 className="mt-6 text-4xl font-extrabold leading-[1.12] tracking-[-0.045em] sm:text-5xl">Think fast.<br />Rise <span className="text-cyan-700 dark:text-cyan-300">together.</span></h3>
                <p className="mt-4 max-w-sm text-sm leading-7 text-slate-600 dark:text-slate-300">Turn what you know into your next win. Take on a fellow medic in a focused, three-minute duel.</p>
                <button className={`${primary} mt-6 w-full sm:w-auto`} disabled={Boolean(starting)} onClick={() => launch('rated', p.onStart)}>{starting === 'rated' ? <Loader2 size={18} className="motion-safe:animate-spin" /> : <Swords size={18} />}Start rated duel<ArrowRight size={17} /></button>
                <p className="mt-3 flex items-center gap-1.5 text-[11px] text-slate-500 dark:text-slate-400"><ShieldCheck size={13} />Same questions. One shared clock. Fair play.</p>
              </div><ArenaArt />
            </div>
            <div className="mt-5 grid grid-cols-3 gap-3 border-t border-cyan-200/70 dark:border-white/10 pt-5">
              {[[Layers3, `${total} MCQs`, 'One focused round'], [Clock3, `${p.minutes} minutes`, 'Make every second count'], [Trophy, 'Elo rated', 'Every match matters']].map(([Icon, title, copy]) => <div key={title}><div className="flex items-center gap-2 text-xs font-semibold text-slate-900 dark:text-white"><Icon size={15} className="hidden text-cyan-700 dark:text-cyan-300 sm:block" />{title}</div><p className="mt-1.5 text-[10px] leading-4 text-slate-500 dark:text-slate-400 sm:text-[11px]">{copy}</p></div>)}
            </div>
          </article>
          <aside className={`${surface} flex flex-col p-6`}><div className="flex items-center justify-between"><p className={`text-[10px] font-bold uppercase tracking-[0.16em] ${muted}`}>Your player card</p><ShieldCheck size={16} className="text-cyan-600" /></div>
            <div className="relative mx-auto my-6 flex h-24 w-24 items-center justify-center"><div className="absolute inset-0 rotate-45 rounded-[24px] border border-amber-300/50 bg-gradient-to-br from-amber-50 to-orange-100 dark:from-amber-400/10 dark:to-orange-500/20" /><Award size={46} strokeWidth={1.35} className="relative text-amber-600 dark:text-amber-300" /></div>
            <p className="truncate text-center text-base font-bold">{p.name}</p><p className={`mt-1 text-center text-xs ${muted}`}>Ready for your next challenge</p>
            <div className="my-5 text-center"><p className="text-4xl font-extrabold tabular-nums tracking-tighter">{number(p.rating)}</p><span className={`text-[10px] font-bold uppercase tracking-[0.18em] ${muted}`}>Current Elo rating</span></div>
            <div className="mt-auto flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-3 text-xs text-amber-800 dark:bg-amber-400/10 dark:text-amber-200"><Flame size={17} />Keep learning. Keep climbing.</div>
          </aside>
        </div>
        <div className="flex items-end justify-between gap-3 pt-2"><div><h3 className="text-lg font-bold tracking-tight">Find your rhythm</h3><p className={`mt-1 text-xs ${muted}`}>Go head-to-head, or get a few reps in first.</p></div><span className={`hidden text-[10px] font-semibold uppercase tracking-widest sm:block ${muted}`}>Your next move</span></div>
        <div className="grid gap-4 md:grid-cols-2">
          {[[Bot, 'TRAINING MODE', 'Your personal sparring partner', 'Sharpen your recall against Clinical Bot. Same intensity, without putting your rating on the line.', 'Play against bot', 'bot', p.onBot, 'bg-cyan-50 text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-300'], [Crosshair, 'WARM-UP ZONE', 'Confidence starts with practice', 'Revisit your subjects, connect the dots, and step into your next duel feeling prepared.', 'Start a warm-up', 'practice', p.onPractice, 'bg-orange-50 text-orange-600 dark:bg-orange-400/10 dark:text-orange-300']].map(([Icon, label, title, copy, cta, kind, action, color]) => <motion.article key={kind} whileHover={reduced ? {} : { y: -4 }} className={`${surface} group relative p-5 transition-shadow hover:shadow-xl hover:shadow-slate-200/40 dark:hover:shadow-none sm:p-6`}>
            <div className="flex items-center justify-between"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${color}`}><Icon size={25} strokeWidth={1.6} /></span><span className={`text-[9px] font-bold tracking-[0.17em] ${muted}`}>{label}</span></div><h4 className="mt-5 text-lg font-bold tracking-tight">{title}</h4><p className={`mt-2 max-w-md text-sm leading-6 ${muted}`}>{copy}</p><button disabled={Boolean(starting)} onClick={() => launch(kind, action)} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg text-sm font-bold text-cyan-700 transition hover:gap-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-500 disabled:opacity-40 dark:text-cyan-300">{starting === kind ? <Loader2 size={16} className="motion-safe:animate-spin" /> : null}{cta}<ArrowRight size={16} /></button>
          </motion.article>)}
        </div>
        <div className={`${surface} grid gap-6 px-6 py-5 sm:grid-cols-3`}><Stat icon={Users} label="Registered learners" value={number(p.learners)} /><Stat icon={Target} label="Community attempts" value={number(p.attempts)} /><Stat icon={ShieldCheck} label="Every rated match" value="Same questions. Fair scores." accent /></div>
        <div className="grid gap-5 px-1 py-2 sm:grid-cols-3">{[['01', 'Find your match', 'Join the queue for a real opponent.'], ['02', 'Trust your knowledge', 'Choose carefully. Lock each answer.'], ['03', 'Learn from the result', 'Review your answers and go again.']].map(([step, title, copy]) => <div key={step} className="flex gap-3"><span className="pt-0.5 text-xs font-bold tabular-nums text-cyan-600 dark:text-cyan-400">{step}</span><div><h4 className="text-xs font-bold">{title}</h4><p className={`mt-1 text-xs leading-5 ${muted}`}>{copy}</p></div></div>)}</div>
      </>}

      {p.status === 'matchmaking' && <article className="relative overflow-hidden rounded-[24px] border border-cyan-200 dark:border-slate-700 bg-gradient-to-br from-white via-cyan-50/70 to-sky-100/70 dark:bg-[#0b162b] dark:from-transparent dark:via-transparent dark:to-transparent px-5 py-8 text-center text-slate-900 dark:text-white sm:py-10">
        <span className="inline-flex items-center gap-2 rounded-full border border-cyan-600/20 dark:border-cyan-300/20 bg-cyan-600/5 dark:bg-cyan-300/10 px-3 py-1.5 text-xs text-cyan-700 dark:text-cyan-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-600 dark:bg-cyan-300 motion-safe:animate-pulse" />Rated matchmaking</span>
        <div className="mx-auto max-w-[270px]"><ArenaArt searching /></div><h3 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Your next rival is out there.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400" role="status">{p.queue?.ticketId ? 'You’re in the queue. Your match starts automatically when another learner joins.' : 'Joining the queue. Getting your place in the arena…'}</p>
        <div className="mx-auto my-7 grid max-w-lg grid-cols-3 divide-x divide-cyan-200/70 dark:divide-white/10 rounded-2xl border border-cyan-200/70 dark:border-white/10 bg-white/70 dark:bg-white/5 py-4">{[['Your rating', number(p.rating)], ['Waiting now', p.queue?.waitingCount ?? '—'], ['Format', `${total} questions`]].map(([label, value]) => <div key={label}><p className="text-[10px] text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 text-lg font-bold tabular-nums">{value}</p></div>)}</div>
        <button className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 dark:border-slate-600 px-5 py-2 text-sm text-slate-600 dark:text-slate-300 transition hover:border-slate-400 hover:text-slate-950 dark:hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300" onClick={p.onLeave}><X size={15} />Leave queue</button>
      </article>}

      {p.status === 'live' && question && <>
        <div className="relative overflow-hidden rounded-2xl border border-cyan-200 dark:border-slate-700 bg-gradient-to-br from-white via-cyan-50/70 to-sky-100/70 dark:bg-[#0b162b] dark:from-transparent dark:via-transparent dark:to-transparent p-4 text-slate-900 dark:text-white sm:p-6"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 sm:gap-6">
          <Player name={p.name} label="YOU" answered={p.answered} total={total} />
          <div className={`flex h-20 w-20 flex-col items-center justify-center rounded-full border-[3px] sm:h-24 sm:w-24 ${p.timeLeft <= 30 ? 'border-amber-400 bg-amber-400/10 text-amber-800 dark:text-amber-200' : 'border-cyan-600/50 dark:border-cyan-300/60 bg-white/70 dark:bg-cyan-300/5 text-cyan-800 dark:text-cyan-100'}`}><span className="text-[8px] font-semibold uppercase tracking-widest">Time left</span><span role="timer" aria-label={`${duration(p.timeLeft)} remaining`} className="mt-1 text-2xl font-bold tabular-nums sm:text-3xl">{duration(p.timeLeft)}</span></div>
          <Player name={p.opponent?.name ?? 'Opponent'} label={p.mode === 'bot' ? 'CLINICAL BOT' : 'OPPONENT'} answered={p.opponentAnswered} total={total} opponent />
        </div><div className="mt-5 h-0.5 overflow-hidden rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full bg-cyan-600 dark:bg-cyan-300 transition-[width] duration-1000 motion-reduce:transition-none" style={{ width: `${Math.max(0, Math.min(100, p.timeLeft / (p.minutes * 60) * 100))}%` }} /></div></div>
        <article className={`${surface} p-5 sm:p-8`}>
          <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">Question {p.index + 1} <span className="text-slate-500 dark:text-slate-400">/ {total}</span></span><div className="flex gap-1.5" aria-label={`Question ${p.index + 1} of ${total}`}>{p.questions.map((q, i) => <span key={q.id ?? i} className={`h-1.5 w-5 rounded-full sm:w-8 ${i === p.index ? 'bg-cyan-500' : p.submitted[i] ? 'bg-emerald-400' : 'bg-slate-200 dark:bg-slate-700'}`} />)}</div><span className={`rounded-full bg-slate-100 px-3 py-1 text-[10px] font-semibold dark:bg-slate-800 ${muted}`}>{p.mode === 'bot' ? 'Bot practice · Unrated' : 'Rated duel'}</span></div>
          <AnimatePresence mode="wait" initial={false}><motion.div key={question.id} {...enter}><h3 className="text-lg font-semibold leading-relaxed tracking-tight sm:text-xl">{question.prompt}</h3>{p.renderDetails(question)}{question.leadIn && <p className="mt-4 font-semibold leading-7">{question.leadIn}</p>}
          <div className="mt-6 grid gap-3 sm:grid-cols-2">{question.options.map((option, i) => {
            const selected = p.selection === option;
            return <button key={i} aria-pressed={selected} disabled={p.locked || p.answerBusy} onClick={() => p.onSelect(option)} className={`group flex min-h-[72px] items-center gap-3 rounded-xl border p-4 text-left text-sm leading-6 transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-500 disabled:cursor-default motion-reduce:transition-none ${selected ? 'border-cyan-500 bg-cyan-50 ring-1 ring-cyan-500 dark:bg-cyan-400/10' : 'border-slate-200 bg-slate-50/60 enabled:hover:border-cyan-400 enabled:hover:bg-cyan-50/50 dark:border-slate-700 dark:bg-slate-800/40 dark:enabled:hover:bg-slate-800'}`}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-xs font-bold ${selected ? 'bg-cyan-700 text-white dark:bg-cyan-500 dark:text-slate-950' : 'border border-slate-200 bg-white text-slate-500 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{selected && p.locked ? <LockKeyhole size={14} /> : String.fromCharCode(65 + i)}</span><span>{option}</span>{selected && <Check size={16} className="ml-auto shrink-0 text-cyan-600 dark:text-cyan-300" />}</button>;
          })}</div></motion.div></AnimatePresence>
          {p.locked && <p role="status" className="mt-4 flex items-center gap-2 text-xs text-emerald-700 dark:text-emerald-300"><ShieldCheck size={15} />Answer locked. Keep going—results arrive after the match.</p>}
          <div className="mt-7 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-6 dark:border-slate-800"><button className={primary} onClick={p.onLock} disabled={!p.selection || p.locked || p.answerBusy}>{p.answerBusy ? <Loader2 size={16} className="motion-safe:animate-spin" /> : <LockKeyhole size={16} />}{p.answerBusy ? 'Locking…' : p.locked ? 'Answer locked' : 'Lock answer'}</button><button className={secondary} onClick={p.onNext} disabled={!p.locked}>{p.index === total - 1 ? 'Finish duel' : 'Next question'}<ChevronRight size={16} /></button><button className="ml-auto inline-flex min-h-11 items-center gap-2 rounded-lg px-2 text-xs text-slate-500 hover:text-red-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-500 dark:text-slate-400" onClick={p.onForfeit}><Flag size={14} />End match</button></div>
        </article>
      </>}

      {p.status === 'finished' && <article className={`${surface} overflow-hidden`}>
        <div className="relative overflow-hidden bg-gradient-to-br from-white via-cyan-50/70 to-sky-100/70 dark:bg-[#0b162b] dark:from-transparent dark:via-transparent dark:to-transparent px-5 py-9 text-center text-slate-900 dark:text-white sm:py-12"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_50%_0%,rgba(34,211,238,0.18),transparent_70%)]" />
          {win && <div aria-hidden="true" className="pointer-events-none absolute inset-0 overflow-hidden">{Array.from({ length: 12 }, (_, i) => <span key={i} className={`absolute h-2 w-1 rounded-sm ${i % 2 ? 'bg-cyan-600 dark:bg-cyan-300' : 'bg-amber-500 dark:bg-amber-300'} motion-safe:animate-[arena-float_4s_ease-in-out_infinite]`} style={{ left: `${8 + i * 7.5}%`, top: `${15 + (i * 17) % 65}%`, transform: `rotate(${i * 31}deg)`, animationDelay: `${i * 0.12}s` }} />)}</div>}
          <span className="relative mx-auto flex h-20 w-20 items-center justify-center rounded-3xl border border-amber-300 dark:border-amber-200/30 bg-amber-100/80 dark:bg-amber-300/10 text-amber-700 dark:text-amber-300">{!p.result ? <Loader2 size={34} className="motion-safe:animate-spin" /> : win ? <Trophy size={38} strokeWidth={1.5} /> : <Swords size={36} strokeWidth={1.5} />}</span><p className="relative mt-5 text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-700 dark:text-cyan-200">{!p.result ? 'Match in progress' : 'Round complete'}</p><h3 aria-live="polite" className="relative mt-2 text-3xl font-extrabold tracking-tight">{!p.result ? 'Waiting for the final whistle…' : p.result.forfeited ? 'You left the match.' : win ? 'That’s a well-earned win.' : p.result.verdict === 'loss' ? 'A lesson. Then a comeback.' : 'Evenly matched. Well played.'}</h3><p className="relative mx-auto mt-3 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400">{!p.result ? 'Your result will appear when both players finish or the clock runs out.' : 'Every round is another chance to sharpen what you know.'}</p>
        </div>
        <div className="p-5 sm:p-8"><div className="grid grid-cols-3 gap-2 text-center sm:gap-5">{[['Your score', p.result ? `${p.result.userScore} / ${total}` : '—'], ['Opponent score', p.result ? `${p.result.opponentScore} / ${total}` : '—'], ['Your rating', number(p.result?.nextRating ?? p.rating)]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 px-2 py-5 dark:bg-slate-800/60"><p className={`text-[10px] sm:text-xs ${muted}`}>{label}</p><p className="mt-2 text-xl font-bold tabular-nums tracking-tight sm:text-3xl">{value}</p></div>)}</div>
          <p className={`mt-4 text-center text-xs ${muted}`}>{p.result?.ratingAffected === false ? 'Training match · Your rating is unchanged' : p.result ? `${p.result.delta > 0 ? '+' : ''}${p.result.delta} Elo this round` : 'Rating update pending'}</p>
          <div className="mt-6 flex flex-wrap justify-center gap-3"><button className={primary} disabled={!p.result} onClick={p.onAgain}><Swords size={16} />Back to arena</button><button className={secondary} onClick={p.onLeaderboard}><Trophy size={16} />View leaderboard</button></div>
          {p.result?.review?.length > 0 && <div className="mt-8 border-t border-slate-200 pt-6 dark:border-slate-700"><button className={`${secondary} w-full`} onClick={p.onToggleReview} aria-expanded={p.showReview}>{p.showReview ? 'Hide answer review' : 'Learn from this round'}<ChevronRight size={16} className={p.showReview ? 'rotate-90' : ''} /></button>{p.showReview && <div className="mt-5 space-y-4">{p.result.review.map((q, i) => <article key={q.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700 sm:p-5"><p className={`mb-3 flex items-center gap-2 text-xs font-bold ${q.status === 'correct' ? 'text-emerald-600 dark:text-emerald-300' : 'text-amber-700 dark:text-amber-300'}`}><Target size={15} />Question {i + 1} · {q.status === 'correct' ? 'Correct' : q.status === 'incorrect' ? 'Incorrect' : 'Unanswered'}</p><h4 className="text-sm font-semibold leading-6">{q.prompt}</h4>{p.renderDetails(q)}{q.leadIn && <p className="mt-3 text-sm">{q.leadIn}</p>}<ol className="mt-4 space-y-2">{q.options.map((option, index) => <li key={index} className={`rounded-lg border px-3 py-2 text-sm ${index === q.correctIndex ? 'border-emerald-300 bg-emerald-50 text-emerald-900 dark:border-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-200' : index === q.selectedIndex ? 'border-amber-300 bg-amber-50 text-amber-900 dark:border-amber-800 dark:bg-amber-500/10 dark:text-amber-200' : 'border-slate-100 text-slate-500 dark:border-slate-800 dark:text-slate-400'}`}>{String.fromCharCode(65 + index)}. {option}{index === q.correctIndex ? ' · Correct answer' : ''}{index === q.selectedIndex ? ' · Your answer' : ''}</li>)}</ol>{q.explanation && <p className={`mt-4 text-sm leading-7 ${muted}`}><strong className="text-slate-800 dark:text-slate-200">Why: </strong>{q.explanation}</p>}</article>)}</div>}</div>}
        </div>
      </article>}
    </motion.div></AnimatePresence>
    {p.message && <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900 dark:border-amber-800 dark:bg-amber-400/10 dark:text-amber-200">{p.message}</p>}
  </section>;
}

function Player({ name, label, answered, total, opponent = false }) {
  return <div className={`min-w-0 ${opponent ? 'text-right' : ''}`}><span className={`text-[8px] font-bold tracking-[0.15em] sm:text-[10px] ${opponent ? 'text-amber-700 dark:text-amber-300' : 'text-cyan-700 dark:text-cyan-300'}`}>{label}</span><p className="mt-1 truncate text-sm font-bold sm:text-lg">{name}</p><p className="mt-1 text-[10px] text-slate-500 dark:text-slate-400 sm:text-xs">{answered} / {total} answers locked</p><div className={`mt-3 flex gap-1 ${opponent ? 'justify-end' : ''}`} aria-hidden="true">{Array.from({ length: total }, (_, i) => <span key={i} className={`h-1.5 w-3 rounded-full sm:w-6 ${i < answered ? opponent ? 'bg-amber-500 dark:bg-amber-300' : 'bg-cyan-600 dark:bg-cyan-300' : 'bg-slate-200 dark:bg-white/15'}`} />)}</div></div>;
}
