import { useState } from 'react';
import LeaderboardPodium from './LeaderboardPodium';
import { ArrowRight, Award, Flame, MapPin, Search, Swords, Trophy, Users } from 'lucide-react';
import { Avatar, EmptyState, SearchField, field, muted, number, pill, primary, secondary, socialPage, surface } from './SocialUI';

export default function Leaderboard(p) {
  const [scope, setScope] = useState('national');
  const [query, setQuery] = useState('');
  const [onlySelf, setOnlySelf] = useState(false);
  const [limit, setLimit] = useState(25);
  const pool = scope === 'national' ? p.players : p.statePlayers;
  const ranked = pool.map((player, index) => ({ ...player, displayRank: scope === 'national' ? player.rank : index + 1 }));
  const filtered = ranked.filter(player => (!onlySelf || player.isCurrentUser) && `${player.name} ${player.college} ${player.state}`.toLowerCase().includes(query.trim().toLowerCase()));
  const self = p.players.find(player => player.isCurrentUser);
  const ahead = self && p.players.find(player => player.rank === self.rank - 1);
  const reset = () => { setQuery(''); setOnlySelf(false); setLimit(25); };
  return <section className={socialPage} aria-label="Leaderboard">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300">The learning league</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Leaderboard</h2><p className={`mt-3 ${muted}`}>Good habits add up. See where your practice takes you.</p></div><button className={primary} onClick={p.onCompete}><Swords size={17} />Join a challenge<ArrowRight size={16} /></button></header>

    <div className="grid gap-5 lg:grid-cols-[1fr_300px]">
      <div className={`${surface} overflow-hidden`}><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h3 className="flex items-center gap-2 text-sm font-semibold"><Trophy size={17} className="text-amber-600 dark:text-amber-300" />Leading the way</h3><span className={pill}>National top 3</span></div>
        {p.players.length ? <LeaderboardPodium players={p.players} onProfile={p.onProfile} /> : <EmptyState icon={Trophy} title="The league starts with you">Complete a challenge to get started.</EmptyState>}
      </div>
      <aside className="rounded-2xl border border-cyan-200 bg-cyan-50/70 p-5 dark:border-cyan-800/60 dark:bg-cyan-950/30"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Your standing</h3><Award size={19} className="text-cyan-700 dark:text-cyan-300" /></div><div className="my-5 flex items-end gap-3"><strong className="text-4xl font-bold tracking-tight">{self ? `#${self.rank}` : '—'}</strong><span className={`pb-1 ${muted}`}>national rank</span></div><div className="flex justify-between border-t border-cyan-200/70 pt-4 text-sm dark:border-cyan-900"><span className="text-slate-500 dark:text-slate-400">Your rating</span><strong className="tabular-nums">{self ? number(self.score) : '—'}</strong></div><p className={`mt-3 text-xs ${muted}`}>{ahead ? `${number(ahead.score - self.score)} rating points to match the learner above you.` : self ? 'Keep practicing. Every challenge is a chance to grow.' : 'Your standing appears once your profile is ranked.'}</p></aside>
    </div>

    <article className={`${surface} overflow-hidden`}>
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5 dark:border-slate-800"><div className="flex gap-1 rounded-xl bg-slate-100 p-1 dark:bg-slate-950" aria-label="Ranking scope">{[['national', 'National', Users], ['college', 'State & college', MapPin]].map(([key, label, Icon]) => <button key={key} aria-pressed={scope === key} onClick={() => { setScope(key); reset(); }} className={`flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm font-semibold transition motion-reduce:transition-none ${scope === key ? 'bg-white text-slate-900 shadow-sm dark:bg-slate-800 dark:text-white' : 'text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white'}`}><Icon size={15} />{label}</button>)}</div><span className="text-xs text-slate-500 dark:text-slate-400">Ranked by rating · {number(pool.length)} learners</span></div>
      <div className="space-y-4 p-5">{scope === 'college' && <div className="grid gap-4 sm:grid-cols-2 motion-safe:animate-in motion-safe:fade-in"><label className="space-y-2 text-xs font-semibold"><span>State or region</span><select className={field} value={p.state?.state || ''} onChange={e => { p.onState(e.target.value); reset(); }}>{p.states.map(entry => <option key={entry.state} value={entry.state}>{entry.state} ({entry.players.length})</option>)}</select></label><label className="space-y-2 text-xs font-semibold"><span>Medical college</span><select className={field} value={p.college} onChange={e => { p.onCollege(e.target.value); reset(); }}><option value="">All colleges</option>{p.colleges.map(college => <option key={college}>{college}</option>)}</select></label></div>}<div className="flex flex-wrap items-center gap-3"><div className="min-w-0 flex-1 basis-64"><SearchField value={query} onChange={value => { setQuery(value); setOnlySelf(false); setLimit(25); }} placeholder="Search learners or colleges" /></div>{self && <button className={secondary} aria-pressed={onlySelf} onClick={() => { setScope('national'); setQuery(''); setOnlySelf(value => !value); setLimit(25); }}>{onlySelf ? 'Show everyone' : 'Find my rank'}</button>}</div></div>
      <div className="overflow-x-auto"><table className="w-full table-fixed text-left text-sm"><caption className="sr-only">{scope === 'national' ? 'National' : p.state?.state} rankings</caption><thead className="border-y border-slate-100 bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500 dark:border-slate-800 dark:bg-slate-950/50 dark:text-slate-400"><tr><th className="w-14 px-3 py-3 text-center sm:w-20">Rank</th><th className="px-3 py-3">Learner</th><th className="hidden w-24 px-3 py-3 text-right sm:table-cell">Streak</th><th className="w-24 px-4 py-3 text-right sm:w-28">Rating</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.slice(0, limit).map(player => <tr key={player.id} className={`transition-colors motion-reduce:transition-none ${player.isCurrentUser ? 'bg-cyan-50/80 dark:bg-cyan-950/30' : 'hover:bg-slate-50 dark:hover:bg-slate-800/40'}`}><td className="px-3 py-4 text-center font-medium tabular-nums text-slate-500 dark:text-slate-400">{player.displayRank.toString().padStart(2, '0')}</td><td className="px-3 py-4"><button onClick={() => p.onProfile(player.id)} className="flex w-full min-w-0 items-center gap-3 text-left"><span className="hidden sm:block"><Avatar name={player.name} /></span><span className="min-w-0"><span className="block truncate font-semibold hover:text-cyan-700 dark:hover:text-cyan-300">{player.name}{player.isCurrentUser && <span className="ml-2 text-xs font-medium text-cyan-700 dark:text-cyan-300">You</span>}</span><span className="mt-1 block truncate text-xs text-slate-500 dark:text-slate-400" title={player.college}>{player.college}</span></span></button></td><td className="hidden px-3 py-4 text-right sm:table-cell"><span className="inline-flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400"><Flame size={14} className="text-amber-600 dark:text-amber-400" />{player.streak}d</span></td><td className="px-4 py-4 text-right font-semibold tabular-nums">{number(player.score)}</td></tr>)}</tbody></table></div>
      {!filtered.length && <EmptyState icon={Search} title={query ? 'No learners found' : 'No rankings here yet'}>{query ? 'Try another name or college, or clear your search.' : 'Choose another state or college to explore the league.'}{query && <button className="mt-3 block w-full font-semibold text-cyan-700 dark:text-cyan-300" onClick={reset}>Clear search</button>}</EmptyState>}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4 dark:border-slate-800"><p role="status" className="text-xs text-slate-500 dark:text-slate-400">Showing {Math.min(limit, filtered.length)} of {number(filtered.length)} learners</p>{filtered.length > limit && <button className={secondary} onClick={() => setLimit(value => value + 25)}>Show more<ArrowRight size={14} /></button>}</div>
    </article>
  </section>;
}
