import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = ROOT / "runtime-data" / "users.json"
SOURCE_PDF = "Goodman and Gilman's The Pharmacological Basis of Therapeutics, 14th ed. (provided PDF)"
ID_PREFIX = "usmle-pharmacology-goodman-gilman-"


def question(
    number,
    chapter_title,
    chapter_order,
    topic,
    topic_order,
    page_start,
    prompt,
    options,
    answer_index,
    explanation,
    difficulty="moderate",
    tags=None,
    lead_in=None,
    laboratory_findings=None,
    item_family="mechanism",
):
    return {
        "id": f"{ID_PREFIX}{number:02d}",
        "examId": "usmle-step-1",
        "examTitle": "USMLE Step 1-Style Practice",
        "subjectId": "pharmacology",
        "subjectTitle": "Pharmacology",
        "chapterTitle": chapter_title,
        "chapterOrder": chapter_order,
        "topic": topic,
        "topicTitle": topic,
        "topicOrder": topic_order,
        "source": "usmle",
        "sourcePdf": SOURCE_PDF,
        "sourcePdfPageStart": page_start,
        "sourcePdfPageEnd": page_start,
        "difficulty": difficulty,
        "prompt": prompt,
        "leadIn": lead_in,
        "laboratoryFindings": laboratory_findings or [],
        "itemFamily": item_family,
        "options": options,
        "answerIndex": answer_index,
        "answer": options[answer_index],
        "explanation": explanation,
        "imageUrls": [],
        "tags": ["usmle-step-1", "goodman-gilman-14e", *(tags or [])],
    }


QUESTIONS = [
    question(
        1,
        "Pharmacokinetics: Absorption, Distribution, Metabolism, and Elimination",
        2,
        "Loading Dose and Bioavailability",
        1,
        59,
        "A 64-year-old man is admitted for recurrent sustained ventricular tachycardia. An oral antiarrhythmic drug must reach its therapeutic concentration promptly. The target plasma concentration is 5 mg/L, the apparent volume of distribution is 40 L, and oral bioavailability is 0.50. Renal and hepatic function are normal. Which of the following is the most appropriate oral loading dose?",
        [
            "100 mg",
            "200 mg",
            "400 mg",
            "800 mg",
            "1600 mg",
        ],
        2,
        "Loading dose equals target plasma concentration multiplied by volume of distribution and divided by bioavailability. Thus, (5 mg/L x 40 L) / 0.50 = 400 mg. Clearance determines the maintenance dosing rate, not the loading dose.",
        tags=["pharmacokinetics", "loading-dose", "bioavailability"],
        item_family="pharmacokinetics",
    ),
    question(
        2,
        "Pharmacodynamics: Molecular Mechanisms of Drug Action",
        3,
        "Receptor Reserve and Irreversible Antagonism",
        1,
        74,
        "Investigators study contraction of isolated arterial smooth muscle in response to a full agonist. After an irreversible antagonist inactivates 20% of the receptors, a higher agonist concentration is required to produce 50% of the maximal contraction, but the maximal contraction remains unchanged. At higher antagonist concentrations, the maximal response eventually decreases. Which of the following best explains the initial preservation of the maximal response?",
        [
            "The agonist is converted to a more potent active metabolite",
            "The antagonist increases receptor synthesis during the experiment",
            "The antagonist has lower affinity at high agonist concentrations",
            "A receptor reserve permits a maximal response without occupancy of every receptor",
            "Negative cooperativity increases agonist efficacy at unoccupied receptors",
        ],
        3,
        "When spare receptors are present, a full tissue response can occur with only a fraction of receptors occupied. Irreversible blockade first shifts the concentration-response relation because more agonist is needed, while maximal efficacy is preserved until the receptor reserve is exhausted.",
        difficulty="hard",
        tags=["pharmacodynamics", "spare-receptors", "irreversible-antagonist"],
    ),
    question(
        3,
        "Pharmacogenetics and Pharmacogenomics",
        7,
        "HLA-Associated Abacavir Hypersensitivity",
        1,
        161,
        "A 38-year-old man with HIV infection begins an antiretroviral regimen that includes abacavir. Nine days later, he develops fever, a diffuse rash, malaise, abdominal pain, and dyspnea. The medication is stopped, and the symptoms resolve. An unsupervised rechallenge causes hypotension and respiratory distress within hours. Screening for which of the following before treatment would most likely have prevented this reaction?",
        [
            "HLA-B*57:01",
            "HLA-B*58:01",
            "HLA-B*15:02",
            "HLA-A*31:01",
            "CYP2C9*3",
        ],
        0,
        "HLA-B*57:01 strongly predicts abacavir hypersensitivity, and genotype-guided avoidance markedly reduces severe reactions. HLA-B*58:01 is associated with allopurinol reactions, while HLA-B*15:02 and HLA-A*31:01 are associated with carbamazepine reactions in particular populations.",
        tags=["pharmacogenetics", "abacavir", "hla-b57-01"],
        item_family="predicted-finding",
    ),
    question(
        4,
        "Postmarketing Drug Safety",
        8,
        "Limits of Spontaneous Adverse-Event Reports",
        1,
        167,
        "During the first year after approval of a new antiarrhythmic drug, a national spontaneous-reporting database receives 18 reports of torsades de pointes among patients who took the drug. Investigators want to use these reports alone to calculate the incidence of drug-induced torsades. Which of the following most directly prevents a valid incidence calculation?",
        [
            "The adverse event has a long biological latency",
            "The reports cannot reveal a temporal relation to drug exposure",
            "Randomization was not stratified by baseline QT interval",
            "The drug was approved without a placebo-controlled efficacy trial",
            "Both the number of exposed patients and the completeness of case reporting are uncertain",
        ],
        4,
        "Spontaneous-reporting systems are valuable for detecting rare safety signals, but they do not reliably provide either the numerator or denominator needed for incidence. Reporting is incomplete and selective, and the total number of exposed patients is usually not known accurately from the reports alone.",
        difficulty="hard",
        tags=["pharmacovigilance", "adverse-events", "postmarketing-surveillance"],
        item_family="experimental-design",
    ),
    question(
        5,
        "Anticholinesterase Inhibitors and Reactivators",
        12,
        "Organophosphate Poisoning and Pralidoxime",
        1,
        247,
        "A 44-year-old greenhouse worker is brought to the emergency department after pesticide exposure. He has diaphoresis, vomiting, pinpoint pupils, bronchorrhea, bradycardia, and diffuse muscle fasciculations. Atropine improves the bradycardia and bronchial secretions, but marked skeletal muscle weakness persists. Pralidoxime is administered promptly. Which of the following best describes the action of this drug?",
        [
            "Competitive inhibition of acetylcholine at nicotinic receptors",
            "Nucleophilic removal of the phosphate group from acetylcholinesterase before aging occurs",
            "Irreversible blockade of muscarinic acetylcholine receptors",
            "Inhibition of presynaptic acetylcholine release at the neuromuscular junction",
            "Acceleration of organophosphate metabolism by hepatic cytochrome P450 enzymes",
        ],
        1,
        "Pralidoxime can reactivate phosphorylated acetylcholinesterase if it is given before the enzyme-organophosphate complex undergoes aging. Atropine antagonizes muscarinic manifestations but does not reverse nicotinic neuromuscular weakness.",
        tags=["organophosphate", "pralidoxime", "acetylcholinesterase"],
        item_family="treatment-mechanism",
    ),
    question(
        6,
        "Neuromuscular Junction and Autonomic Ganglia",
        13,
        "Succinylcholine-Associated Hyperkalemia",
        1,
        257,
        "A 29-year-old man with extensive crush injuries undergoes urgent debridement. Shortly after succinylcholine is given for endotracheal intubation, the ECG develops tall peaked T waves followed by a wide-complex tachycardia. Serum potassium is 7.7 mEq/L. Which of the following mechanisms most directly caused this acute electrolyte abnormality?",
        [
            "Inhibition of the sodium-potassium ATPase in cardiac myocytes",
            "Release of potassium from damaged erythrocytes by an immune reaction",
            "Sustained depolarization of skeletal muscle end plates with potassium efflux",
            "Blockade of renal potassium secretion in the cortical collecting duct",
            "Intracellular potassium displacement by acute respiratory acidosis",
        ],
        2,
        "Succinylcholine is a depolarizing neuromuscular blocker. Persistent end-plate depolarization permits potassium to leave skeletal muscle; in patients with extensive soft-tissue injury, the resulting potassium load can be life-threatening.",
        tags=["succinylcholine", "hyperkalemia", "neuromuscular-blockade"],
        item_family="mechanism",
    ),
    question(
        7,
        "Adrenergic Agonists and Antagonists",
        14,
        "Preoperative Treatment of Pheochromocytoma",
        1,
        288,
        "A 41-year-old woman has episodic headache, diaphoresis, palpitations, and severe hypertension. Imaging shows an adrenal mass, and urinary fractionated metanephrines are markedly increased. Propranolol is given before any other adrenergic antagonist, after which her blood pressure rapidly rises to 246/132 mm Hg. Pretreatment with phenoxybenzamine would most likely have prevented this response by which of the following mechanisms?",
        [
            "Inhibition of catecholamine storage in chromaffin-cell vesicles",
            "Competitive inhibition of catecholamine synthesis by tyrosine hydroxylase",
            "Selective blockade of beta-1 receptors in cardiac pacemaker cells",
            "Activation of presynaptic alpha-2 receptors on sympathetic nerve terminals",
            "Irreversible blockade of alpha adrenergic receptor-mediated vasoconstriction",
        ],
        4,
        "Phenoxybenzamine irreversibly blocks alpha receptors and is given before beta blockade in pheochromocytoma. Giving a beta blocker first removes beta-mediated cardiac effects and vasodilation while leaving intense alpha-mediated vasoconstriction unopposed, which can precipitate a hypertensive crisis.",
        tags=["pheochromocytoma", "phenoxybenzamine", "alpha-blockade"],
        item_family="treatment-mechanism",
    ),
    question(
        8,
        "Protein Synthesis Inhibitors",
        60,
        "Linezolid and Serotonin Syndrome",
        1,
        1206,
        "A 57-year-old woman takes sertraline for major depressive disorder. She is hospitalized for pneumonia caused by vancomycin-resistant Enterococcus faecium and is started on linezolid. Two days later, she develops agitation, diaphoresis, fever, diarrhea, hyperreflexia, and inducible ankle clonus. Which of the following pharmacologic interactions most likely caused these findings?",
        [
            "Combined blockade of dopamine receptors and vesicular dopamine transport",
            "Combined activation of GABA-A receptors and inhibition of GABA metabolism",
            "Combined inhibition of norepinephrine release and alpha-1 receptor blockade",
            "Combined inhibition of serotonin reuptake and monoamine oxidase activity",
            "Combined activation of muscarinic receptors and inhibition of acetylcholinesterase",
        ],
        3,
        "Sertraline inhibits serotonin reuptake, and linezolid has monoamine oxidase-inhibiting activity. Their combined serotonergic effects can produce serotonin syndrome, recognized by mental-status change, autonomic activation, hyperreflexia, and clonus.",
        tags=["linezolid", "serotonin-syndrome", "drug-interaction"],
        item_family="mechanism",
    ),
    question(
        9,
        "Drugs Affecting Renal Excretory Function",
        29,
        "Lithium-Induced Nephrogenic Diabetes Insipidus",
        1,
        598,
        "A 46-year-old woman with bipolar disorder has taken lithium for 8 years. She reports intense thirst and produces 6 L of urine daily. Water deprivation does not appreciably increase urine osmolality, and desmopressin produces little additional change. Lithium is continued because previous alternatives were ineffective.",
        [
            "Block epithelial sodium channels in collecting-duct principal cells",
            "Block sodium-potassium-chloride cotransport in the thick ascending limb",
            "Block sodium-chloride cotransport in the distal convoluted tubule",
            "Activate vasopressin V2 receptors in collecting-duct principal cells",
            "Inhibit carbonic anhydrase in the proximal tubule",
        ],
        0,
        "Amiloride blocks epithelial sodium channels in collecting-duct principal cells, reducing lithium entry into those cells and limiting its disruption of water-concentrating mechanisms. Desmopressin is generally ineffective because this is nephrogenic rather than central diabetes insipidus.",
        tags=["lithium", "nephrogenic-diabetes-insipidus", "amiloride"],
        lead_in="The most appropriate pharmacotherapy acts by which of the following mechanisms?",
        laboratory_findings=[
            {"test": "Serum sodium", "value": "149 mEq/L", "reference": "136-145 mEq/L"},
            {"test": "Serum glucose", "value": "94 mg/dL", "reference": "70-100 mg/dL"},
            {"test": "Urine osmolality", "value": "105 mOsm/kg H2O", "reference": "50-1200 mOsm/kg H2O"},
        ],
        item_family="treatment-mechanism",
    ),
    question(
        10,
        "Treatment of Central Nervous System Degenerative Disorders",
        21,
        "Levodopa and Peripheral Decarboxylase Inhibition",
        1,
        435,
        "A 72-year-old man with bradykinesia, resting tremor, and cogwheel rigidity begins levodopa together with carbidopa. Compared with levodopa alone, the combination permits a lower levodopa dose and causes less nausea and orthostatic hypotension. Which of the following best explains these effects of carbidopa?",
        [
            "It activates dopamine D2 receptors in the striatum",
            "It inhibits catechol-O-methyltransferase in both the brain and peripheral tissues",
            "It inhibits monoamine oxidase B within dopaminergic neurons",
            "It increases levodopa transport across the blood-brain barrier",
            "It inhibits peripheral aromatic L-amino acid decarboxylase without substantially entering the brain",
        ],
        4,
        "Carbidopa inhibits peripheral aromatic L-amino acid decarboxylase and penetrates the CNS poorly. It therefore reduces peripheral conversion of levodopa to dopamine, leaving more levodopa available to cross the blood-brain barrier while decreasing peripheral dopaminergic adverse effects.",
        tags=["parkinson-disease", "levodopa", "carbidopa"],
        item_family="treatment-mechanism",
    ),
    question(
        11,
        "Opioid Analgesics",
        23,
        "Recognition and Reversal of Opioid Toxicity",
        1,
        484,
        "An unconscious 26-year-old man is brought to the emergency department. Respirations are 4/min, pulse is 58/min, and blood pressure is 92/54 mm Hg. Examination shows cyanosis, pinpoint pupils, and decreased bowel sounds. Intranasal naloxone produces a rapid improvement in ventilation and alertness, but respiratory depression recurs 45 minutes later. Which of the following is the most likely diagnosis?",
        [
            "Antimuscarinic poisoning",
            "Carbon monoxide poisoning",
            "Opioid poisoning",
            "Organophosphate poisoning",
            "Sedative-hypnotic withdrawal",
        ],
        2,
        "Profound respiratory depression, miosis, and reduced gastrointestinal motility indicate opioid toxicity. Rapid reversal by naloxone strongly supports the diagnosis. Recurrence can occur because naloxone has a shorter duration than many opioid agonists, so repeat dosing or infusion may be required.",
        tags=["opioid-overdose", "naloxone", "respiratory-depression"],
        item_family="diagnosis",
    ),
    question(
        12,
        "Local Anesthetics",
        25,
        "Bupivacaine Cardiotoxicity",
        1,
        515,
        "A 31-year-old woman in labor receives epidural bupivacaine. Immediately after a repeat injection, she reports circumoral numbness and tinnitus and then develops seizures and a ventricular arrhythmia. Inadvertent intravascular administration is suspected. Interaction with which of the following molecular targets most directly underlies both the desired nerve block and this drug's cardiac conduction toxicity?",
        [
            "Extracellular ligand-binding site of nicotinic acetylcholine channels",
            "Intracellular pore of voltage-gated sodium channels",
            "Ryanodine receptors of the sarcoplasmic reticulum",
            "Transmembrane pore of L-type calcium channels",
            "Voltage sensor of delayed-rectifier potassium channels",
        ],
        1,
        "Local anesthetics such as bupivacaine enter excitable cells and bind within the pore of voltage-gated sodium channels, preferentially when channels are open or inactivated. Sodium-current blockade prevents nerve action-potential propagation and can also impair cardiac conduction and trigger serious arrhythmias.",
        difficulty="hard",
        tags=["bupivacaine", "local-anesthetic-toxicity", "sodium-channels"],
        item_family="mechanism",
    ),
    question(
        13,
        "Drugs Affecting Renal Excretory Function",
        29,
        "Thiazides and Urinary Calcium",
        2,
        586,
        "A 52-year-old woman with hypertension has had three episodes of calcium oxalate nephrolithiasis. Serum calcium and parathyroid hormone concentrations are normal, but 24-hour urine collection shows idiopathic hypercalciuria. Hydrochlorothiazide is started. Which of the following changes is most likely during treatment?",
        [
            "Increased urinary uric acid excretion",
            "Decreased proximal tubular sodium reabsorption",
            "Increased free-water clearance",
            "Increased urinary potassium retention",
            "Decreased urinary calcium excretion",
        ],
        4,
        "Thiazides decrease urinary calcium excretion and are useful in recurrent calcium nephrolithiasis with hypercalciuria. Mild volume contraction increases proximal sodium and calcium reabsorption, and blockade of the distal sodium-chloride cotransporter also favors distal calcium entry.",
        tags=["thiazide", "hypercalciuria", "nephrolithiasis"],
        item_family="predicted-finding",
    ),
    question(
        14,
        "Therapy of Heart Failure",
        33,
        "ACE and Neprilysin Inhibition",
        1,
        674,
        "A 63-year-old man with heart failure and reduced ejection fraction takes lisinopril. Because he remains symptomatic, sacubitril/valsartan is started without an interval after the last lisinopril dose. Several hours later, he develops marked swelling of the lips and tongue. Concurrent inhibition of which of the following processes most likely increased his risk for this adverse effect?",
        [
            "Synthesis of angiotensinogen and release of renin",
            "Binding of angiotensin II to AT1 and AT2 receptors",
            "Conversion of angiotensin I and release of aldosterone",
            "Degradation of bradykinin and substance P by two peptidases",
            "Formation and receptor binding of atrial natriuretic peptide",
        ],
        3,
        "ACE and neprilysin both participate in degrading vasoactive peptides, including bradykinin and substance P. Giving an ACE inhibitor together with a neprilysin inhibitor can cause excessive peptide accumulation and substantially increase the risk of angioedema.",
        tags=["heart-failure", "sacubitril", "ace-inhibitor", "angioedema"],
        item_family="mechanism",
    ),
    question(
        15,
        "Antiarrhythmic Drugs",
        34,
        "Adenosine and AV Nodal Reentry",
        1,
        701,
        "A 35-year-old woman comes to the emergency department with sudden palpitations. ECG shows a regular narrow-complex tachycardia at 190/min. Vagal maneuvers are unsuccessful. A rapid intravenous injection terminates the rhythm within seconds and briefly causes flushing and chest pressure. Which of the following cellular effects most directly explains termination of this arrhythmia?",
        [
            "Activation of an atrial potassium current with hyperpolarization and transient AV nodal block",
            "Blockade of fast sodium channels in ventricular Purkinje fibers",
            "Inhibition of the sodium-potassium ATPase with increased vagal tone",
            "Prolongation of ventricular repolarization by delayed-rectifier potassium-channel blockade",
            "Use-dependent blockade of L-type calcium channels in ventricular myocytes",
        ],
        0,
        "Adenosine activates an acetylcholine-sensitive potassium current in atrial, sinus-node, and AV-node tissue. The resulting hyperpolarization and reduction of cyclic AMP-dependent calcium current transiently block AV nodal conduction and can terminate AV nodal reentrant tachycardia.",
        tags=["adenosine", "psvt", "av-node"],
        item_family="treatment-mechanism",
    ),
    question(
        16,
        "Blood Coagulation and Anticoagulant Drugs",
        36,
        "Heparin-Induced Thrombocytopenia",
        1,
        735,
        "A 68-year-old man with chronic kidney disease develops a painful swollen leg 7 days after unfractionated heparin was begun for an acute coronary syndrome. Ultrasonography shows a new femoral-vein thrombosis. Heparin is discontinued.",
        [
            "Enoxaparin",
            "Argatroban",
            "Unfractionated heparin at a lower dose",
            "Warfarin alone immediately",
            "No anticoagulant until the platelet count normalizes",
        ],
        1,
        "The platelet fall beginning 5-10 days after heparin exposure plus new thrombosis indicates immune heparin-induced thrombocytopenia. All heparin must be stopped and a nonheparin anticoagulant started. Argatroban directly inhibits thrombin and is hepatically cleared, making it useful when renal function is poor.",
        tags=["heparin-induced-thrombocytopenia", "argatroban", "direct-thrombin-inhibitor"],
        lead_in="Which of the following is the most appropriate next pharmacotherapy?",
        laboratory_findings=[
            {"test": "Platelet count at admission", "value": "232,000/mm3", "reference": "150,000-400,000/mm3"},
            {"test": "Current platelet count", "value": "78,000/mm3", "reference": "150,000-400,000/mm3"},
            {"test": "Serum creatinine", "value": "3.1 mg/dL", "reference": "0.6-1.2 mg/dL"},
            {"test": "AST", "value": "24 U/L", "reference": "10-40 U/L"},
        ],
        item_family="treatment",
    ),
    question(
        17,
        "Pharmacotherapy of Inflammation, Fever, Pain, and Gout",
        42,
        "Acid-Base Effects of Salicylate Toxicity",
        1,
        858,
        "A 19-year-old woman is brought to the emergency department because of vomiting, tinnitus, confusion, and rapid breathing after ingesting a large number of aspirin tablets. Temperature is 38.6 C (101.5 F), and respirations are 32/min.",
        [
            "Central respiratory depression with renal bicarbonate retention",
            "Direct medullary respiratory stimulation with uncoupling of oxidative phosphorylation",
            "Inhibition of carbonic anhydrase with suppression of organic-acid production",
            "Inhibition of mitochondrial electron transport with compensatory hypoventilation",
            "Peripheral chemoreceptor blockade with increased renal acid excretion",
        ],
        1,
        "Salicylates directly stimulate the medullary respiratory center, producing primary respiratory alkalosis. They also uncouple oxidative phosphorylation, increasing carbon dioxide, heat, and organic-acid production and causing a concurrent anion-gap metabolic acidosis.",
        tags=["salicylate-toxicity", "acid-base", "oxidative-phosphorylation"],
        lead_in="Which of the following mechanisms best explains this acid-base pattern?",
        laboratory_findings=[
            {"test": "Arterial pH", "value": "7.49", "reference": "7.35-7.45"},
            {"test": "Pco2", "value": "22 mm Hg", "reference": "35-45 mm Hg"},
            {"test": "Serum bicarbonate", "value": "16 mEq/L", "reference": "22-28 mEq/L"},
            {"test": "Serum anion gap", "value": "22 mEq/L", "reference": "8-12 mEq/L"},
        ],
        item_family="physiologic-prediction",
    ),
    question(
        18,
        "Pulmonary Pharmacology",
        44,
        "Biologic Therapy for Eosinophilic Asthma",
        1,
        909,
        "A 45-year-old woman with asthma has had four exacerbations requiring oral glucocorticoids during the past year despite adherence to high-dose inhaled glucocorticoid and long-acting beta-2 agonist therapy. Skin testing for perennial allergens is negative. Spirometry shows reversible airflow obstruction.",
        [
            "Binds circulating interleukin-5",
            "Blocks cysteinyl leukotriene receptors",
            "Blocks immunoglobulin E binding to its high-affinity receptor",
            "Inhibits phosphodiesterase 4 in inflammatory cells",
            "Stimulates beta-2 receptors on airway smooth muscle",
        ],
        0,
        "Marked blood eosinophilia and recurrent exacerbations identify severe eosinophilic asthma. Mepolizumab is a monoclonal antibody that binds circulating interleukin-5, reducing eosinophil survival and eosinophilic airway inflammation.",
        tags=["asthma", "mepolizumab", "interleukin-5", "eosinophils"],
        lead_in="A drug chosen specifically for this patient's phenotype would most likely have which of the following actions?",
        laboratory_findings=[
            {"test": "Blood eosinophils", "value": "920/mm3", "reference": "<500/mm3"},
            {"test": "Total serum IgE", "value": "42 IU/mL", "reference": "0-100 IU/mL"},
        ],
        item_family="treatment-mechanism",
    ),
    question(
        19,
        "Endocrine Pancreas and Pharmacotherapy of Diabetes Mellitus",
        51,
        "SGLT2 Inhibitor-Associated Ketoacidosis",
        1,
        1059,
        "A 58-year-old man with type 2 diabetes mellitus takes metformin and empagliflozin. Two days after the onset of viral gastroenteritis with poor oral intake, he develops nausea, abdominal pain, and deep rapid respirations. Urinalysis shows marked glucosuria and ketonuria.",
        [
            "An alpha-glucosidase inhibitor",
            "A dipeptidyl peptidase-4 inhibitor",
            "A glucagon-like peptide-1 receptor agonist",
            "A sodium-glucose cotransporter 2 inhibitor",
            "A sulfonylurea",
        ],
        3,
        "Empagliflozin inhibits SGLT2 in the proximal tubule and can precipitate diabetic ketoacidosis during illness, fasting, or relative insulin deficiency. Continued urinary glucose loss can keep the serum glucose only mildly elevated despite substantial ketogenesis and anion-gap acidosis.",
        tags=["sglt2-inhibitor", "empagliflozin", "euglycemic-ketoacidosis"],
        lead_in="Which of the following drug classes most likely contributed to this patient's metabolic disorder?",
        laboratory_findings=[
            {"test": "Serum glucose", "value": "184 mg/dL", "reference": "70-100 mg/dL"},
            {"test": "Serum bicarbonate", "value": "12 mEq/L", "reference": "22-28 mEq/L"},
            {"test": "Serum anion gap", "value": "24 mEq/L", "reference": "8-12 mEq/L"},
            {"test": "Beta-hydroxybutyrate", "value": "6.2 mmol/L", "reference": "<0.4 mmol/L"},
        ],
        difficulty="hard",
        item_family="mechanism",
    ),
    question(
        20,
        "Dermatological Pharmacology",
        75,
        "Counseling About Isotretinoin Exposure",
        1,
        1500,
        "A 23-year-old woman who takes isotretinoin for severe nodulocystic acne learns that she is 6 weeks pregnant. She begins to cry and says, \"I was careful, but I must have harmed my baby. What am I supposed to do now?\" Which of the following is the most appropriate initial response by the physician?",
        [
            "Because fetal injury is certain, termination of pregnancy is the only medically appropriate choice",
            "Do not blame yourself; many people have difficulty following medication precautions",
            "I can see how frightened you are; tell me what you understand about isotretinoin exposure, and then we can discuss the next steps together",
            "The risk is probably small because your pregnancy was recognized early",
            "You should stop the drug now and return after you have decided whether to continue the pregnancy",
        ],
        2,
        "The best initial response acknowledges the patient's emotion and invites her perspective before giving information. Systemic retinoids are highly teratogenic, so isotretinoin should be stopped and urgent, nonjudgmental counseling arranged, but the physician should not assume the patient's decision or falsely reassure her.",
        tags=["isotretinoin", "teratogenicity", "patient-communication"],
        item_family="communication-ethics",
    ),
]


def validate_questions():
    assert len(QUESTIONS) == 20
    assert len({item["id"] for item in QUESTIONS}) == 20
    for item in QUESTIONS:
        assert item["source"] == "usmle"
        assert item["subjectId"] == "pharmacology"
        assert len(item["options"]) == 5
        assert len(set(item["options"])) == 5
        assert 0 <= item["answerIndex"] < len(item["options"])
        assert item["answer"] == item["options"][item["answerIndex"]]
        assert (item["leadIn"] or item["prompt"]).strip().endswith("?")
        assert item["explanation"].strip()
        assert not item["imageUrls"]
        for finding in item["laboratoryFindings"]:
            assert set(finding) == {"test", "value", "reference"}
            assert all(str(value).strip() for value in finding.values())

    item_families = [item["itemFamily"] for item in QUESTIONS]
    assert item_families.count("diagnosis") == 1
    assert item_families.count("communication-ethics") == 1
    assert item_families.count("experimental-design") == 1
    assert sum(bool(item["laboratoryFindings"]) for item in QUESTIONS) == 5


def main():
    validate_questions()
    database = json.loads(DATABASE_PATH.read_text(encoding="utf-8-sig"))
    existing = database.get("questions", [])
    retained = [item for item in existing if not str(item.get("id", "")).startswith(ID_PREFIX)]
    database["questions"] = [*retained, *QUESTIONS]
    DATABASE_PATH.write_text(json.dumps(database, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Stored {len(QUESTIONS)} USMLE Step 1-style pharmacology questions.")
    print(f"Database question count: {len(existing)} -> {len(database['questions'])}")


if __name__ == "__main__":
    main()
