import json
import re
from pathlib import Path

DATA_PATHS = [Path("runtime-data/users.json"), Path("data/users.json")]
SUBJECT_ID = "general-medicine"
SUBJECT_TITLE = "General Medicine"
CHAPTER = "Disorders of the Cardiovascular System"
CHAPTER_ORDER = 6
SOURCE_PDF = "medicine 1"


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def q(prompt, answer, wrong, explanation, clinical=False):
    return {
        "prompt": prompt.strip(),
        "options": [answer, *wrong],
        "answerIndex": 0,
        "answer": answer,
        "explanation": explanation,
        "difficulty": "high" if clinical else "moderate",
        "tags": ["clinical"] if clinical else [],
    }


TOPICS = [
    ("Introduction to Cardiovascular Disorders", [
        q("The most useful first step in approaching cardiovascular disease is to classify the problem by", "Syndrome and hemodynamic consequence", ["Drug brand", "Patient age alone", "Single enzyme value alone"], "Cardiovascular diagnosis starts by defining the clinical syndrome and its effect on perfusion or congestion."),
        q("Cardiac output is determined directly by", "Heart rate multiplied by stroke volume", ["Mean arterial pressure divided by hematocrit", "Venous pressure plus pulse pressure", "Ejection fraction multiplied by creatinine"], "Cardiac output equals heart rate times stroke volume."),
        q("Mean arterial pressure is most closely related to", "Cardiac output and systemic vascular resistance", ["Serum sodium and potassium", "Platelet count and fibrinogen", "Residual lung volume only"], "Arterial pressure depends mainly on flow generated by the heart and vascular resistance."),
        q("A patient with cold clammy extremities, confusion and systolic BP 78 mmHg after chest pain has which cardiovascular emergency?", "Cardiogenic shock", ["Stable exertional angina", "Simple vasovagal prodrome", "Isolated venous insufficiency"], "Hypotension with hypoperfusion after ischemic symptoms suggests pump failure from cardiogenic shock.", True),
        q("Raised jugular venous pressure most directly reflects", "Elevated right atrial pressure", ["Low left ventricular afterload", "Low intracranial pressure", "High serum albumin"], "The internal jugular venous column estimates right atrial pressure."),
        q("Dependent pitting edema in heart disease usually reflects", "Systemic venous congestion with sodium and water retention", ["Pure arterial embolism", "Low red cell deformability", "Isolated bronchospasm"], "Heart failure promotes venous hypertension and renal salt-water retention."),
        q("A displaced, diffuse apical impulse suggests", "Left ventricular enlargement", ["Small pericardial effusion only", "Isolated right atrial thrombus", "Normal cardiac size always"], "Volume or pressure overload can enlarge the left ventricle and displace the apex."),
        q("A 64-year-old with long-standing hypertension has exertional dyspnea, S4 and concentric LV hypertrophy. The dominant mechanism is", "Pressure overload causing diastolic dysfunction", ["Acute valve rupture", "Primary pericardial infection", "Right-to-left shunt"], "Hypertension produces pressure overload, LV hypertrophy and impaired relaxation.", True),
        q("Cyanosis in cardiovascular disease most often implies", "Increased deoxygenated hemoglobin in arterial or capillary blood", ["High serum calcium", "High platelet count", "Low plasma albumin only"], "Visible cyanosis reflects a sufficient amount of reduced hemoglobin."),
        q("Syncope during exertion is concerning because it may indicate", "Fixed outflow obstruction or malignant arrhythmia", ["Simple postprandial fullness", "Mild allergic rhinitis", "Iron deficiency without hemodynamic effect"], "Exertional syncope is a red flag for structural or rhythm-related cardiovascular disease."),
        q("A young athlete collapses during sprinting and has a harsh systolic murmur that increases with Valsalva. Most likely diagnosis?", "Hypertrophic obstructive cardiomyopathy", ["Vasovagal syncope", "Acute pericarditis", "Mitral stenosis"], "Dynamic LV outflow obstruction worsens with reduced preload and can cause exertional syncope.", True),
        q("Orthopnea in heart failure occurs mainly because lying flat", "Increases venous return and pulmonary venous congestion", ["Reduces bronchial secretions", "Stops all sympathetic tone", "Eliminates left atrial pressure"], "Recumbency redistributes fluid centrally and worsens pulmonary congestion."),
        q("A new loud holosystolic murmur with pulmonary edema after myocardial infarction suggests", "Acute mitral regurgitation from papillary muscle dysfunction or rupture", ["Benign flow murmur", "Tricuspid stenosis", "Chronic venous thrombosis"], "Post-MI papillary muscle injury can cause abrupt severe MR and pulmonary edema.", True),
        q("The most important modifiable cardiovascular risk factor at the population level is", "Hypertension", ["Eye color", "Blood group alone", "Height"], "Hypertension strongly drives stroke, heart failure, kidney disease and ischemic events."),
    ]),
    ("Diagnosis of Cardiovascular Disorders", [
        q("The 12-lead ECG is most useful for rapid evaluation of", "Rhythm, conduction, ischemia and chamber clues", ["Serum cholesterol synthesis", "Coronary plaque histology", "Valve leaflet calcium content exactly"], "ECG provides immediate electrical and ischemic information."),
        q("ST-segment elevation in contiguous leads during chest pain most strongly suggests", "Acute transmural myocardial injury", ["Stable anemia only", "Primary hypothyroidism", "Simple musculoskeletal pain"], "Contiguous ST elevation in the right setting is treated as acute coronary occlusion until proven otherwise."),
        q("A patient with crushing chest pain has ST elevation in II, III and aVF. Which territory is most likely involved?", "Inferior wall myocardial infarction", ["Anterior septum only", "High lateral wall only", "Posterior fossa"], "Inferior leads II, III and aVF reflect the inferior LV wall.", True),
        q("Cardiac troponin is preferred for myocardial injury because it is", "Sensitive and relatively specific for cardiac myocyte injury", ["A direct measure of coronary artery diameter", "Normal in all myocarditis", "Specific for pulmonary embolism"], "Troponin rises after cardiac myocyte necrosis from ischemic and nonischemic causes."),
        q("A normal initial troponin early after chest pain does not exclude MI because", "Troponin may require serial testing to rise", ["Troponin never rises in MI", "ECG is never useful", "Pain timing is irrelevant"], "Serial troponins are needed when presentation is early or suspicion remains."),
        q("Echocardiography is best for bedside assessment of", "Ventricular function, valves, pericardium and wall motion", ["LDL particle number", "Platelet aggregation", "Renal tubular transport"], "Echo directly images cardiac structure and function."),
        q("A breathless patient has hypotension, muffled heart sounds and distended neck veins. Which test can rapidly support the diagnosis?", "Bedside echocardiography", ["Colonoscopy", "Spirometry alone", "Bone scan"], "Echo can show pericardial effusion and tamponade physiology.", True),
        q("BNP or NT-proBNP is most helpful when evaluating", "Suspected heart failure in a dyspneic patient", ["Appendicitis", "Iron deficiency without dyspnea", "Migraine aura"], "Natriuretic peptides rise with myocardial wall stress."),
        q("Exercise stress testing is most appropriate when", "Stable ischemic symptoms need risk assessment and the patient can exercise with interpretable ECG", ["STEMI is obvious", "The patient is in shock", "Severe aortic stenosis is symptomatic and unstable"], "Stress testing is for selected stable patients, not emergencies."),
        q("Coronary angiography directly defines", "Coronary artery lumen anatomy and obstructive lesions", ["Myocyte oxygen extraction precisely", "Serum triglyceride synthesis", "Pulmonary surfactant level"], "Angiography visualizes coronary stenosis and guides revascularization."),
        q("A patient with ongoing chest pain, dynamic ST depression and rising troponin should be evaluated for", "Non-ST elevation acute coronary syndrome with early invasive risk stratification", ["Benign reflux only", "Simple viral fever", "Stable varicose veins"], "Dynamic ECG change plus troponin rise indicates high-risk ACS.", True),
        q("Ambulatory Holter monitoring is most useful for", "Intermittent palpitations or syncope suspected to be arrhythmic", ["Persistent hyperkalemia grading", "Valve area measurement", "Coronary calcium scoring"], "Holter or event monitoring captures intermittent rhythm abnormalities."),
        q("Ankle-brachial index below normal supports", "Peripheral arterial disease", ["Primary lymphedema only", "Migraine", "Mitral valve prolapse"], "ABI compares ankle to arm systolic pressures and screens for limb arterial obstruction."),
        q("A man has exertional calf pain relieved by rest and ABI 0.62. The diagnosis is", "Peripheral arterial disease causing intermittent claudication", ["Deep vein thrombosis", "Restless leg syndrome only", "Lumbar meningitis"], "Exertional reproducible calf pain with low ABI is classic claudication.", True),
    ]),
    ("Disorders of Rhythm", [
        q("Atrial fibrillation is defined by", "Irregularly irregular rhythm with absent discrete P waves", ["Regular sawtooth flutter waves only", "Wide QRS in every beat", "Sinus rhythm with respiratory variation"], "AF has chaotic atrial activity and an irregular ventricular response."),
        q("The major preventable complication of atrial fibrillation is", "Thromboembolic stroke", ["Acute appendicitis", "Primary hyperparathyroidism", "Nephrotic-range proteinuria"], "Stasis in the atria, especially the left atrial appendage, can form embolic thrombi."),
        q("A 72-year-old with hypertension has irregularly irregular pulse and no P waves. What long-term decision is central?", "Assess stroke risk and need for anticoagulation", ["Give thrombolysis to every patient", "Avoid rate control", "Ignore duration of symptoms"], "AF care includes rate or rhythm control and anticoagulation based on thromboembolic risk.", True),
        q("Atrial flutter classically shows", "Sawtooth flutter waves", ["Delta waves in every lead", "Complete absence of atrial activity", "Osborn waves"], "Typical flutter creates sawtooth atrial activity, often best seen in inferior leads."),
        q("Paroxysmal supraventricular tachycardia usually presents as", "Abrupt-onset regular narrow-complex tachycardia", ["Slow irregular escape rhythm", "Persistent ST elevation only", "Wide pulse pressure without tachycardia"], "AVNRT and related SVTs often start and stop suddenly with regular narrow QRS complexes."),
        q("A stable young patient has sudden regular narrow-complex tachycardia at 180/min. Initial maneuver?", "Vagal maneuver", ["Immediate fibrinolysis", "Permanent pacemaker first", "High-dose loop diuretic"], "Vagal maneuvers can terminate AV node-dependent SVT.", True),
        q("Ventricular tachycardia should be suspected when", "A regular wide-complex tachycardia occurs, especially with structural heart disease", ["Sinus bradycardia follows sleep", "P waves are upright before every QRS", "PR interval is fixed and normal"], "Most wide regular tachycardias in adults with heart disease are treated as VT."),
        q("Pulseless ventricular tachycardia requires", "Immediate defibrillation and resuscitation", ["Oral beta blocker only", "Routine outpatient Holter", "Slow IV fluids without CPR"], "Pulseless VT is a shockable cardiac arrest rhythm."),
        q("A man becomes unresponsive; monitor shows chaotic irregular waveform without QRS complexes. Best action?", "Immediate defibrillation for ventricular fibrillation", ["Carotid massage", "Oral aspirin only", "Elective cardioversion next week"], "VF causes cardiac arrest and needs immediate defibrillation.", True),
        q("First-degree AV block means", "PR interval prolongation with every P wave conducted", ["Dropped QRS after every P wave", "Complete AV dissociation", "Absent P waves"], "First-degree block is delayed AV conduction without dropped beats."),
        q("Mobitz type II AV block is clinically important because it", "Can progress abruptly to complete heart block", ["Is always benign in athletes", "Never needs pacing evaluation", "Only occurs with fever"], "Infranodal conduction disease carries high risk of progression."),
        q("Complete heart block shows", "AV dissociation between atrial and ventricular rhythms", ["Normal PR interval in all beats", "Only sinus tachycardia", "Narrow QRS always with normal rate"], "Third-degree block has independent atrial and ventricular pacemakers."),
        q("A patient has syncope, heart rate 32/min and complete AV dissociation. Most appropriate treatment?", "Urgent pacing", ["Observe for one year", "Give adenosine", "Start anticoagulation only"], "Symptomatic complete heart block requires temporary and often permanent pacing.", True),
        q("Torsades de pointes is associated with", "Prolonged QT interval", ["Short PR interval only", "High platelet count", "Low LDL"], "QT prolongation predisposes to polymorphic VT called torsades."),
    ]),
    ("Disorders of the Heart", [
        q("Heart failure is best defined as", "A clinical syndrome in which cardiac dysfunction causes congestion or inadequate perfusion", ["Any heart murmur", "Only low ejection fraction", "Chest pain from any cause"], "Heart failure can occur with reduced or preserved EF and is defined clinically."),
        q("Left-sided heart failure commonly causes", "Pulmonary congestion and dyspnea", ["Isolated jaundice", "Painless hematuria", "Hyperreflexia only"], "Elevated left-sided filling pressures transmit to pulmonary veins."),
        q("A patient has orthopnea, basal crackles, S3 and leg edema. Most likely syndrome?", "Congestive heart failure", ["Uncomplicated migraine", "Acute cystitis", "Primary hypothyroidism only"], "Orthopnea, crackles, S3 and edema fit decompensated heart failure.", True),
        q("Heart failure with preserved ejection fraction is commonly driven by", "Impaired ventricular relaxation and increased filling pressures", ["Absent atrial contraction in all cases", "Only congenital cyanosis", "Low systemic vascular resistance always"], "HFpEF is often a diastolic filling problem, especially with hypertension and aging."),
        q("Aortic stenosis classically causes exertional dyspnea, angina and syncope because", "Fixed LV outflow obstruction limits cardiac output during exertion", ["Mitral inflow obstruction causes isolated hemoptysis", "Venous thrombosis reduces preload only at rest", "Pulmonary surfactant deficiency narrows the aortic valve"], "The symptom triad of aortic stenosis reflects inability to increase forward flow across a fixed obstruction.", True),
        q("A harsh crescendo-decrescendo systolic murmur radiating to the carotids suggests", "Aortic stenosis", ["Mitral stenosis", "Tricuspid regurgitation", "Patent ductus arteriosus"], "Aortic stenosis produces an ejection systolic murmur radiating to the neck."),
        q("Aortic regurgitation commonly produces", "Wide pulse pressure with early diastolic decrescendo murmur", ["Fixed split S2 only", "Opening snap with rumble only", "Continuous machinery murmur only"], "Diastolic backflow from aorta to LV creates volume overload and wide pulse pressure."),
        q("Mitral stenosis is most often associated worldwide with", "Rheumatic heart disease", ["Marfan syndrome only", "Acute viral myocarditis", "Atrial septal defect only"], "Rheumatic valve damage classically narrows the mitral valve."),
        q("A woman with rheumatic disease has dyspnea, loud S1, opening snap and mid-diastolic rumble. Diagnosis?", "Mitral stenosis", ["Aortic regurgitation", "Pulmonary embolism", "Ventricular septal defect"], "Opening snap followed by diastolic rumble is classic for mitral stenosis.", True),
        q("Acute pericarditis classically causes chest pain that", "Improves sitting forward and worsens lying down or with inspiration", ["Occurs only during urination", "Is never positional", "Always improves with exertion"], "Pericardial pain is pleuritic and positional."),
        q("Diffuse ST elevation with PR depression on ECG suggests", "Acute pericarditis", ["Hyperkalemia only", "Inferior STEMI in all cases", "First-degree AV block only"], "Pericarditis produces widespread inflammatory ST changes and PR depression."),
        q("Cardiac tamponade causes shock because", "Pericardial pressure restricts diastolic filling", ["Coronary plaques dissolve", "The QT interval shortens", "Hemoglobin rises abruptly"], "Fluid under pressure prevents ventricular filling and lowers stroke volume."),
        q("A patient with cancer develops hypotension, raised JVP and muffled heart sounds. Most likely diagnosis?", "Cardiac tamponade", ["Stable angina", "Essential hypertension", "Simple pleurisy"], "Beck triad suggests tamponade, often confirmed by urgent echocardiography.", True),
        q("Dilated cardiomyopathy primarily causes", "Systolic pump failure with ventricular dilation", ["Pure valve stenosis", "Only pericardial calcification", "Normal chamber size with no dysfunction"], "Dilated cardiomyopathy impairs contraction and enlarges ventricular chambers."),
    ]),
    ("Coronary and Peripheral Vascular Disease", [
        q("Stable angina results from", "Fixed coronary stenosis causing demand ischemia during exertion", ["Complete plaque rupture every time", "Pure pericardial inflammation", "Pulmonary venous thrombosis"], "Stable angina is predictable ischemic discomfort due to supply-demand mismatch."),
        q("Unstable angina differs from stable angina by", "New, worsening or rest angina without biomarker evidence of necrosis", ["Pain only after heavy meals", "Normal coronary risk always", "Mandatory fever"], "Unstable angina is an acute coronary syndrome without troponin rise."),
        q("NSTEMI is diagnosed when ischemic symptoms are accompanied by", "Elevated cardiac troponin without persistent ST elevation", ["Normal biomarkers always", "Only a systolic murmur", "Low ankle-brachial index alone"], "Troponin elevation distinguishes NSTEMI from unstable angina."),
        q("A 56-year-old has 30 minutes of crushing chest pain, diaphoresis and anterior ST elevation. Best immediate goal?", "Urgent reperfusion therapy", ["Outpatient lipid review only", "Exercise stress test first", "Delay until troponin peaks"], "STEMI management prioritizes rapid PCI or fibrinolysis when indicated.", True),
        q("Atherosclerosis begins with", "Endothelial dysfunction and lipid entry into the arterial intima", ["Venous valve rupture", "Platelet deficiency", "Low lymphatic flow only"], "Endothelial injury permits LDL retention, inflammation and plaque formation."),
        q("The most important modifiable risks for coronary disease include", "Smoking, hypertension, diabetes and dyslipidemia", ["Eye color, height and handedness", "Blood group alone", "Hair texture"], "These risk factors drive atherosclerosis and are targets for prevention."),
        q("A high-intensity statin reduces coronary risk mainly by", "Lowering LDL cholesterol and stabilizing atherosclerotic plaque", ["Increasing platelet adhesion", "Raising blood glucose intentionally", "Blocking all cardiac conduction"], "Statins lower LDL and have plaque-stabilizing anti-inflammatory effects."),
        q("Peripheral arterial disease usually presents with", "Exertional limb pain relieved by rest", ["Pain only when lying down after meals", "Bilateral hand tremor", "Photophobia"], "Claudication is reproducible muscle ischemia during walking."),
        q("A smoker has calf pain after walking 100 meters, diminished pulses and cool shiny skin. Diagnosis?", "Peripheral arterial disease", ["Deep vein thrombosis", "Cellulitis", "Gout"], "Exertional calf pain with reduced pulses and trophic skin change indicates PAD.", True),
        q("Critical limb ischemia is suggested by", "Rest pain, ulcers or gangrene from severe arterial obstruction", ["Only ankle swelling after standing", "Brief cramps after dehydration", "Normal pulses with warm foot"], "Rest pain and tissue loss indicate severe limb-threatening ischemia."),
        q("An acutely painful pale cold pulseless leg requires", "Emergency evaluation for acute limb ischemia and revascularization", ["Topical steroid only", "Routine follow-up in months", "Compression stockings first"], "The six Ps of acute limb ischemia are vascular emergencies.", True),
        q("Abdominal aortic aneurysm is most associated with", "Older age, male sex, smoking and atherosclerotic risk", ["Childhood asthma only", "Low dietary calcium", "Migraine"], "Smoking and age are major AAA risk factors."),
        q("A hypotensive older smoker has sudden back/abdominal pain and pulsatile abdominal mass. Most likely emergency?", "Ruptured abdominal aortic aneurysm", ["Renal colic only", "Peptic dyspepsia", "Acute cystitis"], "Pain, shock and pulsatile mass are classic for ruptured AAA.", True),
        q("Secondary prevention after myocardial infarction commonly includes", "Antiplatelet therapy, statin, risk factor control and selected beta blocker or ACE inhibitor", ["Stopping all exercise forever", "Antibiotics for life", "Avoiding lipid treatment"], "Post-MI care reduces recurrent ischemic events and remodeling risk."),
    ]),
]


def build_questions():
    questions = []
    for topic_order, (topic, rows) in enumerate(TOPICS, 1):
        if len(rows) != 14:
            raise ValueError(f"{topic} has {len(rows)} questions, expected 14")
        clinical_count = sum(1 for row in rows if "clinical" in row.get("tags", []))
        if clinical_count != 4:
            raise ValueError(f"{topic} has {clinical_count} clinical questions, expected 4")
        topic_slug = slugify(topic)
        for question_order, row in enumerate(rows, 1):
            questions.append({
                "id": f"medicine-cardiovascular-disorders-{topic_slug}-{question_order:02d}",
                "subjectId": SUBJECT_ID,
                "subjectTitle": SUBJECT_TITLE,
                "chapterTitle": CHAPTER,
                "chapterOrder": CHAPTER_ORDER,
                "topic": topic,
                "topicTitle": topic,
                "topicOrder": topic_order,
                "source": "ai",
                "sourcePdf": SOURCE_PDF,
                "imageUrls": [],
                **row,
            })
    return questions


def update(path):
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    questions = build_questions()
    data["questions"] = [
        item for item in data.get("questions", [])
        if not (item.get("subjectId") == SUBJECT_ID and item.get("chapterTitle") == CHAPTER)
    ] + questions
    if len(questions) != 70:
        raise AssertionError(f"Expected 70 questions, got {len(questions)}")
    if len({item["id"] for item in questions}) != 70:
        raise AssertionError("Duplicate cardiovascular disorder question ids")
    if any(item["answer"] != item["options"][item["answerIndex"]] for item in questions):
        raise AssertionError("Answer mismatch found")
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main():
    for path in DATA_PATHS:
        update(path)
        print(f"Updated {path} with 70 Disorders of the Cardiovascular System questions.")


if __name__ == "__main__":
    main()
