import json
from pathlib import Path

DATA = Path("runtime-data/users.json")
CHAPTER = "Modulation of Pulmonary, Renal, and Cardiovascular"
BASE = {"subjectId": "pharmacology", "subjectTitle": "Pharmacology", "chapterTitle": CHAPTER, "source": "ai", "imageUrls": []}


def q(prompt, answer, wrong, explanation):
    return {"prompt": prompt, "answer": answer, "wrong": wrong, "explanation": explanation}


TOPICS = [
    ("renal-excretory-function", "Drugs Affecting Renal Excretory Function", [
        q("A patient with acute pulmonary edema needs rapid venodilation and strong diuresis. Which drug blocks NKCC2 in the thick ascending limb?", "Furosemide", ["Hydrochlorothiazide", "Amiloride", "Mannitol"], "Loop diuretics inhibit NKCC2, causing potent natriuresis and early venodilation useful in pulmonary edema."),
        q("A patient on furosemide develops muscle weakness, metabolic alkalosis, and low potassium. The main renal mechanism is:", "Increased distal sodium delivery with aldosterone-mediated potassium and hydrogen secretion", ["Direct blockade of ENaC", "Reduced bicarbonate reabsorption in proximal tubule only", "Inhibition of ADH receptors"], "Loop and thiazide diuretics increase distal sodium delivery, promoting K+ and H+ loss."),
        q("A patient with calcium oxalate stones and hypercalciuria is treated with hydrochlorothiazide because it:", "Increases distal tubular calcium reabsorption", ["Inhibits collecting duct ENaC", "Blocks aldosterone receptors", "Osmotically traps water only"], "Thiazides reduce urinary calcium and can help prevent calcium stones."),
        q("A cirrhotic patient with ascites and hyperaldosteronism is started on spironolactone. Which adverse effect is most mechanistically expected?", "Hyperkalemia and gynecomastia", ["Ototoxicity and hypocalcemia", "Severe hypouricemia", "Cyanide toxicity"], "Spironolactone blocks mineralocorticoid receptors and also interacts with steroid receptors."),
        q("A patient taking trimethoprim develops hyperkalemia similar to potassium-sparing diuretics. Which nephron target is functionally inhibited?", "Epithelial sodium channel in the collecting duct", ["Na-K-2Cl cotransporter", "Na-Cl cotransporter", "Carbonic anhydrase in red cells only"], "Trimethoprim can behave like amiloride by reducing ENaC-mediated sodium uptake and potassium secretion."),
        q("Mannitol is avoided in anuric renal failure mainly because it can:", "Expand extracellular volume without being excreted", ["Cause irreversible aldosterone excess", "Block beta-1 receptors", "Destroy loop transporters"], "If mannitol cannot be filtered and excreted, it can worsen volume overload."),
        q("Acetazolamide helps acute mountain sickness because it:", "Causes bicarbonate diuresis and metabolic acidosis that stimulates ventilation", ["Blocks aldosterone receptors", "Increases uric acid excretion selectively", "Stimulates ADH release"], "Carbonic anhydrase inhibition promotes bicarbonaturia; mild acidosis increases respiratory drive."),
        q("A patient with lithium-induced nephrogenic diabetes insipidus improves with amiloride because amiloride:", "Reduces lithium entry through ENaC in collecting duct cells", ["Blocks V2 receptors", "Inhibits NKCC2", "Stimulates aldosterone secretion"], "Amiloride blocks ENaC and can reduce lithium uptake into principal cells."),
        q("Ethacrynic acid is chosen for a patient needing loop diuresis who has a severe sulfonamide allergy. What major toxicity still requires caution?", "Ototoxicity", ["Agranulocytosis from ANC suppression", "Pulmonary fibrosis", "Serotonin syndrome"], "Ethacrynic acid is a non-sulfonamide loop diuretic but can cause ototoxicity."),
        q("A patient with gout worsens after starting a thiazide. The likely reason is:", "Reduced urate secretion competing at proximal tubular organic acid transport", ["Increased urate breakdown into allantoin", "Direct uric acid synthesis by thiazide", "Activation of xanthine oxidase"], "Thiazides and loops can increase uric acid by affecting proximal tubular handling."),
    ]),
    ("renin-angiotensin", "Renin and Angiotensin", [
        q("A diabetic patient with albuminuria is started on lisinopril. The kidney-protective logic is:", "Efferent arteriolar dilation lowers intraglomerular pressure", ["Afferent arteriolar constriction increases filtration pressure", "Direct insulin release from beta cells", "Complete aldosterone replacement"], "ACE inhibitors reduce angiotensin II, dilating the efferent arteriole and reducing proteinuric injury."),
        q("A patient on enalapril develops dry cough. The mechanism is accumulation of:", "Bradykinin", ["Renin", "Aldosterone", "Endothelin"], "ACE breaks down bradykinin; ACE inhibition can cause cough and angioedema."),
        q("A patient develops angioedema on an ACE inhibitor. Which replacement most directly preserves RAAS blockade with less bradykinin effect?", "Losartan", ["Aliskiren plus ACE inhibitor", "Hydralazine", "Phenylephrine"], "ARBs block AT1 receptors without inhibiting bradykinin breakdown."),
        q("A pregnant patient is found to be taking valsartan. The major concern is:", "Fetal renal injury and oligohydramnios", ["Neonatal opioid withdrawal", "Maternal serotonin syndrome", "Fetal hyperthyroidism"], "ACE inhibitors and ARBs are contraindicated in pregnancy due to fetal renal toxicity."),
        q("A patient with bilateral renal artery stenosis develops acute kidney injury after starting an ACE inhibitor. Why?", "Loss of angiotensin II efferent arteriolar support drops GFR", ["Excess afferent vasoconstriction by bradykinin", "Direct tubular crystal precipitation", "Complete blockade of sodium-glucose cotransport"], "In renal artery stenosis, GFR depends on angiotensin II-mediated efferent constriction."),
        q("Spironolactone improves resistant hypertension partly by:", "Blocking aldosterone effects in collecting duct and vasculature", ["Inhibiting renin release from beta-1 receptors", "Converting angiotensin I to angiotensin II", "Activating AT1 receptors"], "Mineralocorticoid receptor antagonists oppose aldosterone-mediated sodium retention and remodeling."),
        q("Aliskiren lowers blood pressure by directly inhibiting:", "Renin", ["ACE", "AT1 receptor", "Aldosterone synthase only"], "Aliskiren reduces conversion of angiotensinogen to angiotensin I."),
        q("A patient on ACE inhibitor plus spironolactone develops peaked T waves. The shared adverse effect is:", "Hyperkalemia", ["Severe hypocalcemia", "Hypoglycemia", "Respiratory alkalosis"], "RAAS blockade reduces aldosterone signaling, decreasing potassium excretion."),
        q("Sacubitril is paired with valsartan in heart failure to avoid:", "Angioedema risk from excessive bradykinin/angiotensin effects if combined with ACE inhibition", ["Complete loss of natriuretic peptides", "Irreversible beta blockade", "Direct digoxin toxicity"], "Neprilysin inhibition increases vasoactive peptides; pairing with an ARB avoids ACE inhibitor bradykinin overlap."),
        q("An ARB lowers aldosterone despite increased renin because it:", "Blocks angiotensin II AT1 receptor signaling", ["Destroys aldosterone already secreted", "Blocks mineralocorticoid receptors only", "Stimulates ACE2 exclusively"], "AT1 blockade prevents angiotensin II from driving vasoconstriction and aldosterone release."),
    ]),
    ("ischemic-heart-disease", "Treatment of Ischemic Heart Disease", [
        q("A patient with acute angina takes sublingual nitroglycerin and pain improves within minutes. The dominant antianginal effect is:", "Venodilation reducing preload and myocardial wall stress", ["Increased platelet aggregation", "Increased afterload", "Direct opening of beta-1 receptors"], "Nitrates reduce oxygen demand mainly by lowering preload; they also dilate coronary vessels."),
        q("A man using sildenafil develops chest pain. Why are nitrates contraindicated?", "Combined cGMP elevation can cause profound hypotension", ["Sildenafil blocks nitrate absorption", "Nitrates cause serotonin syndrome", "Both drugs cause hyperkalemia"], "PDE5 inhibition prevents cGMP breakdown; nitrates increase cGMP formation."),
        q("Beta blockers reduce stable exertional angina because they:", "Lower heart rate and contractility, reducing oxygen demand", ["Increase AV conduction and renin", "Cause reflex tachycardia", "Increase preload markedly"], "Reduced rate and contractility decrease myocardial oxygen consumption and extend diastole."),
        q("Prinzmetal angina is best treated chronically with:", "Calcium channel blocker", ["Nonselective beta blocker alone", "Digoxin", "Loop diuretic"], "Vasospastic angina responds to coronary vasodilators such as calcium channel blockers and nitrates."),
        q("A patient on nitroglycerin patches is told to remove the patch overnight to prevent:", "Tolerance from continuous nitrate exposure", ["Irreversible cyanide poisoning", "Agranulocytosis", "Hyperkalemia"], "A nitrate-free interval helps preserve nitrate responsiveness."),
        q("Ranolazine helps chronic angina without major heart rate or blood pressure reduction by:", "Inhibiting late sodium current and reducing diastolic wall tension", ["Blocking platelet P2Y12 receptors", "Activating beta-1 receptors", "Inhibiting aldosterone receptors"], "Ranolazine reduces intracellular sodium/calcium overload through late INa inhibition."),
        q("A patient with recent MI receives aspirin immediately because aspirin:", "Irreversibly inhibits platelet COX-1 thromboxane production", ["Activates plasminogen", "Blocks vitamin K recycling", "Stimulates prostacyclin only"], "Aspirin reduces platelet thromboxane A2 and recurrent coronary thrombosis risk."),
        q("Morphine is no longer routine for all ACS pain partly because it can:", "Delay absorption of oral antiplatelet drugs", ["Reverse heparin completely", "Increase thromboxane synthesis directly", "Activate P2Y12 receptors"], "Opioids slow gastric emptying and may delay P2Y12 inhibitor absorption."),
        q("A patient with angina and severe bradycardia should avoid verapamil because it:", "Depresses SA and AV nodal conduction", ["Causes pure reflex tachycardia", "Irreversibly inhibits platelets", "Blocks aldosterone receptors"], "Non-dihydropyridine calcium channel blockers slow nodal conduction and can worsen bradycardia."),
        q("A dihydropyridine calcium channel blocker relieves angina but causes ankle edema. The edema results mainly from:", "Preferential arteriolar dilation increasing capillary hydrostatic pressure", ["Renal sodium retention from aldosterone excess only", "Deep vein thrombosis in all patients", "Direct lymphatic destruction"], "Arteriolar dilation without matched venodilation can produce peripheral edema."),
    ]),
    ("hypertension", "Treatment of Hypertension", [
        q("An uncomplicated Black adult with hypertension is started on chlorthalidone. A key advantage over hydrochlorothiazide is:", "Longer duration and strong outcome evidence", ["No electrolyte effects", "Direct AT1 blockade", "No renal action"], "Chlorthalidone is thiazide-like, long acting, and has strong cardiovascular outcomes data."),
        q("A young woman with hypertension wants pregnancy soon. Which drug is generally safer in pregnancy than ACE inhibitors?", "Labetalol", ["Lisinopril", "Losartan", "Aliskiren"], "Labetalol, nifedipine, and methyldopa are commonly used options; RAAS blockers are contraindicated in pregnancy."),
        q("A patient with hypertensive emergency and aortic dissection needs immediate therapy. The key initial pharmacologic goal is:", "Rapid beta blockade to reduce shear stress before vasodilation", ["Pure hydralazine first to cause reflex tachycardia", "Oral thiazide monotherapy", "Aldosterone stimulation"], "Aortic dissection requires heart rate and contractility control, often with IV beta blockade, before vasodilators."),
        q("Hydralazine can cause tachycardia and fluid retention because it:", "Directly dilates arterioles and triggers sympathetic/RAAS compensation", ["Blocks beta-1 receptors", "Inhibits ENaC", "Activates central alpha-2 receptors"], "Direct arteriolar vasodilators often require a beta blocker and diuretic."),
        q("Minoxidil treats severe resistant hypertension but causes hirsutism because it:", "Opens potassium channels in vascular smooth muscle and hair follicles", ["Blocks androgen receptors", "Inhibits aldosterone synthesis", "Activates ACE"], "Minoxidil is a K+ channel opener; hypertrichosis is a characteristic adverse effect."),
        q("Clonidine withdrawal produces severe hypertension due to:", "Rebound sympathetic outflow", ["Irreversible alpha-1 blockade", "Sudden ACE activation only", "Loss of platelet inhibition"], "Central alpha-2 agonist withdrawal can cause sympathetic surge."),
        q("A patient with asthma worsens on propranolol. The hypertension drug problem is:", "Nonselective beta-2 blockade causing bronchoconstriction", ["Selective alpha-1 blockade", "ACE inhibition causing bradykinin cough", "Thiazide-induced hypocalciuria"], "Nonselective beta blockers can precipitate bronchospasm."),
        q("A patient on amlodipine develops flushing, headache, and edema but no AV block. This fits:", "Dihydropyridine calcium channel blocker toxicity", ["Verapamil nodal blockade", "ACE inhibitor cough", "Loop diuretic ototoxicity"], "Dihydropyridines are vascular selective and commonly cause vasodilatory adverse effects."),
        q("Primary aldosteronism with resistant hypertension and hypokalemia is treated medically with:", "Eplerenone", ["Phenylephrine", "Mannitol", "Dobutamine"], "Mineralocorticoid receptor antagonists target aldosterone-mediated sodium retention and potassium loss."),
        q("Nitroprusside lowers pressure rapidly but prolonged high-dose use risks:", "Cyanide and thiocyanate toxicity", ["Agranulocytosis", "Pulmonary fibrosis", "Methemoglobinemia from acetazolamide"], "Nitroprusside releases nitric oxide and cyanide; toxicity risk rises with prolonged infusion or renal/hepatic dysfunction."),
    ]),
    ("heart-failure", "Therapy of Heart Failure", [
        q("A patient with HFrEF is started on carvedilol only after congestion improves. Why avoid starting during acute decompensation?", "Initial negative inotropy can worsen unstable heart failure", ["It causes immediate aldosterone excess", "It blocks neprilysin irreversibly", "It cannot reduce mortality"], "Evidence-based beta blockers improve survival but should be started when euvolemic and stable."),
        q("Sacubitril/valsartan improves HFrEF outcomes by combining AT1 blockade with:", "Neprilysin inhibition increasing natriuretic peptides", ["ACE activation", "Direct digoxin antagonism", "Loop transporter blockade"], "ARNI therapy enhances beneficial natriuretic peptide signaling while blocking angiotensin II effects."),
        q("Spironolactone reduces mortality in selected HFrEF patients but requires monitoring for:", "Hyperkalemia and renal dysfunction", ["Severe hypouricemia", "Ototoxicity", "Reflex bronchospasm"], "MRAs reduce aldosterone-mediated remodeling and retention but can raise potassium."),
        q("An SGLT2 inhibitor benefits HFrEF even without diabetes partly by:", "Promoting natriuresis/osmotic diuresis and favorable cardiac-renal effects", ["Increasing insulin release only", "Blocking beta-1 receptors", "Activating aldosterone"], "SGLT2 inhibitors reduce HF hospitalization and mortality through multiple renal and metabolic mechanisms."),
        q("A patient on digoxin has nausea, yellow vision, and ventricular ectopy after hypokalemia. Hypokalemia worsens toxicity because:", "Less potassium competes with digoxin at Na/K-ATPase", ["Digoxin becomes an ACE inhibitor", "Potassium activates beta receptors", "Hypokalemia blocks AV node protection"], "Low K+ increases digoxin binding to Na/K-ATPase and toxicity risk."),
        q("Digoxin can help atrial fibrillation in heart failure because it:", "Increases vagal tone and slows AV nodal conduction", ["Blocks platelet aggregation", "Dilates coronary arteries only", "Inhibits neprilysin"], "Digoxin provides positive inotropy and vagotonic AV nodal slowing."),
        q("Hydralazine plus isosorbide dinitrate helps HFrEF especially when RAAS blockers are not tolerated because it:", "Reduces afterload and preload through complementary vasodilation", ["Blocks aldosterone receptors", "Inhibits SGLT2", "Activates beta-1 receptors"], "Arterial and venous dilation reduces cardiac workload; the combination has outcome benefit in selected groups."),
        q("Ivabradine is considered in HFrEF with sinus rhythm and high resting heart rate despite beta blocker because it:", "Inhibits the funny current in the SA node", ["Blocks AV node calcium channels", "Inhibits Na/K-ATPase", "Activates alpha-1 receptors"], "Ivabradine lowers sinus rate without direct negative inotropy."),
        q("Milrinone is used short-term in severe decompensated HF because it:", "Inhibits PDE3, increasing cAMP and inotropy", ["Blocks AT1 receptors", "Inhibits platelet COX irreversibly", "Antagonizes aldosterone only"], "PDE3 inhibitors increase cardiac contractility and vasodilation but can cause arrhythmias."),
        q("Loop diuretics improve dyspnea in congestive HF mainly by:", "Reducing volume overload and filling pressures", ["Reversing ventricular remodeling mortality in all patients", "Blocking beta receptors", "Increasing hemoglobin"], "Diuretics relieve congestion but are not the core mortality-modifying therapy for HFrEF."),
    ]),
    ("antiarrhythmic-drugs", "Antiarrhythmic Drugs", [
        q("A patient with atrial fibrillation and HFrEF receives amiodarone. Which toxicity requires long-term surveillance?", "Pulmonary fibrosis and thyroid dysfunction", ["Agranulocytosis only", "Severe hypoglycemia", "Cyanide toxicity"], "Amiodarone has iodine-related thyroid effects and pulmonary, hepatic, ocular, and skin toxicities."),
        q("A patient develops torsades de pointes while taking sotalol. The proarrhythmic mechanism is:", "Excess QT prolongation from potassium channel blockade", ["Shortened repolarization", "Pure alpha-1 blockade", "Increased AV nodal conduction"], "Class III action prolongs repolarization and can trigger early afterdepolarizations."),
        q("A narrow-complex paroxysmal SVT terminates after adenosine. The drug works by:", "Transient AV nodal conduction block via A1 receptors", ["Permanent accessory pathway ablation", "Beta-1 stimulation", "Sodium channel opening"], "Adenosine activates A1 receptors, increasing K+ conductance and suppressing AV nodal conduction."),
        q("A patient with Wolff-Parkinson-White and atrial fibrillation should avoid AV nodal blockers alone because they may:", "Promote conduction down the accessory pathway", ["Prevent ventricular preexcitation completely", "Reverse delta waves instantly", "Activate the sinus node only"], "Blocking the AV node can favor accessory pathway conduction and dangerous ventricular rates."),
        q("Lidocaine is useful for ischemia-related ventricular arrhythmias because it:", "Preferentially blocks inactivated sodium channels in depolarized ventricular tissue", ["Strongly blocks AV nodal calcium channels", "Irreversibly blocks beta receptors", "Activates muscarinic receptors"], "Class Ib drugs favor diseased or depolarized ventricular tissue and shorten repolarization."),
        q("Flecainide is avoided after myocardial infarction because it:", "Can increase mortality by provoking ventricular arrhythmias in structural heart disease", ["Always causes pulmonary fibrosis", "Cannot block sodium channels", "Causes cyanide toxicity"], "Class Ic drugs are contraindicated in structural/ischemic heart disease due to proarrhythmia."),
        q("Verapamil slows AV nodal conduction because it blocks:", "L-type calcium channels", ["Fast sodium channels in His-Purkinje only", "IKr potassium channels", "Funny current only"], "Non-dihydropyridine calcium channel blockers act on nodal L-type calcium currents."),
        q("A patient on digoxin develops AV block and ventricular ectopy. Which antibody treatment can reverse severe toxicity?", "Digoxin immune Fab", ["Protamine", "Vitamin K", "Idarucizumab"], "Digoxin immune Fab binds digoxin in severe or life-threatening toxicity."),
        q("Beta blockers prevent catecholamine-triggered arrhythmias after MI mainly by:", "Reducing automaticity and AV nodal conduction through beta-1 blockade", ["Increasing cAMP in nodal cells", "Opening sodium channels", "Activating AT1 receptors"], "Beta blockade reduces sympathetic arrhythmogenicity and mortality after MI."),
        q("Magnesium is used for torsades de pointes even if serum magnesium is normal because it:", "Suppresses early afterdepolarizations and stabilizes repolarization", ["Shortens PR by beta stimulation", "Blocks thrombin", "Chelates digoxin"], "IV magnesium is first-line for torsades and helps stabilize myocardial electrical activity."),
    ]),
    ("pulmonary-arterial-hypertension", "Treatment of Pulmonary Arterial Hypertension", [
        q("A patient with PAH improves on epoprostenol. The key effect is:", "Prostacyclin receptor activation causing pulmonary vasodilation and reduced platelet aggregation", ["Endothelin receptor activation", "ACE activation", "Thromboxane synthesis"], "Prostacyclin analogs increase cAMP, dilate pulmonary vessels, and inhibit platelets."),
        q("A PAH patient on bosentan needs liver tests because bosentan can cause:", "Hepatotoxicity", ["Permanent ototoxicity", "Agranulocytosis as the main toxicity", "Cyanide accumulation"], "Endothelin receptor antagonists, especially bosentan, can elevate aminotransferases."),
        q("Ambrisentan is contraindicated in pregnancy mainly because endothelin antagonists are:", "Teratogenic", ["Strong opioid agonists", "Insulin secretagogues", "Acetylcholinesterase reactivators"], "Endothelin receptor antagonists require pregnancy prevention due to teratogenicity."),
        q("Sildenafil helps PAH by:", "Inhibiting PDE5 and increasing cGMP-mediated pulmonary vasodilation", ["Blocking thrombin", "Activating endothelin-A receptors", "Inhibiting aldosterone receptors"], "PDE5 inhibitors augment NO-cGMP signaling in pulmonary vascular smooth muscle."),
        q("Riociguat must not be combined with PDE5 inhibitors because both:", "Increase cGMP signaling and can cause severe hypotension", ["Block vitamin K recycling", "Cause acetaldehyde accumulation", "Activate beta-1 receptors"], "Riociguat stimulates soluble guanylate cyclase; combining with PDE5 inhibitors overly amplifies cGMP."),
        q("Inhaled iloprost is useful in PAH partly because inhalation:", "Targets ventilated lung regions and limits systemic exposure", ["Prevents any need for repeated dosing", "Blocks endothelin synthesis irreversibly", "Causes selective renal vasoconstriction"], "Inhaled pulmonary vasodilators preferentially reach ventilated areas and can reduce systemic hypotension."),
        q("A PAH patient responds dramatically to acute vasodilator testing. Which chronic oral drug class may be used in selected responders?", "High-dose calcium channel blocker", ["Loop diuretic alone", "Class Ic antiarrhythmic", "Acetylcholinesterase inhibitor"], "Only a small vasoreactive PAH subset benefits from high-dose calcium channel blockers."),
        q("Selexipag treats PAH by acting as a:", "Prostacyclin IP receptor agonist", ["P2Y12 antagonist", "AT1 receptor blocker", "Direct renin inhibitor"], "Selexipag is an oral selective prostacyclin receptor agonist."),
        q("A PAH patient with right-heart failure receives diuretics. The goal is:", "Relieve systemic congestion while avoiding excessive preload reduction", ["Cure pulmonary vascular remodeling alone", "Increase pulmonary artery pressure", "Activate endothelin receptors"], "Diuretics manage volume overload in right HF but require careful balance."),
        q("Endothelin-1 worsens PAH because it is a potent:", "Pulmonary vasoconstrictor and smooth muscle mitogen", ["Fibrinolytic enzyme", "Natriuretic peptide", "Beta-2 agonist"], "Endothelin promotes vasoconstriction and vascular remodeling; antagonists oppose this pathway."),
    ]),
    ("coagulation-anticoagulant-fibrinolytic-antiplatelet", "Blood Coagulation and Anticoagulant, Fibrinolytic, and Antiplatelet Drugs", [
        q("A patient on unfractionated heparin has bleeding. Which reversal agent is most appropriate?", "Protamine sulfate", ["Vitamin K", "Idarucizumab", "Aminocaproic acid"], "Protamine binds and neutralizes heparin, especially unfractionated heparin."),
        q("Warfarin is teratogenic but heparin is generally safer in pregnancy because heparin:", "Does not cross the placenta significantly", ["Is a direct thrombin tablet", "Activates vitamin K epoxide reductase", "Irreversibly inhibits platelets"], "Heparins are large/polar and do not meaningfully cross the placenta."),
        q("A patient starting warfarin is bridged with heparin because early warfarin therapy:", "Lowers protein C before full anticoagulation, causing transient hypercoagulability", ["Immediately dissolves clots", "Raises factor II levels", "Blocks antithrombin"], "Protein C falls quickly; prothrombin falls slowly, so bridging is used in high-risk starts."),
        q("Dabigatran overdose can be reversed with:", "Idarucizumab", ["Vitamin K", "Protamine only", "Aspirin"], "Idarucizumab is a monoclonal antibody fragment that binds dabigatran."),
        q("Rivaroxaban and apixaban anticoagulate by directly inhibiting:", "Factor Xa", ["Thrombin receptor PAR1", "Vitamin K epoxide reductase", "Cyclooxygenase-1"], "Direct oral Xa inhibitors reduce thrombin generation."),
        q("Aspirin prevents arterial thrombosis by:", "Irreversibly inhibiting platelet COX-1 and thromboxane A2 synthesis", ["Blocking ADP P2Y12 receptors", "Activating plasminogen", "Inhibiting factor Xa directly"], "Platelets cannot resynthesize COX, so aspirin suppresses thromboxane for their lifespan."),
        q("Clopidogrel has reduced effect in a CYP2C19 poor metabolizer because it is:", "A prodrug requiring metabolic activation", ["A direct thrombin inhibitor", "Destroyed by stomach acid only", "An irreversible vitamin K analog"], "Clopidogrel needs CYP-mediated activation; poor metabolizers may have less platelet inhibition."),
        q("Alteplase is most useful early in ischemic stroke because it:", "Converts plasminogen to plasmin to lyse fibrin", ["Blocks vitamin K recycling", "Neutralizes heparin", "Inhibits platelet COX"], "tPA promotes fibrinolysis but carries bleeding risk and must be time-selected."),
        q("Aminocaproic acid helps severe fibrinolytic bleeding by:", "Inhibiting plasminogen activation and plasmin binding to fibrin", ["Activating antithrombin", "Blocking P2Y12 receptors", "Stimulating prostacyclin"], "Antifibrinolytics preserve clots by opposing plasmin formation/action."),
        q("Heparin-induced thrombocytopenia is suspected. The correct response is to stop heparin and use:", "A non-heparin anticoagulant such as argatroban", ["More unfractionated heparin", "Warfarin alone immediately", "Aspirin only"], "HIT is prothrombotic; treat with non-heparin anticoagulation and avoid starting warfarin alone acutely."),
    ]),
    ("dyslipidemias", "Drug Therapy for Dyslipidemias", [
        q("A patient with high LDL starts atorvastatin. The main mechanism is:", "HMG-CoA reductase inhibition increasing hepatic LDL receptors", ["Bile acid receptor activation in muscle", "PCSK9 activation", "Cholesterol absorption stimulation"], "Statins reduce hepatic cholesterol synthesis and upregulate LDL receptor clearance."),
        q("A patient on high-dose simvastatin develops muscle pain and dark urine after starting clarithromycin. The likely issue is:", "CYP3A4 inhibition increasing statin myotoxicity", ["Vitamin K deficiency", "Aspirin resistance", "Aldosterone excess"], "Many statin myopathies are worsened by CYP interactions that raise statin levels."),
        q("Ezetimibe lowers LDL by blocking:", "Intestinal NPC1L1 cholesterol absorption", ["HMG-CoA reductase", "PCSK9 catalytic activity", "Lipoprotein lipase"], "Ezetimibe inhibits NPC1L1 at the intestinal brush border."),
        q("A patient with familial hypercholesterolemia has further LDL reduction with evolocumab because it:", "Inhibits PCSK9 and increases LDL receptor recycling", ["Blocks bile acid binding", "Activates CETP", "Inhibits ApoA-I synthesis"], "PCSK9 inhibitors preserve LDL receptors and markedly lower LDL."),
        q("A patient with severe hypertriglyceridemia at pancreatitis risk is treated with fenofibrate. The key mechanism is:", "PPAR-alpha activation increasing lipoprotein lipase activity", ["COX-1 inhibition", "AT1 receptor blockade", "NPC1L1 blockade only"], "Fibrates lower triglycerides by increasing fatty acid oxidation and LPL-mediated clearance."),
        q("Gemfibrozil plus statin is used cautiously because it increases risk of:", "Myopathy and rhabdomyolysis", ["Torsades only", "Angioedema from bradykinin", "Pulmonary hypertension"], "Fibrates, especially gemfibrozil, can increase statin-associated muscle toxicity."),
        q("Niacin improves lipids but a patient cannot tolerate intense flushing. The flushing is mediated by:", "Prostaglandin release", ["Bradykinin destruction", "Aldosterone release", "Factor Xa inhibition"], "Niacin flushing is prostaglandin mediated and may be reduced by aspirin pretreatment."),
        q("Bile acid sequestrants can worsen which lipid abnormality?", "Hypertriglyceridemia", ["Low LDL", "Low Lp(a) only", "Low HDL only"], "Bile acid resins can raise triglycerides and are avoided in significant hypertriglyceridemia."),
        q("A patient with ASCVD has LDL above goal despite maximal statin and ezetimibe. Which injectable option is most directly appropriate?", "PCSK9 inhibitor", ["Loop diuretic", "PDE5 inhibitor", "Direct thrombin activator"], "PCSK9 inhibitors provide additional LDL reduction in high-risk patients."),
        q("Statins are avoided in pregnancy because cholesterol synthesis is important for:", "Fetal development", ["Maternal platelet COX inhibition", "Placental heparin clearance", "Fetal beta blockade"], "Lipid-lowering with statins is generally avoided during pregnancy due to fetal developmental concerns."),
    ]),
]


def main():
    questions = []
    for topic_index, (slug, topic, rows) in enumerate(TOPICS):
        if len(rows) != 10:
            raise ValueError(f"{topic} has {len(rows)} questions, expected 10")
        for question_index, row in enumerate(rows, 1):
            options = list(row["wrong"])
            answer_index = (topic_index + question_index - 1) % 4
            options.insert(answer_index, row["answer"])
            questions.append({**BASE, "id": f"mod-prcv-{slug}-{question_index:02d}", "topic": topic, "difficulty": "moderate" if question_index <= 3 else "high" if question_index <= 8 else "very high", "prompt": row["prompt"], "options": options, "answerIndex": answer_index, "answer": row["answer"], "explanation": row["explanation"]})

    data = json.loads(DATA.read_text(encoding="utf-8-sig"))
    data["questions"] = [x for x in data.get("questions", []) if not (x.get("subjectId") == "pharmacology" and x.get("chapterTitle") == CHAPTER)] + questions

    if len(TOPICS) != 9 or len(questions) != 90:
        raise AssertionError(f"Expected 9 topics and 90 questions, got {len(TOPICS)} and {len(questions)}")
    if len({x["id"] for x in questions}) != 90:
        raise AssertionError("Duplicate question IDs")
    if any(x["answer"] != x["options"][x["answerIndex"]] for x in questions):
        raise AssertionError("Bad answer index")

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Added {len(questions)} questions across {len(TOPICS)} topics for {CHAPTER}.")


if __name__ == "__main__":
    main()
