import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATABASE_PATH = ROOT / "runtime-data" / "users.json"
SOURCE_PDF = "Robbins & Cotran Pathologic Basis of Disease, 10th ed. (provided PDF)"
ID_PREFIX = "usmle-pathology-robbins-"


def question(
    number,
    chapter_title,
    chapter_order,
    topic,
    topic_order,
    page_start,
    prompt,
    options,
    answer_index,
    explanation,
    difficulty="moderate",
    tags=None,
    lead_in=None,
    laboratory_findings=None,
    item_family="mechanism",
    image_urls=None,
):
    return {
        "id": f"{ID_PREFIX}{number:02d}",
        "examId": "usmle-step-1",
        "examTitle": "USMLE Step 1-Style Practice",
        "subjectId": "pathology",
        "subjectTitle": "Pathology",
        "chapterTitle": chapter_title,
        "chapterOrder": chapter_order,
        "topic": topic,
        "topicTitle": topic,
        "topicOrder": topic_order,
        "source": "usmle",
        "sourcePdf": SOURCE_PDF,
        "sourcePdfPageStart": page_start,
        "sourcePdfPageEnd": page_start,
        "difficulty": difficulty,
        "prompt": prompt,
        "leadIn": lead_in,
        "laboratoryFindings": laboratory_findings or [],
        "itemFamily": item_family,
        "options": options,
        "answerIndex": answer_index,
        "answer": options[answer_index],
        "explanation": explanation,
        "imageUrls": image_urls or [],
        "tags": ["usmle-step-1", "robbins-10e", *(tags or [])],
    }


QUESTIONS = [
    question(
        1,
        "Cell Injury, Cell Death, and Adaptations",
        2,
        "Apoptosis and Other Regulated Cell-Death Pathways",
        4,
        56,
        "A 46-year-old woman has painless cervical lymphadenopathy. A lymph-node biopsy shows closely packed follicles composed predominantly of small lymphocytes. Cytogenetic analysis demonstrates t(14;18), resulting in overexpression of BCL2. The affected lymphocytes survive substantially longer than normal germinal-center B cells. Which of the following events is most directly inhibited by the overexpressed protein in these cells?",
        [
            "Activation of receptor-associated caspase 8",
            "Release of cytochrome c through the outer mitochondrial membrane",
            "Cleavage of an inhibitor of caspase-activated DNase",
            "Externalization of phosphatidylserine on the plasma membrane",
            "Formation of a death-inducing signaling complex",
        ],
        1,
        "BCL2 is an anti-apoptotic protein that preserves outer mitochondrial membrane integrity and prevents cytochrome c from entering the cytosol. The other options describe downstream execution events or components of the extrinsic death-receptor pathway.",
        tags=["apoptosis", "bcl2"],
    ),
    question(
        2,
        "Cell Injury, Cell Death, and Adaptations",
        2,
        "Ischemic, Reperfusion, and Toxic Injury",
        6,
        68,
        "A 62-year-old man is brought to the emergency department 45 minutes after the onset of crushing substernal chest pain. ECG shows ST-segment elevations in leads V1 through V4. Angiography demonstrates complete occlusion of the left anterior descending artery, and blood flow is restored by percutaneous intervention. Despite successful reperfusion, additional cardiomyocyte injury occurs during the next several hours. Which of the following mechanisms most directly contributes to this additional injury?",
        [
            "Decreased recruitment of neutrophils to previously ischemic tissue",
            "Closure of mitochondrial permeability transition pores",
            "Rapid efflux of calcium from damaged cardiomyocytes",
            "Generation of reactive oxygen species during reoxygenation",
            "Upregulation of intracellular antioxidant defenses during ischemia",
        ],
        3,
        "Reoxygenation can cause a burst of reactive oxygen and nitrogen species from leukocytes, endothelial cells, and injured parenchymal cells. Reperfusion also worsens calcium overload, opens mitochondrial permeability transition pores, and recruits inflammatory cells.",
        tags=["reperfusion", "reactive-oxygen-species"],
    ),
    question(
        3,
        "Hemodynamic Disorders, Thromboembolic Disease, and Shock",
        4,
        "Platelets, Coagulation Factors, and Anticoagulant Mechanisms",
        4,
        136,
        "A 29-year-old woman develops pain and swelling of the left calf 2 days after returning from a long flight. Duplex ultrasonography confirms a deep venous thrombosis. Her father and paternal aunt had venous thromboemboli before age 40 years. Laboratory studies are shown.",
        [
            "Reduced hepatic synthesis of antithrombin",
            "Increased prothrombin expression caused by a coding-region deletion",
            "Resistance of factor V to cleavage by activated protein C",
            "Impaired conversion of plasminogen to plasmin",
            "Absence of endothelial thrombomodulin",
        ],
        2,
        "Factor V Leiden is caused by an Arg-to-Gln substitution at residue 506, making factor V resistant to inactivation by activated protein C. It produces an autosomal dominant predisposition to venous thrombosis while routine coagulation studies may remain normal.",
        tags=["factor-v-leiden", "thrombosis"],
        lead_in="Which of the following abnormalities is most likely present?",
        laboratory_findings=[
            {"test": "Platelet count", "value": "248,000/mm3", "reference": "150,000-400,000/mm3"},
            {"test": "Prothrombin time", "value": "12 seconds", "reference": "11-13 seconds"},
            {"test": "Partial thromboplastin time", "value": "29 seconds", "reference": "25-35 seconds"},
            {"test": "Activated protein C resistance ratio", "value": "1.5", "reference": ">=2.3"},
        ],
    ),
    question(
        4,
        "Diseases of the Immune System",
        6,
        "Transplantation Immunology",
        7,
        244,
        "A 51-year-old woman with end-stage kidney disease undergoes renal transplantation. Within minutes after vascular anastomoses are completed, the graft becomes cyanotic and produces no urine. A biopsy specimen from the transplanted kidney is shown. Which of the following is the most likely cause of these findings?",
        [
            "Donor CD8+ T lymphocytes attacking recipient tubular cells",
            "Deposition of circulating immune complexes formed after transplantation",
            "Activation of recipient memory T lymphocytes against graft parenchyma",
            "Preformed donor antibodies binding recipient vascular endothelium",
            "Preformed recipient antibodies binding antigens on graft endothelium",
        ],
        4,
        "Hyperacute rejection is mediated by preformed recipient antibodies directed against donor blood-group or HLA antigens. Antibody binding activates complement and thrombosis in graft vessels, causing ischemia and failure within minutes to hours.",
        tags=["hyperacute-rejection", "transplantation"],
        image_urls=["/uploads/usmle-pathology-robbins-q04-hyperacute-rejection.png"],
    ),
    question(
        5,
        "Diseases of the Immune System",
        6,
        "Primary and Secondary Immunodeficiency Diseases",
        8,
        250,
        "A 10-month-old boy is evaluated for recurrent bacterial skin infections. His umbilical cord separated 5 weeks after birth. During infections he develops marked neutrophilia, but the infected areas contain little pus. Flow cytometry shows absent expression of a molecule shared by LFA-1 and Mac-1. A defect in which of the following proteins most likely causes this patient's condition?",
        [
            "The beta-2 integrin chain CD18",
            "A membrane component of phagocyte NADPH oxidase",
            "Bruton tyrosine kinase",
            "The lysosomal trafficking protein LYST",
            "Myeloperoxidase",
        ],
        0,
        "Leukocyte adhesion deficiency type 1 results from defective synthesis of the beta-2 chain of CD11/CD18 integrins. Neutrophils cannot adhere firmly to endothelium or migrate into tissue, producing delayed cord separation, neutrophilia, recurrent bacterial infections, and impaired pus formation.",
        tags=["leukocyte-adhesion-deficiency", "cd18"],
    ),
    question(
        6,
        "Diseases of the Immune System",
        6,
        "Amyloidosis",
        10,
        270,
        "A 68-year-old man has progressive fatigue, back pain, ankle edema, and exertional dyspnea. Echocardiography shows increased ventricular wall thickness with impaired diastolic filling. Serum protein electrophoresis has a narrow spike, and abdominal fat-pad biopsy demonstrates Congo red-positive extracellular deposits with apple-green birefringence. Selected laboratory studies are shown.",
        [
            "Amyloid-beta peptide",
            "Beta-2 microglobulin",
            "Serum amyloid-associated protein",
            "Immunoglobulin light chains",
            "Transthyretin",
        ],
        3,
        "A monoclonal plasma-cell disorder with systemic amyloidosis produces AL fibrils derived from immunoglobulin light chains, most often lambda. AA fibrils accompany chronic inflammation, beta-2 microglobulin accumulates with long-term dialysis, and transthyretin forms hereditary or age-related amyloid.",
        tags=["amyloidosis", "plasma-cell-disorder"],
        lead_in="The deposited fibrils are most likely derived from which of the following precursors?",
        laboratory_findings=[
            {"test": "Hemoglobin", "value": "9.1 g/dL", "reference": "13.5-17.5 g/dL"},
            {"test": "Creatinine", "value": "2.3 mg/dL", "reference": "0.7-1.3 mg/dL"},
            {"test": "Calcium", "value": "11.4 mg/dL", "reference": "8.6-10.2 mg/dL"},
            {"test": "Urine protein", "value": "4.8 g/24 h", "reference": "<150 mg/24 h"},
        ],
    ),
    question(
        7,
        "Blood Vessels",
        11,
        "Atherosclerosis: Risk Factors and Pathogenesis",
        3,
        503,
        "Investigators create a small area of endothelial dysfunction in the coronary arteries of an animal model with severe hypercholesterolemia. Before the intervention, circulating cells are permanently labeled with lineage-specific fluorescent markers. Weeks later, the arterial lesions contain numerous lipid-laden foam cells beneath intact endothelium but no well-developed fibrous cap. The marker found in most foam cells was originally expressed by which of the following circulating cell types?",
        [
            "Adventitial fibroblasts",
            "Circulating monocytes",
            "Neutrophils",
            "Vascular endothelial cells",
            "T lymphocytes",
        ],
        1,
        "This lineage-tracing experiment models an early fatty streak. Endothelial dysfunction promotes monocyte adhesion and entry into the intima; the monocytes become macrophages and ingest modified LDL through scavenger receptors. Smooth muscle cells can contribute to foam cells later, but they are not circulating cells.",
        tags=["atherosclerosis", "foam-cells"],
        item_family="experimental-design",
    ),
    question(
        8,
        "The Heart",
        12,
        "Complications of Myocardial Infarction and Chronic IHD",
        5,
        556,
        "A 71-year-old woman is hospitalized after a first transmural myocardial infarction involving the lateral wall of the left ventricle. On hospital day 5, she suddenly develops hypotension, jugular venous distention, and pulseless electrical activity. Echocardiography shows a large pericardial effusion. Which of the following tissue processes most likely predisposed to this complication?",
        [
            "Deposition and contraction of a dense collagenous scar",
            "Persistent coagulative necrosis without an inflammatory response",
            "Macrophage-mediated digestion and maximal softening of necrotic myocardium",
            "Neutrophil-mediated replacement of myocardium by mature granulation tissue",
            "Rapid synthesis of type I collagen by surviving cardiomyocytes",
        ],
        2,
        "Left ventricular free-wall rupture causes hemopericardium and cardiac tamponade. Rupture is most likely 3 to 7 days after infarction, when macrophages are digesting necrotic myocardium and the infarct is maximally soft before a strong collagen scar has formed.",
        difficulty="hard",
        tags=["myocardial-infarction", "cardiac-rupture"],
    ),
    question(
        9,
        "Diseases of White Blood Cells, Lymph Nodes, Spleen, and Thymus",
        13,
        "Myeloproliferative Neoplasms and Myelodysplastic Syndromes",
        4,
        627,
        "A 55-year-old man has 3 months of fatigue, night sweats, and early satiety. Examination shows a markedly enlarged spleen. A peripheral blood smear shows granulocytes at all stages of maturation. Selected laboratory studies are shown. Cytogenetic analysis demonstrates t(9;22)(q34;q11).",
        [
            "Constitutively active nonreceptor tyrosine kinase activity",
            "Constitutively active cytokine-receptor serine kinase activity",
            "GTPase activity that is locked in its inactive GDP-bound state",
            "Ligand-independent nuclear steroid-receptor activity",
            "Membrane-bound receptor tyrosine phosphatase activity",
        ],
        0,
        "The Philadelphia chromosome creates the BCR-ABL fusion protein. BCR-mediated self-association constitutively activates the nonreceptor ABL tyrosine kinase, driving growth and survival signaling through pathways including RAS and JAK/STAT.",
        tags=["cml", "bcr-abl"],
        lead_in="The protein produced by this rearrangement has which of the following activities?",
        laboratory_findings=[
            {"test": "Hemoglobin", "value": "10.2 g/dL", "reference": "13.5-17.5 g/dL"},
            {"test": "Leukocyte count", "value": "145,000/mm3", "reference": "4,500-11,000/mm3"},
            {"test": "Basophils", "value": "8%", "reference": "0-1%"},
            {"test": "Leukocyte alkaline phosphatase score", "value": "18", "reference": "20-100"},
        ],
    ),
    question(
        10,
        "The Lung",
        15,
        "Lung Tumors and Carcinogenesis",
        9,
        723,
        "A 66-year-old man with a 50-pack-year smoking history has progressive cough, weight loss, headache, and confusion. Examination shows no edema. CT scan shows a central hilar mass with bulky mediastinal lymphadenopathy. A bronchoscopic biopsy specimen is shown. Selected laboratory studies are shown.",
        [
            "Birbeck granules",
            "Prominent desmosomal plaques with tonofilaments",
            "Weibel-Palade bodies",
            "Premelanosomes",
            "Dense-core neurosecretory granules",
        ],
        4,
        "Small cell carcinoma is a high-grade neuroendocrine carcinoma and often causes ectopic hormone syndromes such as SIADH. Its cells express neuroendocrine markers and commonly contain dense-core neurosecretory granules on electron microscopy.",
        tags=["small-cell-carcinoma", "neuroendocrine"],
        lead_in="Which of the following findings is most likely on electron microscopy of the tumor cells?",
        laboratory_findings=[
            {"test": "Serum sodium", "value": "119 mEq/L", "reference": "136-145 mEq/L"},
            {"test": "Serum osmolality", "value": "258 mOsm/kg H2O", "reference": "275-295 mOsm/kg H2O"},
            {"test": "Urine osmolality", "value": "540 mOsm/kg H2O", "reference": "50-1,200 mOsm/kg H2O"},
            {"test": "Urine sodium", "value": "62 mEq/L", "reference": "variable with intake"},
        ],
        image_urls=["/uploads/usmle-pathology-robbins-q10-small-cell-carcinoma.png"],
    ),
    question(
        11,
        "The Gastrointestinal Tract",
        17,
        "Esophagus: Reflux, Barrett Esophagus, and Tumors",
        2,
        764,
        "A 48-year-old man comes to the office because of a 12-year history of substernal burning and sour-tasting regurgitation after meals. The symptoms are worse when he lies down. BMI is 31 kg/m2. Endoscopy shows velvety salmon-colored mucosa extending proximally from the gastroesophageal junction. Biopsy demonstrates columnar epithelium containing goblet cells. Which of the following is the most likely diagnosis?",
        [
            "Barrett esophagus",
            "Eosinophilic esophagitis",
            "Esophageal squamous dysplasia",
            "Gastric heterotopia",
            "Reflux esophagitis without metaplasia",
        ],
        0,
        "This is Barrett esophagus: intestinal metaplasia in which reflux-damaged distal esophageal squamous mucosa is replaced by columnar epithelium containing goblet cells. It increases the risk for dysplasia and esophageal adenocarcinoma.",
        tags=["barrett-esophagus", "metaplasia"],
        item_family="diagnosis",
    ),
    question(
        12,
        "The Gastrointestinal Tract",
        17,
        "Gastric Polyps and Gastric Tumors",
        4,
        779,
        "A 58-year-old woman has chronic dyspepsia. Gastric biopsy shows Helicobacter pylori organisms and a dense infiltrate of small CD20-positive B lymphocytes forming lymphoepithelial lesions. Molecular testing shows no API2-MALT1, MALT1, or BCL10 translocation. Eradication therapy results in regression of the lymphoid proliferation. Which of the following best explains this response?",
        [
            "Restoration of p53 function in the neoplastic B cells",
            "Direct cytotoxicity of the antibiotics against CD20-positive cells",
            "Pharmacologic inhibition of an API2-MALT1 fusion protein",
            "Removal of antigen-dependent NF-kappaB signaling through the MALT1-BCL10 pathway",
            "Correction of a mismatch-repair defect in gastric epithelial cells",
        ],
        3,
        "Early gastric MALT lymphomas without constitutively activating translocations can remain dependent on antigenic stimulation from H. pylori. Eradication removes this stimulus and reduces NF-kappaB-mediated B-cell growth and survival; translocation-positive tumors are more likely to resist eradication therapy.",
        difficulty="hard",
        tags=["malt-lymphoma", "helicobacter-pylori"],
    ),
    question(
        13,
        "The Pancreas",
        19,
        "Pancreatic Ductal Adenocarcinoma: Risks and Morphology",
        6,
        892,
        "A 69-year-old man has 4 months of progressive weight loss, dull epigastric discomfort radiating to the back, dark urine, and yellow discoloration of the skin. Examination shows a palpable, nontender gallbladder. CT scan demonstrates an infiltrative mass in the head of the pancreas. Biopsy shows irregular mucin-producing glands within a dense desmoplastic stroma; adjacent ducts contain pancreatic intraepithelial neoplasia. Which of the following genes most likely contains an activating mutation affecting a small GTP-binding signaling protein?",
        [
            "APC",
            "BRCA2",
            "KRAS",
            "RB1",
            "VHL",
        ],
        2,
        "Activating KRAS mutations are common early abnormalities in pancreatic intraepithelial neoplasia and pancreatic ductal adenocarcinoma. CDKN2A, TP53, and SMAD4 are also frequently altered, but they are tumor suppressor genes rather than small GTP-binding proteins.",
        tags=["pancreatic-carcinoma", "kras"],
    ),
    question(
        14,
        "The Kidney",
        20,
        "Nephrotic Syndrome: Minimal Change, FSGS, and Membranous Nephropathy",
        2,
        916,
        "A 5-year-old boy develops periorbital edema 1 week after an upper respiratory infection. Blood pressure is 96/60 mm Hg. There is no rash or joint swelling. Selected laboratory studies are shown. Light microscopy of a renal biopsy shows glomeruli without significant abnormalities, and immunofluorescence shows no immune deposits.",
        [
            "Diffuse effacement of podocyte foot processes",
            "Linear deposition of IgG along glomerular basement membranes",
            "Mesangial deposition of IgA",
            "Subendothelial immune-complex deposits with wire-loop lesions",
            "Subepithelial immune-complex deposits with basement-membrane spikes",
        ],
        0,
        "The nephrotic syndrome, preserved complement level, bland urine sediment, and normal light microscopy indicate minimal change disease. It is a podocytopathy whose defining ultrastructural finding is diffuse foot-process effacement; immune-complex deposits are absent.",
        tags=["minimal-change-disease", "podocyte"],
        lead_in="Which of the following additional renal-biopsy findings is most likely?",
        laboratory_findings=[
            {"test": "Serum albumin", "value": "2.1 g/dL", "reference": "3.5-5.0 g/dL"},
            {"test": "Total cholesterol", "value": "286 mg/dL", "reference": "<170 mg/dL"},
            {"test": "Creatinine", "value": "0.4 mg/dL", "reference": "0.3-0.7 mg/dL"},
            {"test": "Complement C3", "value": "112 mg/dL", "reference": "80-160 mg/dL"},
            {"test": "Urinalysis", "value": "4+ protein; no blood", "reference": "negative"},
        ],
        item_family="predicted-finding",
    ),
    question(
        15,
        "The Lower Urinary Tract and Male Genital System",
        21,
        "Prostatitis and Benign Prostatic Hyperplasia",
        9,
        978,
        "A 67-year-old man has urinary hesitancy, a weak stream, and nocturia. Digital rectal examination shows a symmetrically enlarged prostate without nodules. Histologic examination would show nodular hyperplasia of glands and stroma in the transition zone. Treatment is begun with an inhibitor of type 2 5-alpha-reductase in prostatic stromal cells. The intraprostatic concentration of which of the following substances will decrease?",
        [
            "Androstenedione",
            "Dehydroepiandrosterone",
            "Estradiol",
            "Testosterone",
            "Dihydrotestosterone",
        ],
        4,
        "Type 2 5-alpha-reductase converts testosterone to dihydrotestosterone in prostatic stromal cells. DHT activates androgen receptors in stromal and epithelial cells and promotes growth-factor signaling that contributes to benign prostatic hyperplasia.",
        tags=["bph", "dihydrotestosterone"],
    ),
    question(
        16,
        "The Female Genital Tract",
        22,
        "Cervicitis, HPV Infection, and Cervical Intraepithelial Neoplasia",
        2,
        998,
        "A 34-year-old woman has a high-grade squamous intraepithelial lesion on cervical cytology. Biopsy confirms severe dysplasia, and testing detects integrated HPV type 16 DNA with high expression of the viral E6 protein. Which of the following molecular effects is most directly caused by E6 in these cells?",
        [
            "Binding and proteasomal degradation of hypophosphorylated RB by E7",
            "Binding and proteasomal degradation of p53",
            "Constitutive activation of RAS GTPase",
            "Inhibition of telomerase expression",
            "Synthesis of a viral thymidine kinase that blocks DNA repair",
        ],
        1,
        "High-risk HPV E6 binds p53 and promotes its proteasomal degradation; it also increases telomerase expression. E7 separately binds active hypophosphorylated RB and promotes its degradation, releasing cell-cycle restraints.",
        tags=["cervical-neoplasia", "hpv-e6"],
    ),
    question(
        17,
        "The Breast",
        23,
        "Breast Cancer Risk Factors and Molecular Subtypes",
        5,
        1053,
        "A 38-year-old woman has a poorly differentiated invasive breast carcinoma that is negative for estrogen receptor, progesterone receptor, and HER2. Her mother died of ovarian cancer at age 44 years. Germline testing identifies a pathogenic BRCA1 variant. The patient begins to cry and says, \"I gave this cancer to my daughter. She is only 12. What have I done?\" Which of the following is the most appropriate initial response by the physician?",
        [
            "Because the variant is autosomal dominant, your daughter will develop breast cancer unless she has prophylactic surgery",
            "I can see that you are worried you harmed your daughter; can you tell me what frightens you most about this result?",
            "Your daughter has a 50% risk, so we should arrange genetic testing for her today",
            "You should not blame yourself because inherited variants are entirely outside a parent's control",
            "We need to focus on treating your cancer before discussing what this result could mean for your family",
        ],
        1,
        "The best initial response names the patient's emotion and invites her to explain her concern before providing more information. A pathogenic BRCA1 variant confers susceptibility rather than certainty, and predictive testing for an adult-onset condition is generally deferred in a healthy 12-year-old. Immediate reassurance, redirection, or arranging testing fails to explore the patient's distress.",
        tags=["brca1", "triple-negative-breast-cancer"],
        item_family="communication-ethics",
    ),
    question(
        18,
        "The Endocrine System",
        24,
        "Thyroid Nodules and Thyroid Tumors",
        5,
        1088,
        "A 30-year-old woman who received radiation therapy to the neck during childhood has a painless thyroid nodule. A histologic section of the nodule is shown. Molecular analysis is most likely to demonstrate an alteration that directly activates which of the following intracellular signaling pathways?",
        [
            "JAK-STAT signaling",
            "WNT-beta-catenin signaling",
            "RAS-RAF-MAPK signaling",
            "Hedgehog-GLI signaling",
            "TGF-beta-SMAD signaling",
        ],
        2,
        "RET/PTC rearrangements create constitutively active receptor tyrosine kinase fusion proteins that signal through the RAS-RAF-MAPK pathway. Activating BRAF mutations provide an alternative alteration in the same pathway in conventional papillary thyroid carcinoma.",
        tags=["papillary-thyroid-carcinoma", "ret-ptc"],
        image_urls=["/uploads/usmle-pathology-robbins-q18-papillary-thyroid-carcinoma.png"],
    ),
    question(
        19,
        "Bones, Joints, and Soft Tissue Tumors",
        26,
        "Bone-Forming Tumors: Osteoma, Osteoid Osteoma, and Osteosarcoma",
        4,
        1189,
        "A 16-year-old boy has 3 months of progressive pain and swelling above the knee. He has no history of trauma, fever, or weight loss. A radiograph of the affected limb is shown. Biopsy of the lesion is most likely to demonstrate which of the following findings?",
        [
            "Atypical chondrocytes embedded in a lobulated hyaline cartilage matrix",
            "Malignant spindle cells surrounding lace-like deposits of osteoid",
            "Mononuclear stromal cells admixed uniformly with osteoclast-type giant cells",
            "Sheets of small round cells with scant cytoplasm and diffuse CD99 expression",
            "Well-differentiated plasma cells with eccentric clock-face nuclei",
        ],
        1,
        "The aggressive metaphyseal lesion with a mixed destructive and bone-forming matrix, sunburst periosteal reaction, and Codman triangle is a conventional osteosarcoma. Its defining histologic feature is malignant mesenchymal cells directly producing lace-like osteoid. The other options describe chondrosarcoma, giant cell tumor, Ewing sarcoma, and a plasma-cell neoplasm.",
        tags=["osteosarcoma", "malignant-osteoid"],
        item_family="predicted-finding",
        image_urls=["/uploads/usmle-pathology-robbins-q19-osteosarcoma-xray.png"],
    ),
    question(
        20,
        "The Eye",
        29,
        "Vascular Retinopathies and Retinal Ischemia",
        7,
        1322,
        "A newborn delivered at 27 weeks' gestation requires supplemental oxygen for respiratory distress. Several weeks later, ophthalmologic examination shows abnormal proliferation of vessels at the border between vascularized and avascular retina. Contraction of the resulting fibrovascular membrane places the infant at risk for retinal detachment. Which of the following mediators is most likely increased in the ischemic peripheral retina?",
        [
            "Complement component C5a",
            "Endostatin",
            "Interferon-gamma",
            "Thromboxane A2",
            "Vascular endothelial growth factor",
        ],
        4,
        "High oxygen exposure constricts immature retinal vessels, leaving peripheral retina ischemic when oxygen is reduced. Ischemia upregulates VEGF and other proangiogenic factors, producing pathologic neovascularization whose contraction can cause retinal detachment.",
        tags=["retinopathy-of-prematurity", "vegf"],
    ),
]


def validate_questions():
    assert len(QUESTIONS) == 20
    assert len({item["id"] for item in QUESTIONS}) == 20
    for item in QUESTIONS:
        assert item["source"] == "usmle"
        assert item["subjectId"] == "pathology"
        assert len(item["options"]) == 5
        assert 0 <= item["answerIndex"] < len(item["options"])
        assert item["answer"] == item["options"][item["answerIndex"]]
        assert (item["leadIn"] or item["prompt"]).strip().endswith("?")
        assert item["explanation"].strip()
        assert len(item["imageUrls"]) <= 1
        for finding in item["laboratoryFindings"]:
            assert set(finding) == {"test", "value", "reference"}
            assert all(str(value).strip() for value in finding.values())

    item_families = [item["itemFamily"] for item in QUESTIONS]
    assert item_families.count("diagnosis") in {1, 2}
    assert item_families.count("communication-ethics") == 1
    assert item_families.count("experimental-design") == 1
    assert sum(bool(item["laboratoryFindings"]) for item in QUESTIONS) >= 5
    assert sum(bool(item["imageUrls"]) for item in QUESTIONS) == 4


def main():
    validate_questions()
    database = json.loads(DATABASE_PATH.read_text(encoding="utf-8-sig"))
    existing = database.get("questions", [])
    retained = [item for item in existing if not str(item.get("id", "")).startswith(ID_PREFIX)]
    database["questions"] = [*retained, *QUESTIONS]
    DATABASE_PATH.write_text(json.dumps(database, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Stored {len(QUESTIONS)} USMLE Step 1-style pathology questions.")
    print(f"Database question count: {len(existing)} -> {len(database['questions'])}")


if __name__ == "__main__":
    main()
