"""Build original integrated items from the sources audited in docs/usmle-module-1-review.md.

Only the dedicated module bank is written; existing subject banks and user data are untouched.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULE_ID = "usmle-module-01"


def ref(book, edition, chapter, pdf_pages=None, pages=None, url=None):
    return {key: value for key, value in {
        "book": book, "edition": edition, "chapter": chapter,
        "pdfPages": pdf_pages, "pages": pages, "url": url,
    }.items() if value}


def bio(chapter, pdf_pages):
    return ref("Vasudevan, Sreekumari & Vaidyanathan: Textbook of Biochemistry for Medical Students", "6th ed.", chapter, pdf_pages)


def robbins(chapter, pdf_pages):
    return ref("Robbins & Cotran Pathologic Basis of Disease", "10th ed.", chapter, pdf_pages)


def goodman(chapter, pdf_pages):
    return ref("Goodman & Gilman's The Pharmacological Basis of Therapeutics", "14th ed.", chapter, pdf_pages)


def lab(test, value, reference):
    return {"test": test, "value": value, "reference": reference}


def item(number, disciplines, system, topic, prompt, lead_in, choices, correct, explanation,
         objective, reasoning, references, family="mechanism", labs=None):
    # Choices carry their own teaching notes, so key placement cannot detach a rationale.
    return {
        "id": f"{MODULE_ID}-q{number:03d}", "moduleId": MODULE_ID,
        "questionNumber": number, "subjectId": MODULE_ID, "subjectTitle": "Module 1",
        "examId": "usmle-step-1", "examTitle": "USMLE Step 1 · Integrated Practice",
        "source": "usmle", "topic": topic, "organSystem": system,
        "disciplines": disciplines, "itemFamily": family, "difficulty": "integrated",
        "prompt": prompt, "leadIn": lead_in,
        "options": [choice[0] for choice in choices], "answerIndex": correct,
        "answer": choices[correct][0], "optionExplanations": [choice[1] for choice in choices],
        "explanation": explanation, "educationalObjective": objective,
        "reasoningChain": reasoning, "references": references,
        "laboratoryFindings": labs or [], "imageUrls": [],
        "tags": ["usmle-step-1", "integrated", "module-1", *[d.lower().replace(" ", "-") for d in disciplines]],
    }


QUESTIONS = [
    item(1, ["Biochemistry", "Pathology", "Pharmacology"], "Hematologic", "Oxidative injury and erythrocyte metabolism",
        "A 24-year-old man develops fatigue, jaundice, and dark urine 2 days after beginning trimethoprim-sulfamethoxazole for a skin infection. He recalls a similar episode after eating fava beans as a child but is otherwise well between episodes. Examination shows scleral icterus. A peripheral smear shows erythrocytes with semicircular defects at their margins; a supravital stain reveals dark intracellular inclusions. The direct antiglobulin test is negative. Laboratory results are shown below.",
        "Reduced availability of which of the following most directly prevents these erythrocytes from regenerating the antioxidant needed to tolerate the medication?",
        [
            ("ATP generated by glycolysis", "Pyruvate kinase deficiency lowers ATP and impairs red-cell membrane maintenance. It usually causes chronic hemolysis, often with echinocytes; episodic oxidant-triggered Heinz-body formation points to deficient antioxidant reducing power instead."),
            ("NADH generated by glycolysis", "NADH supplies the principal cytochrome b5 reductase pathway that reduces methemoglobin. It is not the reducing equivalent used by glutathione reductase; predominant methemoglobinemia would cause cyanosis rather than this classic oxidant hemolysis pattern."),
            ("NADPH generated by the pentose phosphate pathway", "Correct. G6PD supplies NADPH, which glutathione reductase uses to restore reduced glutathione. Inadequate reduced glutathione permits peroxide-mediated hemoglobin and membrane damage."),
            ("FADH2 generated by the citric acid cycle", "Mature erythrocytes lack mitochondria and cannot run the citric acid cycle. This cannot be their source of antioxidant reducing power."),
            ("Ribose-5-phosphate generated by the pentose phosphate pathway", "Ribose-5-phosphate is used to make nucleotides. Although it shares a pathway with NADPH, it does not donate electrons to glutathione reductase, and mature erythrocytes do not synthesize DNA."),
        ], 2,
        "The episodic drug- and fava-bean-associated hemolysis indicates glucose-6-phosphate dehydrogenase deficiency. Oxidized hemoglobin precipitates as Heinz bodies; splenic removal of these inclusions produces bite cells. G6PD is the first enzyme in the oxidative pentose phosphate pathway. Its NADPH product allows glutathione reductase to convert oxidized glutathione back to reduced glutathione, which supports peroxide detoxification. The negative antiglobulin test favors a nonimmune process. The elevated reticulocyte count reflects an appropriate marrow response.",
        "Connect an oxidant drug exposure to the NADPH–glutathione defense system in erythrocytes.",
        "Oxidant exposure + episodic hemolysis + Heinz/bite cells → G6PD deficiency → insufficient NADPH → impaired regeneration of reduced glutathione.",
        [bio("Ch. 10, Minor Metabolic Pathways of Carbohydrates; Ch. 20, Free Radicals and Antioxidants; Ch. 23, Clinical Enzymology", "131–132, 253, 286")],
        labs=[lab("Hemoglobin", "8.6 g/dL", "13.5–17.5 g/dL"), lab("Reticulocytes", "8.0%", "0.5–2.5%"), lab("Indirect bilirubin", "3.2 mg/dL", "0.2–0.8 mg/dL")]),

    item(2, ["Microbiology", "Physiology", "Biochemistry"], "Gastrointestinal", "Enterotoxin signaling and epithelial transport",
        "A 32-year-old woman is treated at a field clinic after a flood disrupts the local drinking-water supply. During the past 12 hours, she has passed repeated large volumes of watery stool and developed leg cramps. Her temperature is 36.8°C, pulse is 118/min, and blood pressure is 88/54 mm Hg. Stool microscopy shows few leukocytes and no erythrocytes. Culture yields oxidase-positive, curved gram-negative rods. She receives intravenous fluid replacement and then an oral solution containing glucose and sodium.",
        "Which of the following intestinal epithelial functions remains sufficiently intact to explain the benefit of the oral solution despite the organism's toxin?",
        [
            ("Apical sodium-glucose cotransport driven by a sodium gradient", "Correct. SGLT1 couples glucose entry to sodium uptake using the gradient maintained by basolateral Na+/K+-ATPase. This absorptive pathway continues to operate in cholera, and water follows absorbed solute."),
            ("Apical chloride secretion stimulated by cyclic AMP", "Cholera toxin increases cAMP and chloride secretion. This is the mechanism of fluid loss, not the preserved absorptive process responsible for oral rehydration."),
            ("Apical sodium entry through an aldosterone-sensitive channel", "ENaC participates in electrogenic sodium uptake in the distal colon and kidney. It is not the glucose-coupled small-intestinal transport mechanism targeted by the oral solution."),
            ("Apical fructose uptake through a sodium-independent transporter", "GLUT5 transports fructose independently of sodium. This solution supplies glucose, and the therapeutic mechanism requires coupled sodium absorption."),
            ("Apical glucose transport coupled directly to ATP hydrolysis", "The relevant apical carrier does not itself hydrolyze ATP. It uses secondary active transport; ATP is consumed by the basolateral sodium pump that establishes the gradient."),
        ], 0,
        "The outbreak, profuse noninflammatory diarrhea, and curved oxidase-positive rods indicate cholera. Its toxin ADP-ribosylates Gs, sustaining adenylyl cyclase activity and increasing cAMP-dependent chloride secretion. The sodium-glucose cotransporter remains functional, allowing glucose and sodium in oral rehydration solution to be absorbed together. Water follows the absorbed solutes. Thus, toxin-driven secretion and useful absorptive transport can occur simultaneously; oral rehydration does not work by switching off the toxin.",
        "Distinguish toxin-induced secretion from the preserved sodium-glucose absorption used in oral rehydration.",
        "Noninflammatory secretory diarrhea + curved gram-negative rods → cholera toxin/cAMP signaling → preserved SGLT1-mediated sodium-glucose uptake permits rehydration.",
        [ref("Sastry & Bhat: Essentials of Medical Microbiology", "4th ed.", "Ch. 42, Vibrio", "953–955, 962–964"),
         ref("Indu Khurana: Medical Physiology for Undergraduate Students", "1st ed.", "Ch. 7.7, Digestion and Absorption", "523–524"),
         goodman("Ch. 54, Treatment of Disorders of Bowel Motility and Water Flux; Antiemetics; Agents Used in Biliary and Pancreatic Disease", "1115")], family="treatment-mechanism"),

    item(3, ["Physiology", "Pharmacology", "Pathology"], "Renal and cardiovascular", "Renal autoregulation during renin–angiotensin blockade",
        "A 68-year-old man with longstanding hypertension and peripheral arterial disease returns 6 days after lisinopril was added to his medications. His blood pressure has fallen from 176/96 to 148/84 mm Hg. Serum creatinine has risen from 1.1 to 2.3 mg/dL. He has had no vomiting, diarrhea, or change in fluid intake and has not taken NSAIDs. Urinalysis is bland. Duplex ultrasonography shows severe narrowing of both renal arteries. There is no urinary tract obstruction.",
        "Which of the following changes most directly explains the fall in glomerular filtration after the medication was started?",
        [
            ("Constriction of afferent arterioles with lower glomerular capillary pressure", "Afferent constriction can reduce filtration, for example when NSAIDs suppress vasodilator prostaglandins. ACE inhibition instead removes angiotensin II-dependent support of efferent arteriolar tone in this setting."),
            ("Dilation of afferent arterioles with higher glomerular capillary pressure", "Afferent dilation generally supports filtration by increasing pressure delivery to the glomerulus. It would not explain this drug-associated decline."),
            ("Constriction of efferent arterioles with higher glomerular capillary pressure", "This is the angiotensin II-mediated adaptation that helps preserve GFR when renal perfusion pressure is low. Lisinopril diminishes this adaptation."),
            ("Dilation of efferent arterioles with lower glomerular capillary pressure", "Correct. In bilateral renal artery stenosis, filtration is unusually dependent on angiotensin II-mediated efferent constriction. ACE inhibition relaxes that arteriole and lowers filtration pressure."),
            ("Contraction of mesangial cells with lower filtration surface area", "Mesangial contraction can reduce the ultrafiltration coefficient, but angiotensin II stimulates this contraction. Blocking its formation does not explain the creatinine rise through increased mesangial contraction."),
        ], 3,
        "Bilateral renal artery stenosis reduces perfusion pressure upstream of both glomeruli. Angiotensin II-mediated efferent arteriolar constriction helps maintain glomerular capillary hydrostatic pressure despite that reduction. Lisinopril inhibits angiotensin II production, removing the compensatory efferent constriction. Glomerular pressure and GFR fall, so creatinine rises. The preserved systemic blood pressure, bland urine, lack of volume loss, and bilateral arterial lesions favor a hemodynamic effect rather than inflammatory nephritis or obstruction.",
        "Explain why GFR can fall with ACE inhibition when renal perfusion depends on angiotensin II-mediated efferent tone.",
        "Bilateral renal artery stenosis → angiotensin II-dependent efferent constriction → ACE inhibition → efferent dilation and lower glomerular filtration pressure.",
        [goodman("Ch. 30, Renin and Angiotensin", "612, 619")], family="physiologic-prediction"),

    item(4, ["Anatomy", "Immunology", "Pathology"], "Developmental and immune", "Pharyngeal development and T-cell maturation",
        "A 3-week-old boy is brought to the emergency department after a generalized seizure. He has perioral twitching and a harsh systolic murmur. Serum ionized calcium is 0.72 mmol/L (reference 1.10–1.35), and parathyroid hormone is inappropriately low. Echocardiography shows a common arterial trunk arising above a ventricular septal defect. Chest imaging shows no visible thymic shadow. Flow cytometry shows markedly reduced CD3-positive lymphocytes with preserved numbers of CD19-positive lymphocytes.",
        "Abnormal development of which of the following structures best unifies the endocrine and lymphocyte findings?",
        [
            ("The first pharyngeal pouch", "The first pouch forms the tubotympanic recess, including the middle-ear cavity and auditory tube. It does not produce the thymus or parathyroid glands."),
            ("The third and fourth pharyngeal pouches", "Correct. The third pouch gives rise to the thymus and inferior parathyroids, and the fourth supplies the superior parathyroids. Their abnormal development links hypocalcemia to impaired T-cell maturation."),
            ("The first pharyngeal cleft", "The first cleft contributes to the external acoustic meatus. A cleft abnormality cannot explain simultaneous thymic and parathyroid hypoplasia."),
            ("The median thyroid diverticulum", "This produces thyroid follicular tissue. Its abnormal development causes problems of thyroid location or hormone production, not the combination of low PTH and selective T-cell depletion."),
            ("The second pharyngeal pouch", "The second pouch contributes to the epithelium of the palatine tonsil. It is not the embryologic source of the thymus and parathyroids."),
        ], 1,
        "Hypocalcemia with low PTH, a conotruncal heart defect, and marked T-cell deficiency point to the DiGeorge phenotype of 22q11.2 deletion syndrome. Abnormal pharyngeal apparatus development impairs formation of the thymus and parathyroid glands. Thymic hypoplasia reduces T-cell maturation; parathyroid hypoplasia causes hypocalcemic tetany or seizures. B-cell numbers can be preserved because their early development occurs in bone marrow, although antibody responses may still be impaired when T-cell help is deficient.",
        "Integrate pharyngeal-pouch embryology with parathyroid function and thymic T-cell maturation.",
        "Low-PTH hypocalcemia + conotruncal defect + absent thymic shadow → DiGeorge phenotype → abnormal third/fourth pouch development.",
        [robbins("Ch. 5, Genetic Disorders; Ch. 6, Diseases of the Immune System", "178–179, 252–253")]),

    item(5, ["Biochemistry", "Anatomy", "Pathology"], "Gastrointestinal, hematologic and nervous", "Ileal absorption and cobalamin-dependent reactions",
        "A 46-year-old woman has gradually worsening fatigue and difficulty walking in the dark. Five years ago, she underwent resection of 90 cm of terminal ileum for Crohn disease. She eats a varied diet but has not taken prescribed vitamin supplements. Examination shows a smooth tongue, reduced vibration sense at the ankles, and a positive Romberg sign. Her peripheral smear shows macro-ovalocytes and hypersegmented neutrophils. Kidney function is normal. Laboratory results are shown below.",
        "Activity of which of the following reactions is most likely reduced by the nutritional deficiency responsible for her findings?",
        [
            ("Conversion of pyruvate to oxaloacetate", "Pyruvate carboxylase requires biotin. Biotin deficiency does not explain the combination of terminal ileal resection, megaloblastosis, and posterior-column sensory dysfunction."),
            ("Conversion of methylmalonyl-CoA to succinyl-CoA", "Correct. Methylmalonyl-CoA mutase requires adenosylcobalamin. Reduced activity in B12 deficiency increases methylmalonic acid, distinguishing it from isolated folate deficiency."),
            ("Conversion of glucose-6-phosphate to 6-phosphogluconolactone", "G6PD uses NADP+ in the pentose phosphate pathway. Its deficiency produces oxidant-sensitive hemolysis rather than this delayed malabsorption-related neurologic and megaloblastic syndrome."),
            ("Conversion of homocysteine to cystathionine", "Cystathionine beta-synthase requires pyridoxal phosphate, derived from vitamin B6. It is distinct from B12-dependent remethylation of homocysteine and cannot explain the full clinical pattern."),
            ("Conversion of phenylalanine to tyrosine", "Phenylalanine hydroxylase uses tetrahydrobiopterin. Its deficiency presents with phenylalanine accumulation, not megaloblastosis after terminal ileal resection."),
        ], 1,
        "The intrinsic factor–B12 complex is absorbed in the terminal ileum. Resection can produce B12 deficiency after the body's substantial stores are depleted. Cobalamin deficiency impairs both methionine synthase and methylmalonyl-CoA mutase; the latter converts methylmalonyl-CoA to succinyl-CoA. It therefore raises methylmalonic acid as well as homocysteine. Folate deficiency also causes megaloblastosis and elevated homocysteine, but does not impair methylmalonyl-CoA mutase and does not explain this characteristic sensory syndrome.",
        "Link ileal anatomy, delayed B12 depletion, megaloblastosis, and impaired methylmalonyl-CoA metabolism.",
        "Terminal ileal resection + macrocytosis + impaired vibration sense → B12 deficiency → reduced methylmalonyl-CoA mutase activity.",
        [bio("Ch. 11, Metabolism of Fatty Acids; Ch. 34, Water Soluble Vitamins", "149, 419–421")],
        labs=[lab("Hemoglobin", "9.1 g/dL", "12.0–16.0 g/dL"), lab("Mean corpuscular volume", "114 fL", "80–100 fL"), lab("Serum creatinine", "0.8 mg/dL", "0.6–1.1 mg/dL")]),

    item(6, ["Anatomy", "Physiology", "Pathology"], "Nervous", "Brainstem localization and branchial motor function",
        "A 63-year-old man develops sudden vertigo, vomiting, and difficulty swallowing. His voice becomes hoarse. Examination shows left-sided limb ataxia, reduced pain and temperature sensation on the left side of the face, and reduced pain and temperature sensation on the right side of the trunk and limbs. The left palate elevates poorly. His tongue protrudes in the midline, limb strength is preserved, and vibration sense is intact. MRI shows a small acute infarct in the left dorsolateral medulla.",
        "Damage to which of the following structures most directly accounts for the hoarseness and palatal weakness?",
        [
            ("Left hypoglossal nucleus", "A hypoglossal lesion weakens the ipsilateral tongue and causes deviation toward the lesion. Midline tongue protrusion argues against it, and it does not provide motor supply to the palate or larynx."),
            ("Left dorsal motor nucleus of the vagus", "This nucleus supplies parasympathetic preganglionic output to thoracic and abdominal viscera. It does not provide the branchial motor neurons responsible for palatal and laryngeal movement."),
            ("Left spinal trigeminal nucleus", "This explains loss of ipsilateral facial pain and temperature. It is a sensory nucleus and cannot account for the palatal weakness or hoarseness."),
            ("Left nucleus of the solitary tract", "The solitary nucleus receives taste and visceral sensory inputs. It is distinct from the branchial motor outflow to swallowing and phonation muscles."),
            ("Left nucleus ambiguus", "Correct. Nucleus ambiguus supplies branchial motor fibers, principally through the vagus for palatal, pharyngeal, and laryngeal function. Its injury produces dysphagia, palatal weakness, and hoarseness."),
        ], 4,
        "Crossed loss of facial and body pain-temperature sensation with ipsilateral ataxia localizes to the lateral medulla. The nucleus ambiguus lies in this region and supplies motor output to muscles important for swallowing and phonation. A lesion on the left therefore causes left palatal weakness and a hoarse voice. The preserved tongue movement, strength, and vibration sensation indicate sparing of the hypoglossal nucleus, corticospinal tract, and medial lemniscus, which are more medially situated.",
        "Map individual deficits within a lateral medullary syndrome to the appropriate cranial nerve nucleus.",
        "Crossed pain-temperature loss + ipsilateral ataxia → lateral medulla → hoarseness and palatal weakness identify nucleus ambiguus injury.",
        [ref("B. D. Chaurasia's Human Anatomy, Volume 3: Head, Neck and Brain", "6th ed.", "Ch. 24, Cranial Nerves; Ch. 25, Brain Stem", "357–360, 399–400")], family="localization"),

    item(7, ["Biochemistry", "Pathology"], "Metabolic and nervous", "Urea-cycle failure and pyrimidine synthesis",
        "A 5-day-old boy is evaluated for poor feeding, vomiting, and increasing somnolence after initially appearing healthy. He is breathing rapidly without retractions. His mother reports that a maternal uncle died during the first week of life. There is no hepatomegaly. Blood cultures are negative, blood glucose is normal, and urine ketones are absent. Plasma amino-acid analysis shows low citrulline. Additional results are shown below.",
        "Which of the following mechanisms best explains the increased urinary orotic acid in this infant?",
        [
            ("Reduced cleavage of argininosuccinate to arginine and fumarate", "Argininosuccinate lyase deficiency causes argininosuccinate accumulation and can cause hyperammonemia. The proximal block suggested by low citrulline and the X-linked family pattern is a better fit for OTC deficiency."),
            ("Reduced conversion of orotidine monophosphate to uridine monophosphate", "UMP synthase deficiency causes primary orotic aciduria with megaloblastic anemia. It does not cause the marked hyperammonemia and low citrulline of a urea-cycle block."),
            ("Increased conversion of glutamine to carbamoyl phosphate within the urea cycle", "Glutamine-dependent carbamoyl phosphate synthetase II is cytosolic and serves pyrimidine synthesis. The mitochondrial urea-cycle enzyme, CPS I, uses free ammonia, so this proposed reaction misidentifies both the nitrogen donor and pathway."),
            ("Diversion of accumulated mitochondrial carbamoyl phosphate into cytosolic pyrimidine synthesis", "Correct. OTC deficiency blocks transfer of carbamoyl phosphate to ornithine. Excess carbamoyl phosphate becomes available to the pyrimidine pathway, increasing orotate production."),
            ("Reduced mitochondrial synthesis of carbamoyl phosphate from ammonia", "CPS I deficiency also causes severe hyperammonemia with low citrulline, but little carbamoyl phosphate is produced. It therefore lacks the characteristic orotate elevation that distinguishes OTC deficiency here."),
        ], 3,
        "Severe neonatal hyperammonemia, low citrulline, elevated orotic acid, and a maternal-line history indicate ornithine transcarbamylase deficiency, an X-linked urea-cycle disorder. OTC normally combines mitochondrial carbamoyl phosphate with ornithine to form citrulline. The blocked reaction allows carbamoyl phosphate to accumulate and feed cytosolic pyrimidine synthesis, producing excess orotate. Impaired urea production explains the low blood urea nitrogen. Primary orotic aciduria is a pyrimidine-synthesis defect with megaloblastic anemia and no primary hyperammonemia.",
        "Use orotate excretion to distinguish OTC deficiency from CPS I deficiency and primary orotic aciduria.",
        "Neonatal hyperammonemia + low citrulline + high orotate + maternal-line history → OTC deficiency → carbamoyl phosphate overflow into pyrimidine synthesis.",
        [bio("Ch. 14, General Amino Acid Metabolism; Ch. 39, Metabolism of Nucleotides", "193–195, 482–483")],
        labs=[lab("Plasma ammonia", "410 µmol/L", "Neonatal laboratory interval: 20–90 µmol/L"), lab("Blood urea nitrogen", "2 mg/dL", "Neonatal laboratory interval: 3–12 mg/dL"), lab("Urinary orotic acid", "Markedly increased", "Not increased")]),

    item(8, ["Pharmacology", "Physiology", "Biochemistry"], "Toxicology, respiratory and metabolic", "Mixed acid–base disturbance in salicylate toxicity",
        "A 29-year-old woman comes to the emergency department because of nausea, ringing in her ears, and rapid breathing. For 2 days she has repeatedly taken an aspirin-containing preparation for severe dental pain, exceeding the package instructions. Her temperature is 38.0°C, pulse is 112/min, and respirations are 30/min. She is alert, and her lungs are clear. Serum albumin and creatinine are normal. Arterial blood gas and electrolyte results are shown below.",
        "Which of the following acid–base disturbances best explains these findings?",
        [
            ("Primary respiratory alkalosis with appropriate renal compensation alone", "Hyperventilation explains the low PaCO2, but compensation alone does not explain an anion gap of 26 mEq/L. There is an additional metabolic acid load."),
            ("Primary high-anion-gap metabolic acidosis with appropriate respiratory compensation alone", "For bicarbonate of 14 mEq/L, Winter's formula predicts PaCO2 of about 29 ± 2 mm Hg. The measured value of 20 is lower, identifying an additional primary respiratory alkalosis."),
            ("Combined high-anion-gap metabolic acidosis and respiratory alkalosis", "Correct. The anion gap is 140 − (100 + 14) = 26 mEq/L. PaCO2 is below the compensatory range predicted for this bicarbonate concentration, so two primary processes coexist."),
            ("Combined normal-anion-gap metabolic acidosis and respiratory alkalosis", "The respiratory component fits, but the anion gap is elevated. Bicarbonate loss alone, such as diarrhea or renal tubular acidosis, would not produce this electrolyte pattern."),
            ("Combined high-anion-gap metabolic acidosis and respiratory acidosis", "The metabolic component fits, but respiratory acidosis requires PaCO2 to be higher than expected for the bicarbonate level. Here PaCO2 is substantially lower than expected."),
        ], 2,
        "Salicylates stimulate ventilation and can also cause accumulation of organic acids through disturbed cellular energy metabolism. This produces primary respiratory alkalosis together with high-anion-gap metabolic acidosis. The anion gap is 26 mEq/L. With bicarbonate of 14, appropriate respiratory compensation for an isolated metabolic acidosis would give PaCO2 near 29 ± 2 mm Hg; the actual value is 20. The mildly alkalemic pH therefore does not exclude a clinically important metabolic acidosis. The pH is internally consistent with the reported bicarbonate and PaCO2.",
        "Recognize a mixed acid–base disorder by calculating the anion gap and comparing PaCO2 with expected compensation.",
        "Aspirin exposure + tinnitus/tachypnea → salicylate toxicity; elevated anion gap + PaCO2 below Winter's prediction → metabolic acidosis plus respiratory alkalosis.",
        [goodman("Ch. 42, Pharmacotherapy of Inflammation, Fever, Pain, and Gout: Salicylate Intoxication", "858–859"),
         ref("Harrison's Principles of Internal Medicine", "20th ed.", "Ch. 51, Acidosis and Alkalosis, Table 51-1", "361", "315")], family="diagnosis",
        labs=[lab("Arterial pH", "7.47", "7.35–7.45"), lab("PaCO2", "20 mm Hg", "35–45 mm Hg"), lab("Bicarbonate", "14 mEq/L", "22–28 mEq/L"), lab("Sodium", "140 mEq/L", "135–145 mEq/L"), lab("Chloride", "100 mEq/L", "98–106 mEq/L")]),

    item(9, ["Immunology", "Pathology", "Anatomy"], "Pulmonary and renal", "Shared basement-membrane antigen and antibody-mediated injury",
        "A 27-year-old man is admitted with 4 days of cough productive of blood-streaked sputum and dark urine. Serum creatinine has increased rapidly, and urinalysis shows dysmorphic erythrocytes and red-cell casts. Chest imaging shows bilateral air-space opacities. Kidney biopsy demonstrates crescent formation; immunofluorescence shows a smooth, continuous linear band of IgG along glomerular capillary basement membranes. There is no history of chronic sinus disease, and testing for antineutrophil cytoplasmic antibodies is negative.",
        "The pathogenic antibodies are most likely directed against which of the following targets?",
        [
            ("A noncollagenous domain of a type IV collagen chain", "Correct. Anti-GBM antibodies recognize the NC1 domain of the alpha-3 chain of type IV collagen. Its distribution in glomerular and alveolar basement membranes explains the pulmonary-renal pattern and linear IgG staining."),
            ("A proteinase in neutrophil azurophilic granules", "Proteinase 3 is an ANCA target in granulomatosis with polyangiitis. That disease generally causes pauci-immune glomerulonephritis rather than continuous linear IgG along the basement membrane."),
            ("A phospholipase receptor on podocyte membranes", "PLA2R is a common target in primary membranous nephropathy. It produces subepithelial immune deposits and a nephrotic presentation, not this characteristic pulmonary hemorrhage with linear anti-GBM staining."),
            ("A nucleosomal antigen in circulating immune complexes", "Nuclear-antigen immune complexes can produce lupus nephritis. Their deposition produces granular immune staining rather than uniform linear binding along an intrinsic basement-membrane antigen."),
            ("A hemidesmosomal protein in the epidermal basement membrane", "BP180/BP230-directed autoimmunity causes bullous pemphigoid. Linear staining can occur at the dermal-epidermal junction, but this target does not explain glomerular and alveolar injury."),
        ], 0,
        "Pulmonary hemorrhage and rapidly progressive glomerulonephritis with linear IgG staining indicate anti-glomerular basement membrane disease with pulmonary involvement (Goodpasture syndrome). Antibodies bind an intrinsic antigen, the noncollagenous domain of the alpha-3 chain of type IV collagen, distributed along glomerular and alveolar basement membranes. This is antibody-mediated, type II hypersensitivity. Uniform antigen distribution creates linear staining; deposition of preformed immune complexes instead tends to produce a granular pattern.",
        "Connect a shared structural antigen to a pulmonary-renal syndrome and its immunofluorescence pattern.",
        "Pulmonary hemorrhage + nephritic urine + linear glomerular IgG → anti-GBM disease → antibodies to alpha-3 type IV collagen NC1 domain.",
        [robbins("Ch. 6, Diseases of the Immune System; Ch. 20, The Kidney: Crescentic Glomerulonephritis", "219, 911–913")]),

    item(10, ["Biochemistry", "Microbiology", "Pathology"], "Pulmonary and gastrointestinal", "Protein quality control and multisystem disease",
        "A 9-year-old boy is evaluated for poor weight gain, frequent bulky stools, and recurrent lower respiratory infections. Sputum culture grows Pseudomonas aeruginosa. Sweat chloride is 86 mmol/L (diagnostic threshold for cystic fibrosis: at least 60 mmol/L in the appropriate clinical setting). Sequencing identifies a three-nucleotide deletion that removes phenylalanine at position 508 of an epithelial chloride-channel protein. Studies of his cells show near-normal messenger RNA abundance but very little channel protein at the apical membrane.",
        "Which of the following processes most directly accounts for the low membrane abundance of this mutant protein?",
        [
            ("Nonsense-mediated degradation of transcripts with premature stop codons", "Nonsense-mediated decay removes transcripts containing certain premature termination codons. This is an in-frame three-nucleotide deletion, and messenger RNA abundance is preserved."),
            ("Failure of mature channels to open after ATP binding", "A gating defect can leave channels present at the cell surface but poorly functional. It does not explain the near-absence of apical protein characteristic of the specified deletion."),
            ("Loss of the promoter required for transcription initiation", "A promoter defect would reduce messenger RNA production. The stem specifies preserved messenger RNA and a coding-region in-frame deletion."),
            ("Ubiquitin-dependent degradation after endoplasmic-reticulum retention", "Correct. Phe508del causes misfolding, retention by endoplasmic-reticulum quality control, and proteasomal degradation before much protein reaches the apical membrane."),
            ("Reduced chloride conductance through normally trafficked channels", "A conductance mutation impairs ion passage through surface channels. It does not primarily prevent the protein from reaching the membrane."),
        ], 3,
        "The clinical pattern is cystic fibrosis, and the specified mutation is Phe508del (ΔF508), a class II CFTR defect. The deletion preserves the reading frame but interferes with protein folding. Endoplasmic-reticulum quality-control machinery retains the abnormal protein and targets it for proteasomal degradation, leaving little CFTR at the apical surface. Impaired epithelial ion and water transport promotes thick secretions, chronic airway infection, and pancreatic exocrine dysfunction. This trafficking defect differs from mutations that produce a normal amount of poorly gating or poorly conducting surface protein.",
        "Distinguish a CFTR folding/trafficking mutation from transcription, gating, and conductance defects.",
        "Pulmonary infections + pancreatic malabsorption + high sweat chloride → cystic fibrosis; Phe508del + preserved mRNA → misfolding and pre-membrane degradation.",
        [robbins("Ch. 10, Diseases of Infancy and Childhood: Cystic Fibrosis", "475–479")]),

    item(11, ["Pharmacology", "Microbiology", "Biochemistry"], "Urinary and microbial metabolism", "Sequential blockade of microbial folate metabolism",
        "A 23-year-old woman is treated for dysuria and urinary frequency without fever or flank pain. Urine culture grows Escherichia coli susceptible to trimethoprim-sulfamethoxazole. In a laboratory study of the isolate, sulfamethoxazole inhibits synthesis of folate from para-aminobenzoic acid. Addition of trimethoprim produces a substantially greater reduction in bacterial growth by blocking a later step in the same pathway. The patient's own cells obtain folate from the diet.",
        "Which of the following reactions is directly inhibited by trimethoprim to produce this sequential blockade?",
        [
            ("Incorporation of para-aminobenzoic acid into dihydropteroate", "This is the dihydropteroate synthase step inhibited by sulfamethoxazole. Trimethoprim acts later in the pathway, so choosing the same step misses the basis of the sequential blockade."),
            ("Transfer of a methyl group from methyltetrahydrofolate to homocysteine", "This is the cobalamin-dependent methionine synthase reaction. It is not the microbial enzyme directly targeted by trimethoprim."),
            ("Conversion of deoxyuridylate to thymidylate", "Thymidylate synthesis is impaired downstream when reduced folate is depleted. Trimethoprim does not directly inhibit thymidylate synthase; direct inhibition is associated with other drugs such as fluoropyrimidines."),
            ("Reduction of ribonucleoside diphosphates to deoxyribonucleoside diphosphates", "Ribonucleotide reductase performs this reaction. It is inhibited by hydroxyurea, not by trimethoprim."),
            ("Reduction of dihydrofolate to tetrahydrofolate", "Correct. Trimethoprim preferentially inhibits microbial dihydrofolate reductase. Reduced tetrahydrofolate availability limits one-carbon transfers needed for nucleotide production."),
        ], 4,
        "Sulfamethoxazole inhibits dihydropteroate synthase, whereas trimethoprim inhibits dihydrofolate reductase. Inhibiting successive steps lowers tetrahydrofolate availability more effectively than blocking either step alone. This restricts folate-dependent nucleotide synthesis. Human cells lack the de novo PABA-to-folate pathway, and trimethoprim binds microbial DHFR much more strongly than human DHFR. These differences explain selective toxicity, although selectivity is not absolute and adverse effects can still occur.",
        "Identify the two distinct targets responsible for sequential inhibition of microbial folate metabolism.",
        "TMP-SMX exposure → early folate-synthesis block by SMX + later DHFR block by TMP → reduced tetrahydrofolate and nucleotide synthesis.",
        [goodman("Ch. 57, DNA Disruptors: Sulfonamides, Quinolones, and Nitroimidazoles", "1156–1157")], family="treatment-mechanism"),

    item(12, ["Pharmacology", "Physiology", "Biochemistry"], "Endocrine and metabolic", "Beta-cell electrical coupling in monogenic diabetes",
        "A 7-week-old girl is evaluated for persistent hyperglycemia and poor weight gain. Her serum insulin and C-peptide concentrations are low despite an elevated glucose concentration. Genetic testing identifies an activating KCNJ11 variant. In isolated beta cells carrying this variant, ATP-sensitive potassium channels remain open despite high intracellular ATP. A medication is then applied that binds the SUR1 subunit and closes these channels independently of the defective ATP-sensing response.",
        "Which of the following immediate cellular changes most directly promotes insulin granule exocytosis after the medication is applied?",
        [
            ("Membrane hyperpolarization with increased calcium influx", "Closing potassium efflux channels depolarizes, rather than hyperpolarizes, the beta cell. Hyperpolarization would keep voltage-dependent calcium channels less active."),
            ("Membrane depolarization with decreased calcium influx", "Depolarization opens voltage-dependent calcium channels. A decrease in calcium entry would impede, not promote, insulin granule exocytosis."),
            ("Membrane depolarization with increased calcium influx", "Correct. Reduced potassium efflux depolarizes the beta cell, opening voltage-dependent calcium channels. The rise in cytosolic calcium triggers insulin granule exocytosis."),
            ("Membrane hyperpolarization with decreased calcium influx", "This describes the direction associated with open KATP channels and reduced secretion. The drug is intended to reverse that state."),
            ("Unchanged membrane potential with increased chloride influx", "KATP closure changes membrane potential and recruits calcium entry. Chloride influx with no change in potential is not the coupling step described here."),
        ], 2,
        "KCNJ11 encodes Kir6.2, the pore-forming subunit of the beta-cell ATP-sensitive potassium channel. Activating variants can prevent the normal glucose/ATP-induced channel closure and cause neonatal diabetes. A sulfonylurea acts through the associated SUR1 subunit to close susceptible channels. Reduced potassium efflux depolarizes the membrane, opens voltage-dependent calcium channels, and raises intracellular calcium, which triggers exocytosis. Response varies by mutation; this item explicitly establishes drug-induced closure in the patient's cells.",
        "Trace potassium-channel closure through membrane depolarization and calcium entry to insulin secretion.",
        "Early insulin-deficient diabetes + activating KCNJ11 variant → persistent KATP opening; drug closes channel → depolarization → calcium influx → insulin exocytosis.",
        [goodman("Ch. 51, Endocrine Pancreas and Pharmacotherapy of Diabetes Mellitus and Hypoglycemia", "1043, 1047–1049, 1052–1053")], family="physiologic-prediction"),

    item(13, ["Immunology", "Biochemistry", "Microbiology"], "Immune and metabolic", "Purine catabolism and combined immunodeficiency",
        "A 4-month-old girl is hospitalized with persistent oral candidiasis, watery diarrhea, and hypoxemia. Bronchoalveolar lavage identifies Pneumocystis jirovecii. She has very low circulating T- and B-lymphocyte counts and low immunoglobulin concentrations. Her parents are first cousins. An erythrocyte enzyme assay shows profoundly reduced adenosine deaminase activity, and intracellular deoxyadenosine triphosphate is markedly elevated. A mitogen-stimulated lymphocyte culture shows severely impaired DNA synthesis.",
        "Inhibition of which of the following enzymes by the accumulated metabolite most directly contributes to the DNA-synthesis defect?",
        [
            ("Ribonucleotide reductase", "Correct. Excess dATP inhibits ribonucleotide reductase, limiting the balanced deoxyribonucleotide supply required for DNA synthesis in proliferating lymphocytes."),
            ("Hypoxanthine-guanine phosphoribosyltransferase", "HGPRT salvages hypoxanthine and guanine. Its inherited deficiency causes purine overproduction with hyperuricemia, rather than the ADA-associated combined immunodeficiency described here."),
            ("Xanthine oxidase", "Xanthine oxidase participates in uric acid production. Its inhibition reduces urate and does not account for dATP-mediated inhibition of DNA precursor synthesis."),
            ("Dihydroorotate dehydrogenase", "This enzyme supports de novo pyrimidine synthesis and is a drug target in immunomodulation. It is not the principal deoxyribonucleotide-generating enzyme inhibited by excess dATP."),
            ("Thymidine kinase", "Thymidine kinase salvages thymidine to thymidylate. Inhibiting this salvage enzyme does not explain the broad impairment of de novo deoxyribonucleotide production attributed to excess dATP."),
        ], 0,
        "Severe opportunistic infections and depletion of both T and B cells indicate combined immunodeficiency. The enzyme result establishes ADA deficiency, an autosomal recessive cause. Deoxyadenosine metabolites accumulate, including dATP, which inhibits ribonucleotide reductase and compromises DNA precursor production. This contributes to toxicity in developing lymphocytes; it is not the only mechanism of lymphocyte injury. T-cell loss explains susceptibility to Pneumocystis and persistent candidiasis, while B-cell dysfunction compromises humoral immunity.",
        "Connect a purine-catabolism defect to deoxyribonucleotide depletion and combined immunodeficiency.",
        "Opportunistic infections + low T/B cells + deficient ADA → dATP accumulation → ribonucleotide reductase inhibition and impaired lymphocyte DNA synthesis.",
        [bio("Ch. 39, Metabolism of Nucleotides", "480–483"), robbins("Ch. 6, Diseases of the Immune System: Severe Combined Immunodeficiency", "251–252")]),

    item(14, ["Behavioral science", "Pharmacology"], "Communication and hematologic care", "Exploring treatment concerns before counseling",
        "A 26-year-old woman with sickle cell disease attends a routine visit to discuss hydroxyurea after several painful episodes. The physician has explained its purpose and the need for monitoring. The patient pauses and says, 'My aunt took chemotherapy and lost her hair. When you say this drug is also used for cancer, I wonder if you are hiding something about my illness.' She is medically stable and has time to discuss her concerns.",
        "Which of the following is the most appropriate initial response?",
        [
            ("'Your blood tests do not suggest cancer. Shall we move on to the monitoring schedule?'", "Factual reassurance may be useful later, but moving directly to logistics closes exploration of the patient's fear and mistrust before their meaning is understood."),
            ("'The doses are different for this illness. Would you like me to list all the side effects?'", "This provides technical information before understanding the specific concern. A detailed side-effect list is less useful initially than acknowledging the emotion and inviting the patient's perspective."),
            ("'You can decline the medication. Should I record that you do not want treatment today?'", "Respect for autonomy is important, but the patient has expressed a concern, not an informed refusal. Treating the comment as a final decision prematurely ends the discussion."),
            ("'Your aunt's experience sounds frightening. Could you tell me more about what worries you about this treatment?'", "Correct. The response acknowledges the emotion and invites an open account of the patient's concern without assuming that she has refused treatment. Her answer can guide a clear, individualized explanation."),
            ("'I would not prescribe something unnecessary. Would it help if your family encouraged you to take it?'", "This centers the physician's authority and introduces pressure from family before exploring the patient's own perspective. It risks increasing rather than resolving mistrust."),
        ], 3,
        "The immediate task is to understand what the proposed treatment means to the patient. Acknowledging the frightening association and asking an open-ended question permits her to explain her concern. The clinician can then clarify why a medication may have more than one indication, discuss benefits and risks in understandable language, and check understanding. An initial factual correction, defensive reassurance, or premature documentation of refusal can miss the concern driving the conversation.",
        "Respond to treatment-related fear with an empathic acknowledgment and an open-ended invitation before further counseling.",
        "Patient links medication to a frightening family experience → acknowledge the emotion → explore the concern → tailor explanation and shared decision-making.",
        [ref("Clinical Methods: The History, Physical, and Laboratory Examinations", "3rd ed.", "Ch. 3, The Medical Interview", url="https://www.ncbi.nlm.nih.gov/books/NBK349/"), goodman("Ch. 69, General Principles of Cancer Pharmacotherapy", "1356–1357")], family="communication-ethics"),

    item(15, ["Behavioral science", "Immunology"], "Biostatistics and diagnostic reasoning", "Positive predictive value in a low-prevalence population",
        "A hospital laboratory evaluates a hypothetical serum autoantibody assay for an autoimmune disease. The assay has 90% sensitivity and 95% specificity against an independent reference standard. It is then used in a screening population of 1,000 adults, of whom 10% truly have the disease. Assume the sensitivity and specificity remain the same in this population and that every person receives both the assay and the reference standard. A participant's assay result is positive.",
        "Based on these data, what is the approximate probability that this participant truly has the disease?",
        [
            ("10%", "This is the pretest prevalence. A positive test changes the probability, so prevalence alone is not the probability asked for."),
            ("67%", "Correct. There are 100 diseased participants, yielding 90 true positives, and 900 nondiseased participants, yielding 45 false positives. PPV is 90/(90 + 45), approximately 67%."),
            ("90%", "This is sensitivity: the probability of a positive test among people who have the disease. It reverses the conditioning in the question, which asks for disease among positive tests."),
            ("95%", "This is specificity: the probability of a negative test among people without the disease. It is not the positive predictive value."),
            ("99%", "This approximates the negative predictive value here: 855/(855 + 10). It describes a negative result, whereas the participant tested positive."),
        ], 1,
        "Among 1,000 screened adults, 100 have the disease and 900 do not. Sensitivity of 90% gives 90 true positives and 10 false negatives. Specificity of 95% gives 855 true negatives and 45 false positives. Thus, 135 people test positive, of whom 90 have disease: PPV = 90/135 ≈ 67%. Even a fairly specific assay can produce a substantial fraction of false positive results when disease is uncommon. This calculation assumes the stated test performance applies to the screened population.",
        "Calculate disease probability after a positive test using prevalence, sensitivity, and specificity.",
        "Prevalence → 100 diseased/900 nondiseased → 90 true positives/45 false positives → PPV = 90/135 ≈ 67%.",
        [ref("Clinical Methods: The History, Physical, and Laboratory Examinations", "3rd ed.", "Ch. 6, Sensitivity, Specificity, and Predictive Value", url="https://www.ncbi.nlm.nih.gov/books/NBK383/")], family="biostatistics"),
]


def main():
    assert len(QUESTIONS) == 15
    assert len({q["id"] for q in QUESTIONS}) == 15
    for question in QUESTIONS:
        assert len(question["options"]) == len(set(question["options"])) == len(question["optionExplanations"]) == 5
        assert question["answer"] == question["options"][question["answerIndex"]]
        assert question["leadIn"].endswith("?")
        assert len(question["disciplines"]) >= 2
        assert question["references"] and all(r.get("pdfPages") or r.get("url") for r in question["references"])
    destination = ROOT / "data/usmle-module-bank.json"
    bank = json.loads(destination.read_text(encoding="utf-8")) if destination.exists() else {
        "schemaVersion": 1,
        "title": "USMLE Step 1 Integrated Modules",
        "modules": [{"id": f"usmle-module-{n:02d}", "moduleNumber": n, "title": f"Module {n}", "questions": []} for n in range(1, 11)],
    }
    module = next(m for m in bank["modules"] if m["id"] == MODULE_ID)
    module["questions"] = QUESTIONS
    destination.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Built {len(QUESTIONS)} integrated questions in Module 1; all other modules preserved.")


if __name__ == "__main__":
    main()
