import json
from pathlib import Path

DATA = Path("runtime-data/users.json")
CHAPTER = "Thorax"


def u(answer, wrong, prompt, explanation):
    return {"answer": answer, "wrong": wrong, "prompt": prompt, "explanation": explanation}


UPDATES = {
    "anatomy-thorax-introduction-11": u("Cervical pleura and apex of lung", ["Inferior lobe only", "Costodiaphragmatic recess", "Middle mediastinum"], "A medical student places a deep central venous line just above the clavicle and the patient develops sudden dyspnea. Which thoracic extension into the neck was most likely injured?", "The pleural cupula and lung apex project above the first rib into the root of neck, so supraclavicular procedures can cause pneumothorax."),
    "anatomy-thorax-introduction-12": u("Negative intrathoracic pressure is reduced by paradoxical rib movement", ["The diaphragm becomes anatomically absent", "The heart blocks both bronchi", "The pleural cavities fuse"], "A patient with multiple adjacent rib fractures has a chest-wall segment that moves inward during inspiration. Why does ventilation become inefficient?", "Flail chest causes paradoxical motion, reducing effective thoracic expansion and impairing pressure changes needed for ventilation."),
    "anatomy-thorax-introduction-13": u("Scalenes elevate the first two ribs", ["Internal intercostals depress the sternum", "Rectus abdominis elevates ribs", "Latissimus dorsi opens alveoli"], "A COPD patient fixes the upper limbs on a table and uses neck muscles to breathe. Which action helps inspiration?", "Accessory muscles such as scalenes and sternocleidomastoid elevate upper ribs/sternum when the shoulder girdle is fixed."),
    "anatomy-thorax-introduction-14": u("T1 lower brachial plexus and cervical sympathetic fibers", ["Femoral nerve and lumbar sympathetic trunk", "Phrenic nerve only", "Vagus nerve only"], "An apical lung tumor causes medial forearm wasting and ptosis with miosis. Which structures at the thoracic inlet explain this combination?", "Pancoast tumors may involve T1 fibers of the lower brachial plexus and sympathetic pathway, producing hand signs plus Horner syndrome."),
    "anatomy-thorax-introduction-15": u("Bucket-handle elevation of ribs", ["Pump-handle movement only", "Descent of sternum", "Closure of thoracic inlet"], "During forced inspiration, the transverse diameter of the lower thorax increases. Which rib movement best explains this?", "Bucket-handle movement elevates middle/lower ribs laterally, increasing transverse thoracic diameter."),

    "anatomy-thorax-bones-joints-thorax-11": u("Intercostal nerve and vessels in the costal groove", ["Phrenic nerve on pericardium", "Internal thoracic artery near sternum", "Thoracic duct posterior to esophagus"], "A junior doctor inserts a needle just below the lower border of a rib for pleural aspiration and the patient develops sharp bleeding and pain. What was injured?", "The intercostal VAN bundle lies in the costal groove along the inferior border of each rib."),
    "anatomy-thorax-bones-joints-thorax-12": u("Second costal cartilage at the sternal angle", ["First rib at xiphisternal joint", "Tenth rib at jugular notch", "Twelfth rib at manubrium"], "A clinician needs to count ribs before inserting a chest drain. Which palpable landmark is most reliable to find rib 2?", "The sternal angle is the articulation site of the second costal cartilage and is used to count ribs."),
    "anatomy-thorax-bones-joints-thorax-13": u("Subclavian vessels and brachial plexus", ["Median nerve in carpal tunnel", "Femoral vessels", "Sciatic nerve"], "A high-energy trauma patient has a first-rib fracture. Why is this fracture treated as a red flag even before lung imaging?", "First-rib fracture requires major force and lies close to subclavian vessels and brachial plexus."),
    "anatomy-thorax-bones-joints-thorax-14": u("Compression fracture of thoracic vertebral bodies", ["Dislocation of costal cartilages only", "Paralysis of intercostal muscles", "Fusion of pleural layers"], "An elderly osteoporotic woman develops progressive thoracic kyphosis and loss of height. What anatomical change best explains this?", "Osteoporotic wedge compression fractures of thoracic vertebral bodies exaggerate kyphosis."),
    "anatomy-thorax-bones-joints-thorax-15": u("Costovertebral and costotransverse joints move during respiration", ["Ribs are completely immobile", "Only sternum moves and ribs do not", "Pleura prevents rib movement"], "A rib-fracture patient says pain increases with every breath. Which anatomical principle explains this pain pattern?", "Respiration requires rib movement at costovertebral and costotransverse joints, stressing the fracture site."),

    "anatomy-thorax-wall-thorax-11": u("Insert just superior to the upper border of the rib", ["Insert along the inferior border of rib", "Insert through the sternum", "Insert below the costal margin"], "In the safe triangle for chest drain insertion, where should the tube pass relative to the rib to avoid the main intercostal bundle?", "The main intercostal vein, artery and nerve run under the rib above, so instruments pass just above the upper border of the lower rib."),
    "anatomy-thorax-wall-thorax-12": u("Intercostal nerve dermatome", ["Azygos venous channel", "Pulmonary artery segment", "Thoracic duct territory"], "A patient has burning vesicular pain in a narrow band around the chest wall, not crossing the midline. Which anatomy explains the pattern?", "Herpes zoster reactivation follows a thoracic spinal nerve dermatome via an intercostal nerve."),
    "anatomy-thorax-wall-thorax-13": u("Internal thoracic artery", ["Azygos vein", "Pulmonary trunk", "Thoracic duct"], "A CABG surgeon chooses a vessel running vertically just lateral to the sternum because of excellent long-term patency. Which vessel is harvested?", "The internal thoracic artery descends near the sternum and is commonly used for coronary artery bypass grafting."),
    "anatomy-thorax-wall-thorax-14": u("Enlarged posterior intercostal arteries erode ribs", ["Pulmonary veins calcify ribs", "Azygos vein compresses rib heads", "Pleura thickens rib cortex"], "A chest X-ray in coarctation of aorta shows inferior rib notching. What is the mechanism?", "Collateral flow through enlarged posterior intercostal arteries erodes the inferior borders of ribs."),
    "anatomy-thorax-wall-thorax-15": u("Intercostal nerves are somatic nerves", ["Visceral pleura has no sensory supply", "Vagus nerve localizes sharp pain", "Pulmonary veins carry pain"], "Why can a patient localize pain precisely after a rib fracture or costal pleurisy?", "The thoracic wall and costal pleura are supplied by somatic intercostal nerves, producing localized pain."),

    "anatomy-thorax-thoracic-cavity-pleurae-11": u("Costodiaphragmatic recess", ["Oblique pericardial sinus", "Carina", "Aortic hiatus"], "An upright patient with pleural effusion has fluid layering at the lung base. Which anatomical space collects the fluid first?", "The costodiaphragmatic recess is the most dependent pleural recess in erect posture."),
    "anatomy-thorax-thoracic-cavity-pleurae-12": u("Phrenic nerve C3-C5", ["Intercostobrachial nerve", "Vagus nerve only", "Long thoracic nerve"], "A patient with diaphragmatic pleurisy complains of shoulder-tip pain. Which nerve pathway explains the referral?", "Central diaphragmatic pleura is supplied by phrenic nerve C3-C5, same spinal levels as shoulder skin."),
    "anatomy-thorax-thoracic-cavity-pleurae-13": u("Loss of negative intrapleural pressure", ["Collapse of pulmonary arteries", "Fusion of visceral and parietal pleura", "Closure of the trachea"], "After a penetrating chest wound, air enters the pleural cavity and the lung collapses. What is the immediate anatomical reason?", "Air in pleural cavity abolishes the negative pressure keeping visceral and parietal pleura apposed."),
    "anatomy-thorax-thoracic-cavity-pleurae-14": u("Intercostal nerves", ["Phrenic nerve", "Vagus nerve", "Recurrent laryngeal nerve"], "A patient with lateral costal pleuritis points exactly to the painful intercostal space. Which nerve carries this localized pain?", "Costal pleura is supplied by intercostal nerves, giving sharply localized somatic pain."),
    "anatomy-thorax-thoracic-cavity-pleurae-15": u("Needle placed too low may cross diaphragm into abdominal viscera", ["Pleura is absent below the second rib", "The lung always fills the entire recess", "The pericardium lies in the flank"], "Why is blind pleural aspiration dangerously low in the midaxillary line?", "Pleura descends below lung, but too low an entry may pass through diaphragm and injure liver/spleen or abdominal viscera."),

    "anatomy-thorax-lungs-11": u("Right main bronchus is wider, shorter and more vertical", ["Left main bronchus is wider and vertical", "Right lung has no fissures", "Left lung has an eparterial bronchus"], "An unconscious patient aspirates vomitus and later develops pneumonia in the right lower lobe. Which airway anatomy explains this?", "The right main bronchus is shorter, wider and more vertical, so aspirated material preferentially enters it."),
    "anatomy-thorax-lungs-12": u("Segmental bronchus and pulmonary artery with intersegmental veins", ["One common bronchus for entire lung", "No independent arterial supply", "Only visceral pleura separates segments"], "A surgeon removes one bronchopulmonary segment while preserving adjacent segments. Which anatomical arrangement permits this?", "Bronchopulmonary segments are discrete units supplied by segmental bronchi/arteries; veins lie intersegmentally."),
    "anatomy-thorax-lungs-13": u("Cervical sympathetic chain/stellate ganglion", ["Median nerve", "Intercostobrachial nerve only", "Phrenic nerve in pericardium"], "A superior sulcus tumor causes ptosis, miosis and anhidrosis. Which structure is invaded?", "Pancoast tumors at the lung apex can damage cervical sympathetic fibers causing Horner syndrome."),
    "anatomy-thorax-lungs-14": u("Lingula of left upper lobe", ["Right middle lobe", "Left lower lobe posterior basal segment", "Right lower lobe"], "On PA chest X-ray, loss of the left heart border but preserved left hemidiaphragm suggests consolidation in which part?", "The lingula contacts the left heart border; disease there produces silhouette sign of left cardiac border."),
    "anatomy-thorax-lungs-15": u("Pulmonary veins run intersegmentally", ["Pulmonary arteries run intersegmentally", "Bronchi run outside all segments", "Bronchial arteries define fissures"], "During segmentectomy, the surgeon follows veins in the planes between segments. Why?", "Pulmonary veins are intersegmental and mark surgical planes between bronchopulmonary segments."),

    "anatomy-thorax-mediastinum-11": u("Esophagus in posterior mediastinum", ["Trachea in anterior mediastinum", "Thymus in middle mediastinum", "Internal thoracic artery"], "A posterior mediastinal mass presents mainly with progressive dysphagia. Which compressed structure explains the symptom?", "The esophagus lies in posterior mediastinum and compression causes dysphagia."),
    "anatomy-thorax-mediastinum-12": u("Phrenic nerve", ["Vagus nerve", "Sympathetic trunk", "Intercostal nerve"], "After mediastinal lymph node surgery, the right hemidiaphragm is elevated and moves paradoxically. Which nerve was injured?", "Phrenic nerve supplies motor innervation to diaphragm and descends through mediastinum anterior to lung root."),
    "anatomy-thorax-mediastinum-13": u("Left recurrent laryngeal nerve", ["Right recurrent laryngeal nerve", "Phrenic nerve", "Greater splanchnic nerve"], "A patient with an aortic arch aneurysm develops hoarseness. Which nerve is most likely compressed?", "Left recurrent laryngeal nerve loops under the aortic arch near ligamentum arteriosum."),
    "anatomy-thorax-mediastinum-14": u("Rising pleural pressure pushes mediastinum and impairs venous return", ["Esophagus pulls the heart left", "Ribs contract actively", "Trachea expands equally"], "In tension pneumothorax, why can the patient rapidly become hypotensive?", "Pressure displaces mediastinum and compresses great veins, reducing venous return."),
    "anatomy-thorax-mediastinum-15": u("Transverse thoracic plane at sternal angle/T4-T5", ["Xiphisternal plane", "Thoracic outlet only", "Plane of first rib"], "A CT report describes a mass above the plane dividing superior and inferior mediastinum. Which anatomical plane is being used?", "The sternal angle to T4/T5 plane separates superior from inferior mediastinum."),

    "anatomy-thorax-pericardium-heart-11": u("Restricted ventricular filling due to pericardial pressure", ["Obstruction of the trachea", "Loss of lung surfactant", "Spasm of intercostal muscles"], "A trauma patient with Beck triad has blood accumulating in the pericardial sac. Why does cardiac output fall?", "Pericardial tamponade compresses the heart and prevents adequate diastolic filling."),
    "anatomy-thorax-pericardium-heart-12": u("Phrenic nerve supply to fibrous/parietal pericardium", ["Vagus supply to myocardium", "Intercostobrachial nerve", "Thoracic duct"], "A pericarditis patient feels pain at the shoulder tip. Which anatomical pathway best explains it?", "Fibrous and parietal serous pericardium receive sensory fibers from phrenic nerve C3-C5, referring pain to shoulder."),
    "anatomy-thorax-pericardium-heart-13": u("Right ventricle", ["Left atrium", "Coronary sinus", "Pulmonary veins"], "A stab wound immediately left of the sternum penetrates the anterior cardiac surface. Which chamber is most likely injured?", "Right ventricle forms most of the sternocostal/anterior surface of the heart."),
    "anatomy-thorax-pericardium-heart-14": u("Anterior two-thirds of interventricular septum", ["SA node always", "Posterior left atrial wall only", "Azygos arch"], "Occlusion of the LAD/anterior interventricular artery causes conduction problems due to septal ischemia. Which septal area is supplied?", "The anterior interventricular artery supplies anterior two-thirds of interventricular septum."),
    "anatomy-thorax-pericardium-heart-15": u("Between arterial and venous ends of heart", ["Behind sternum only", "Inside right atrium", "Between pleural layers"], "A surgeon passes a finger through the transverse pericardial sinus to clamp great arteries during cardiac surgery. Where is this sinus?", "The transverse sinus lies posterior to ascending aorta/pulmonary trunk and anterior to SVC/atria."),

    "anatomy-thorax-great-vessels-11": u("Superior vena cava obstruction", ["Inferior vena cava obstruction", "Portal vein thrombosis", "Femoral artery occlusion"], "A lung tumor compresses a large vein, causing facial swelling, distended neck veins and upper limb edema. What syndrome is this?", "SVC obstruction impairs venous drainage from head, neck, upper limbs and upper thorax."),
    "anatomy-thorax-great-vessels-12": u("Left recurrent laryngeal nerve", ["Right phrenic nerve", "Vagus trunk below diaphragm", "Intercostal nerve T6"], "Hoarseness develops in a patient with aneurysm of the aortic arch. Which nerve is stretched under the arch?", "Left recurrent laryngeal nerve loops beneath the aortic arch near ligamentum arteriosum."),
    "anatomy-thorax-great-vessels-13": u("Communication between aorta and pulmonary trunk", ["Communication between atria", "Communication between ventricles", "Communication between SVC and IVC"], "A continuous machinery murmur is diagnosed as patent ductus arteriosus. Which fetal channel failed to close?", "Ductus arteriosus connects pulmonary trunk/left pulmonary artery to aorta."),
    "anatomy-thorax-great-vessels-14": u("Collateral flow through posterior intercostal arteries", ["Flow through pulmonary veins", "Flow through coronary sinus", "Flow through thoracic duct"], "A child with postductal coarctation develops rib notching. Which collateral route enlarged?", "Collateral flow via internal thoracic/anterior intercostal to posterior intercostal arteries causes rib notching."),
    "anatomy-thorax-great-vessels-15": u("Right heart to pulmonary trunk", ["Left heart to aorta first", "Portal vein to liver first", "Coronary sinus to myocardium"], "A thrombus from deep veins of the leg lodges in the lung. What route must it take after entering the thorax?", "Venous emboli travel through IVC to right atrium, right ventricle, and pulmonary trunk/arteries."),

    "anatomy-thorax-trachea-oesophagus-thoracic-duct-11": u("Right main bronchus", ["Left main bronchus", "Esophagus", "Thoracic duct"], "A peanut aspirated by a child is seen at bronchoscopy entering the more vertical bronchus. Where is it most likely lodged?", "The right main bronchus is wider, shorter and more vertical."),
    "anatomy-thorax-trachea-oesophagus-thoracic-duct-12": u("Thoracic duct injury", ["Azygos vein injury", "Phrenic nerve injury", "Internal thoracic artery injury"], "After esophagectomy, a patient develops a milky pleural effusion that increases after fatty meals. Which structure was injured?", "Thoracic duct injury causes chylothorax because it transports chyle from intestinal lymphatics."),
    "anatomy-thorax-trachea-oesophagus-thoracic-duct-13": u("Left atrial enlargement compressing esophagus", ["Right ventricular enlargement compressing trachea", "SVC obstruction", "Aortic valve stenosis only"], "A patient with long-standing mitral stenosis develops dysphagia. Which anatomical relation explains it?", "The esophagus passes posterior to the left atrium, so left atrial enlargement may compress it."),
    "anatomy-thorax-trachea-oesophagus-thoracic-duct-14": u("Carina", ["Cricoid cartilage", "Epiglottis", "Vocal fold"], "During bronchoscopy, touching a structure at tracheal bifurcation triggers violent cough. Which structure is highly sensitive?", "The carina at tracheal bifurcation is highly sensitive and triggers cough reflex."),
    "anatomy-thorax-trachea-oesophagus-thoracic-duct-15": u("At the left venous angle", ["Into the right atrium", "Into azygos vein", "Into pulmonary trunk"], "A surgeon tracing the thoracic duct in the neck expects it to terminate where?", "Thoracic duct drains into the junction of left internal jugular and left subclavian veins."),

    "anatomy-thorax-surface-radiological-thorax-11": u("Left 5th intercostal space at or near midclavicular line", ["Right 2nd intercostal space", "Left 10th intercostal space posteriorly", "Epigastrium only"], "A patient with suspected cardiomegaly has the apex beat palpated down and out. Where is the normal apex beat expected?", "Normal apex beat is in the left fifth intercostal space near the midclavicular line."),
    "anatomy-thorax-surface-radiological-thorax-12": u("Pleural effusion in costodiaphragmatic recess", ["Scaphoid fracture", "Aortic valve calcification only", "Pneumonia in apex only"], "A chest X-ray shows blunting of the right costophrenic angle. What is the most anatomical explanation?", "Fluid in the costodiaphragmatic recess blunts the costophrenic angle."),
    "anatomy-thorax-surface-radiological-thorax-13": u("Lingula", ["Right lower lobe", "Azygos lobe", "Posterior basal segment only"], "A PA chest X-ray shows loss of the left heart border but the left hemidiaphragm remains visible. Which region is diseased?", "The lingula contacts the left heart border; opacity there obscures it by silhouette sign."),
    "anatomy-thorax-surface-radiological-thorax-14": u("Aortic injury", ["Carpal tunnel syndrome", "Appendicitis", "Scaphoid fracture"], "After high-speed deceleration trauma, chest X-ray shows widened mediastinum. Which life-threatening injury must be suspected?", "Widened mediastinum after blunt trauma suggests great vessel, especially aortic, injury."),
    "anatomy-thorax-surface-radiological-thorax-15": u("Enter pleural space just above rib to release trapped air", ["Enter pericardium below xiphoid", "Enter lung parenchyma deliberately", "Enter below the rib to find nerve"], "In tension pneumothorax, why is emergency needle decompression placed above the rib in an intercostal space?", "It must enter pleural space to release air while avoiding the neurovascular bundle under the rib."),
}


def main():
    data = json.loads(DATA.read_text(encoding="utf-8-sig"))
    found = set()
    for question in data.get("questions", []):
        item = UPDATES.get(question.get("id"))
        if not item:
            continue
        found.add(question["id"])
        options = list(item["wrong"])
        options.insert(question["answerIndex"], item["answer"])
        question["prompt"] = item["prompt"]
        question["answer"] = item["answer"]
        question["options"] = options
        question["explanation"] = item["explanation"]
        question["difficulty"] = "very high"
    missing = sorted(set(UPDATES) - found)
    if missing:
        raise AssertionError(f"Missing IDs: {missing}")
    qs = [q for q in data.get("questions", []) if q.get("subjectId") == "anatomy" and q.get("chapterTitle") == CHAPTER]
    if len(qs) != 150:
        raise AssertionError(f"Expected 150 Thorax questions, got {len(qs)}")
    if any(q["answer"] != q["options"][q["answerIndex"]] for q in qs):
        raise AssertionError("Bad answer index")
    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Upgraded {len(UPDATES)} Thorax last-five questions to stronger clinical/logic vignettes.")


if __name__ == "__main__":
    main()
