import json
from pathlib import Path

DATA = Path("runtime-data/users.json")
CHAPTER = "Abdomen"


def u(answer, wrong, prompt, explanation):
    return {"answer": answer, "wrong": wrong, "prompt": prompt, "explanation": explanation}


UPDATES = {
    "anatomy-abdomen-introduction-abdominal-wall-01": u("Transversus abdominis and internal oblique", ["External oblique and rectus femoris", "Psoas major and iliacus", "Serratus anterior and latissimus dorsi"], "During repair of a lower abdominal incision, the surgeon expects the deep muscular support to come mainly from which flat abdominal-wall layers?", "Internal oblique and transversus abdominis form the deeper dynamic support of the anterolateral abdominal wall."),
    "anatomy-abdomen-introduction-abdominal-wall-02": u("Inferior epigastric vessels", ["Femoral vein", "Portal vein", "Cystic artery"], "While differentiating direct and indirect inguinal hernia, which landmark tells whether the sac is medial or lateral?", "Direct hernias pass medial to inferior epigastric vessels; indirect hernias pass lateral through the deep ring."),
    "anatomy-abdomen-introduction-abdominal-wall-03": u("Linea alba", ["Linea semilunaris", "Inguinal ligament", "Rectus muscle belly"], "A surgeon wants a midline laparotomy with minimal muscle cutting and relatively low bleeding. Which structure is intentionally opened?", "The linea alba is a tendinous midline raphe with few major vessels and no muscle belly."),
    "anatomy-abdomen-introduction-abdominal-wall-04": u("External oblique aponeurosis", ["Transversalis fascia", "Parietal peritoneum", "Internal oblique muscle"], "At the end of the inguinal canal, the spermatic cord emerges through a slit above the pubic tubercle. Which layer forms this opening?", "The superficial inguinal ring is an opening in external oblique aponeurosis."),
    "anatomy-abdomen-introduction-abdominal-wall-05": u("Transversalis fascia", ["External oblique aponeurosis", "Scarpa fascia", "Rectus sheath anterior layer"], "An indirect inguinal hernia first enters the canal through the deep inguinal ring. Which layer is pierced at this point?", "The deep ring is an opening in transversalis fascia, lateral to inferior epigastric vessels."),
    "anatomy-abdomen-introduction-abdominal-wall-06": u("Ilioinguinal nerve", ["Femoral nerve", "Obturator nerve", "Tibial nerve"], "After open inguinal hernia repair, a patient has numbness over the upper medial thigh and anterior scrotum. Which nerve was likely injured?", "Ilioinguinal nerve traverses part of the canal and supplies upper medial thigh and anterior scrotum/labium."),
    "anatomy-abdomen-introduction-abdominal-wall-07": u("Conjoint tendon", ["Lacunar ligament", "Pectineal ligament", "Round ligament of liver"], "A direct inguinal hernia pushes through the posterior wall of the canal near the medial end. Which reinforcement normally resists it?", "The conjoint tendon reinforces the medial posterior wall of the inguinal canal."),
    "anatomy-abdomen-introduction-abdominal-wall-08": u("Scarpa fascia", ["Camper fascia", "Transversalis fascia", "Endoabdominal fascia only"], "Urine from a ruptured spongy urethra tracks into the lower anterior abdominal wall but not the thigh. Which fascial plane guides it?", "Membranous Scarpa fascia is continuous with superficial perineal fascia and attaches to fascia lata below the inguinal ligament."),
    "anatomy-abdomen-introduction-abdominal-wall-09": u("Above and medial to pubic tubercle", ["Below and lateral to pubic tubercle", "Behind medial malleolus", "At the femoral pulse only"], "On examination, where would an inguinal hernia swelling classically appear relative to the pubic tubercle?", "Inguinal hernias present above and medial to the pubic tubercle; femoral hernias are below and lateral."),
    "anatomy-abdomen-introduction-abdominal-wall-10": u("Rectus sheath below arcuate line lacks posterior aponeurotic wall", ["Rectus muscle disappears below umbilicus", "External oblique becomes retroperitoneal", "Linea alba contains portal vein"], "Why is a lower rectus sheath incision more vulnerable posteriorly than one above the arcuate line?", "Below the arcuate line, all three flat-muscle aponeuroses pass anterior to rectus, leaving only transversalis fascia posteriorly."),

    "anatomy-abdomen-peritoneum-mesentery-01": u("Epiploic foramen", ["Aortic hiatus", "Deep inguinal ring", "Duodenojejunal flexure"], "A surgeon enters the lesser sac from the greater sac by passing a finger behind the free edge of lesser omentum. Which opening is used?", "The epiploic foramen connects greater and lesser sacs behind the hepatoduodenal ligament."),
    "anatomy-abdomen-peritoneum-mesentery-02": u("Portal vein, hepatic artery proper and bile duct", ["Aorta, IVC and thoracic duct", "Splenic artery, renal vein and ureter", "SMA, SMV and appendix"], "In a Pringle maneuver, clamping the hepatoduodenal ligament controls inflow through which set of structures?", "The free edge of lesser omentum contains the portal triad: portal vein, hepatic artery and bile duct."),
    "anatomy-abdomen-peritoneum-mesentery-03": u("Greater omentum", ["Falciform ligament", "Mesentery of appendix", "Coronary ligament"], "An inflamed appendix becomes walled off by a mobile fatty peritoneal fold descending from the stomach. What is this fold?", "The greater omentum can migrate to inflamed areas and help localize infection."),
    "anatomy-abdomen-peritoneum-mesentery-04": u("Hepatorenal recess", ["Rectouterine pouch", "Lesser sac", "Left paracolic gutter"], "In a supine trauma patient, free intraperitoneal blood commonly collects between liver and right kidney. Which recess is examined on FAST scan?", "The hepatorenal pouch of Morrison is a dependent recess in supine patients."),
    "anatomy-abdomen-peritoneum-mesentery-05": u("Transverse mesocolon", ["Falciform ligament", "Mesentery proper", "Median umbilical fold"], "A surgeon lifts the stomach and enters a peritoneal fold attached to the transverse colon. Which structure is being handled?", "The transverse mesocolon attaches the transverse colon to the posterior abdominal wall and relates to stomach/lesser sac surgery."),
    "anatomy-abdomen-peritoneum-mesentery-06": u("Root of mesentery crosses duodenum, aorta, IVC and right ureter", ["It attaches only to spleen", "It lies completely in pelvis", "It is an opening in external oblique"], "Why can mesenteric root disease affect several posterior abdominal-wall structures?", "The oblique root of mesentery crosses major vessels and retroperitoneal organs from DJ flexure to ileocecal region."),
    "anatomy-abdomen-peritoneum-mesentery-07": u("Right paracolic gutter", ["Left inguinal canal", "Femoral canal", "Rectus sheath"], "Pus from an infected appendix tracks superiorly toward the subhepatic space. Which pathway allows this spread?", "The right paracolic gutter provides a route between right iliac fossa and subhepatic spaces."),
    "anatomy-abdomen-peritoneum-mesentery-08": u("Retroperitoneal duodenum or pancreas", ["Jejunum suspended by mesentery", "Spleen in dorsal mesogastrium", "Transverse colon"], "A blunt abdominal injury produces retroperitoneal air rather than free intraperitoneal gas. Injury to which organ group fits best?", "Secondarily retroperitoneal structures such as most duodenum and pancreas can leak into retroperitoneum."),
    "anatomy-abdomen-peritoneum-mesentery-09": u("Visceral afferents from midgut enter around T10", ["Parietal peritoneum is supplied by phrenic nerve only", "Appendix has no nerves", "Somatic nerves refer to epigastrium"], "Early appendicitis produces vague periumbilical pain before local tenderness appears. What explains the first pain site?", "Appendix is midgut; visceral pain follows T10 afferents to the umbilical dermatome."),
    "anatomy-abdomen-peritoneum-mesentery-10": u("Lesser sac", ["Greater sac only", "Rectovesical pouch", "Subcutaneous tissue"], "A posterior gastric perforation initially leaks into a peritoneal space behind the stomach. Which space is involved?", "The lesser sac lies posterior to stomach and anterior to pancreas."),

    "anatomy-abdomen-stomach-duodenum-01": u("Right and left gastric arteries", ["Right and left colic arteries", "Cystic and hepatic arteries", "Renal and suprarenal arteries"], "A gastric ulcer on the lesser curvature bleeds from the arterial arcade running along that border. Which arteries form it?", "Right and left gastric arteries anastomose along the lesser curvature."),
    "anatomy-abdomen-stomach-duodenum-02": u("Right and left gastro-omental arteries", ["Superior and inferior pancreaticoduodenal arteries", "Sigmoid arteries", "Lumbar arteries"], "During mobilization of the greater curvature, which paired vessels must be preserved or ligated deliberately?", "The right and left gastro-omental arteries run along the greater curvature."),
    "anatomy-abdomen-stomach-duodenum-03": u("Gastroduodenal artery", ["Splenic vein", "Inferior mesenteric artery", "Left renal artery"], "A posterior ulcer in the first part of duodenum causes massive upper GI bleeding. Which structure lies directly behind it?", "The gastroduodenal artery is posterior to the first part of duodenum."),
    "anatomy-abdomen-stomach-duodenum-04": u("Superior mesenteric artery compressing the third part of duodenum", ["Cystic duct blocking the pylorus", "Splenic artery compressing fundus", "Inferior epigastric artery entering stomach"], "A thin patient develops vomiting from vascular compression of the horizontal duodenum. Which relation explains SMA syndrome?", "The third part of duodenum crosses between SMA anteriorly and aorta posteriorly."),
    "anatomy-abdomen-stomach-duodenum-05": u("Major duodenal papilla in second part of duodenum", ["Pylorus", "Cardiac orifice", "Ileocecal valve"], "Endoscopy shows a stone blocking the common opening of bile and pancreatic ducts. Where is the obstruction?", "The hepatopancreatic ampulla opens on the major duodenal papilla in the second part of duodenum."),
    "anatomy-abdomen-stomach-duodenum-06": u("Ligament of Treitz at duodenojejunal flexure", ["Falciform ligament at umbilicus", "Gastrosplenic ligament at fundus", "Lacunar ligament at groin"], "A radiologist uses the position of the duodenojejunal flexure to exclude malrotation. Which suspensory structure marks it?", "The suspensory muscle of duodenum, or ligament of Treitz, supports the duodenojejunal flexure."),
    "anatomy-abdomen-stomach-duodenum-07": u("Left gastric and short gastric vessels", ["Ileocolic and appendicular vessels", "Inferior epigastric vessels", "Obturator vessels"], "Portal hypertension can produce varices near the cardia and fundus. Which gastric venous territories are most relevant?", "Left gastric and short gastric venous routes connect portal flow to esophageal/systemic channels."),
    "anatomy-abdomen-stomach-duodenum-08": u("Pancreas", ["Urinary bladder", "Cecum", "Femoral canal"], "A posterior gastric ulcer penetrates a retroperitoneal organ and causes deep back pain. Which organ is most likely involved?", "The pancreas forms a major part of the stomach bed."),
    "anatomy-abdomen-stomach-duodenum-09": u("Right vagus forms posterior trunk; left vagus forms anterior trunk", ["Both vagi become phrenic nerves", "Right vagus supplies only kidney", "Left vagus becomes portal vein"], "After esophageal rotation during development, which vagal arrangement is expected at the stomach?", "The left vagus becomes anterior vagal trunk and right vagus becomes posterior vagal trunk."),
    "anatomy-abdomen-stomach-duodenum-10": u("Pyloric sphincter hypertrophy", ["Appendix torsion", "Splenic rupture", "Femoral hernia"], "A 4-week-old infant has projectile non-bilious vomiting and a palpable olive in epigastrium. Which anatomical narrowing is diseased?", "Hypertrophy of pyloric circular muscle obstructs gastric outflow before bile enters."),

    "anatomy-abdomen-small-large-intestine-01": u("Jejunal arcades are fewer with longer vasa recta", ["Jejunum has taeniae coli", "Ileum lacks mesentery", "Jejunum has appendices epiploicae"], "A surgeon distinguishes jejunum from ileum by looking at mesenteric vessels. Which pattern favors jejunum?", "Jejunum has fewer arterial arcades and longer vasa recta than ileum."),
    "anatomy-abdomen-small-large-intestine-02": u("Peyer's patches in ileum", ["Gastric rugae", "Colonic haustra only", "Duodenal papilla"], "During ileal resection, the pathologist notes prominent aggregated lymphoid follicles. What are these?", "Peyer's patches are characteristic lymphoid aggregates of ileum."),
    "anatomy-abdomen-small-large-intestine-03": u("Taeniae coli converge at the base of appendix", ["Plicae circulares end at pylorus", "Villi point to appendix", "Omental apron inserts on appendix"], "In difficult appendicectomy, what surface feature of cecum guides the surgeon to the appendicular base?", "The three taeniae coli converge at the base of appendix."),
    "anatomy-abdomen-small-large-intestine-04": u("Retrocecal position", ["Pre-gastric position", "Intrasplenic position", "Femoral canal position"], "A patient has appendicitis but less marked anterior abdominal guarding because the appendix lies behind the cecum. Which position explains this?", "A retrocecal appendix may produce atypical signs because it is partly shielded from anterior parietal peritoneum."),
    "anatomy-abdomen-small-large-intestine-05": u("Marginal artery of Drummond", ["Circle of Willis", "Palmar arch", "Trochanteric anastomosis"], "After left colectomy, collateral flow along the colon depends on an arterial arcade near the mesenteric border. What is it?", "The marginal artery links colic branches along the colon."),
    "anatomy-abdomen-small-large-intestine-06": u("Superior and inferior mesenteric artery territories", ["Celiac and hepatic territories", "Renal and gonadal territories", "Internal and external iliac territories"], "Ischemia at the splenic flexure is clinically important because it is a watershed between which arterial systems?", "The splenic flexure lies near the SMA-IMA watershed."),
    "anatomy-abdomen-small-large-intestine-07": u("Antimesenteric border of ileum", ["Mesenteric border of jejunum", "Greater curvature of stomach", "Base of cecum"], "A Meckel diverticulum is found during surgery. Where is it classically located?", "Meckel diverticulum lies on the antimesenteric border of ileum."),
    "anatomy-abdomen-small-large-intestine-08": u("Vitellointestinal duct", ["Urachus", "Ductus venosus", "Processus vaginalis"], "A child has painless bleeding from ectopic gastric mucosa in a Meckel diverticulum. Which embryonic duct persisted?", "Meckel diverticulum is a remnant of the vitellointestinal duct."),
    "anatomy-abdomen-small-large-intestine-09": u("Sigmoid mesocolon", ["Transverse mesocolon only", "Mesoappendix", "Falciform ligament"], "A volvulus twists a mobile loop of distal colon around its mesentery. Which mesentery is usually involved?", "Sigmoid volvulus occurs because the sigmoid colon has a long mobile mesocolon."),
    "anatomy-abdomen-small-large-intestine-10": u("Appendicular artery in the mesoappendix", ["Cystic artery in Calot triangle", "Left gastric artery", "Inferior epigastric artery"], "During appendicectomy, bleeding from the small peritoneal fold to the appendix is controlled. Which artery is ligated?", "The appendicular artery runs in the mesoappendix."),

    "anatomy-abdomen-liver-gallbladder-biliary-01": u("Portal vein", ["Hepatic vein", "Inferior vena cava", "Cystic duct"], "At the porta hepatis, which portal triad structure usually lies posterior to the hepatic artery and bile duct?", "The portal vein is the posterior member of the portal triad."),
    "anatomy-abdomen-liver-gallbladder-biliary-02": u("Right hepatic artery", ["Left gastric artery", "Splenic artery", "Superior mesenteric artery"], "During cholecystectomy, the cystic artery is traced in the hepatocystic triangle. What is its usual source?", "The cystic artery most commonly arises from the right hepatic artery."),
    "anatomy-abdomen-liver-gallbladder-biliary-03": u("Cystic duct obstruction", ["Portal vein thrombosis only", "Left gastric artery spasm", "Ureteric stone"], "A patient has colicky right upper quadrant pain after fatty meals but no jaundice. Which blockage best fits?", "A stone in the cystic duct obstructs gallbladder emptying without necessarily blocking the common bile duct."),
    "anatomy-abdomen-liver-gallbladder-biliary-04": u("Common bile duct obstruction", ["Cystic artery ligation", "Appendicular artery blockage", "Left renal vein compression"], "A stone in the distal bile duct causes pale stools, dark urine and jaundice. Which duct is obstructed?", "Common bile duct obstruction prevents bile pigments reaching the intestine."),
    "anatomy-abdomen-liver-gallbladder-biliary-05": u("Paraumbilical veins", ["Short saphenous veins", "Pulmonary veins", "Dorsal venous arch"], "A cirrhotic patient develops dilated veins radiating from the umbilicus. Which portal-systemic channel reopened?", "Paraumbilical veins connect the portal system to superficial abdominal wall veins."),
    "anatomy-abdomen-liver-gallbladder-biliary-06": u("Left gastric to esophageal veins", ["Cystic to renal veins", "Portal to femoral veins", "Hepatic to popliteal veins"], "Hematemesis in portal hypertension often comes from varices at the lower esophagus. Which venous connection is responsible?", "Left gastric portal tributaries anastomose with systemic esophageal veins."),
    "anatomy-abdomen-liver-gallbladder-biliary-07": u("Hepatic veins draining directly to IVC", ["Portal vein draining to spleen", "Bile duct draining to kidney", "Cystic duct draining to stomach"], "At the bare area of liver, which large venous drainage pathway is closely related posteriorly?", "Hepatic veins leave the liver posteriorly to enter the IVC."),
    "anatomy-abdomen-liver-gallbladder-biliary-08": u("Second part of duodenum", ["First part of jejunum", "Cecum", "Sigmoid colon"], "A stone blocks the hepatopancreatic ampulla. Into which gut segment should bile normally enter?", "Bile enters the descending second part of duodenum through the major papilla."),
    "anatomy-abdomen-liver-gallbladder-biliary-09": u("Right shoulder via phrenic nerve C3-C5", ["Left little finger via ulnar nerve", "Medial thigh via obturator nerve", "Dorsum foot via L5 only"], "Acute cholecystitis irritates the diaphragm and pain is felt at the shoulder tip. What is the referral pathway?", "Diaphragmatic peritoneum is supplied by phrenic nerve, referring pain to C3-C5 shoulder region."),
    "anatomy-abdomen-liver-gallbladder-biliary-10": u("Segmental portal triad distribution within liver", ["Single artery supplies all segments without branches", "Liver has no venous drainage", "Bile flows only through hepatic veins"], "Why can surgeons perform anatomical segmental liver resections?", "Functional liver segments have their own portal triad inflow and biliary drainage."),

    "anatomy-abdomen-pancreas-spleen-01": u("Common bile duct passes through/behind pancreatic head", ["Portal vein opens into pancreatic duct", "Splenic artery drains bile", "Cystic duct crosses splenic hilum"], "A carcinoma in the head of pancreas produces painless obstructive jaundice. Which relation explains this?", "The common bile duct is closely related to the pancreatic head and can be compressed by tumors."),
    "anatomy-abdomen-pancreas-spleen-02": u("Splenic artery", ["Inferior mesenteric artery", "Cystic artery", "Inferior epigastric artery"], "A posterior gastric ulcer erodes a tortuous artery along the upper border of pancreas. Which artery bleeds?", "The splenic artery runs along the superior border of pancreas behind the stomach."),
    "anatomy-abdomen-pancreas-spleen-03": u("Tail of pancreas", ["Appendix", "Gallbladder", "Right adrenal gland"], "During splenectomy, the surgeon stays close to the splenic capsule to avoid damaging which structure at the hilum?", "The tail of pancreas reaches the splenic hilum in the splenorenal ligament."),
    "anatomy-abdomen-pancreas-spleen-04": u("Left shoulder pain from phrenic irritation", ["Right foot drop", "Umbilical discharge", "Medial thigh numbness"], "After splenic rupture, blood under the left hemidiaphragm produces Kehr sign. What symptom is expected?", "Diaphragmatic irritation refers pain via phrenic nerve to the shoulder."),
    "anatomy-abdomen-pancreas-spleen-05": u("Ribs 9 to 11", ["Ribs 1 to 3", "Rib 12 only", "Clavicle and first rib"], "A left lower rib fracture is monitored for splenic injury. Which ribs normally protect the spleen?", "The spleen lies deep to ribs 9-11 with its long axis along the 10th rib."),
    "anatomy-abdomen-pancreas-spleen-06": u("Dorsal mesogastrium", ["Ventral mesentery", "Urachus", "Septum transversum only"], "Accessory spleens near the hilum reflect the embryological origin of spleen in which peritoneal fold?", "The spleen develops in the dorsal mesogastrium."),
    "anatomy-abdomen-pancreas-spleen-07": u("Splenorenal ligament", ["Falciform ligament", "Lacunar ligament", "Median umbilical ligament"], "Which peritoneal ligament carries splenic vessels and the pancreatic tail to the spleen?", "The splenorenal ligament contains splenic vessels and pancreatic tail."),
    "anatomy-abdomen-pancreas-spleen-08": u("Main pancreatic duct and common bile duct", ["Portal vein and hepatic vein", "Splenic vein and left renal vein", "Cystic artery and cystic duct"], "A stone at the ampulla causes both pancreatitis and jaundice because it blocks which paired ducts?", "The main pancreatic duct and CBD usually join to form the hepatopancreatic ampulla."),
    "anatomy-abdomen-pancreas-spleen-09": u("Splenic vein posterior to pancreas", ["Femoral vein in thigh", "Azygos vein in thorax", "Great saphenous vein"], "Pancreatitis can cause thrombosis of a vein running behind the pancreas and lead to gastric varices. Which vein is this?", "The splenic vein courses posterior to the pancreas."),
    "anatomy-abdomen-pancreas-spleen-10": u("Pancreas is retroperitoneal, so inflammation tracks to the back", ["Pancreas lies in scrotum", "Spleen has no capsule", "Duodenum is subcutaneous"], "Acute pancreatitis often causes severe epigastric pain radiating to the back. Which anatomical fact explains this?", "The pancreas lies retroperitoneally against the posterior abdominal wall."),

    "anatomy-abdomen-kidneys-suprarenals-ureters-01": u("Renal vein, renal artery, renal pelvis", ["Renal artery, renal vein, renal pelvis", "Renal pelvis, renal artery, renal vein", "Ureter, renal pelvis, renal vein"], "At the renal hilum, a mass compresses the most anterior structure first. What is the anterior-to-posterior order?", "The hilar order is VAP: vein, artery, pelvis."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-02": u("Liver depresses the right kidney", ["Spleen pulls left kidney down", "Right kidney has no suprarenal gland", "Aorta pushes left kidney into pelvis"], "On imaging, the right kidney lies slightly lower than the left. What is the main anatomical reason?", "The large liver occupies the right upper abdomen and pushes the right kidney lower."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-03": u("Between superior mesenteric artery and aorta", ["Between femoral artery and vein", "Inside inguinal canal", "Behind urinary bladder"], "A patient has nutcracker syndrome involving the left renal vein. Where is the vein compressed?", "The left renal vein crosses anterior to aorta and posterior to SMA."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-04": u("Pelviureteric junction, pelvic brim, ureterovesical junction", ["Hilum, porta hepatis, pylorus", "Cardia, fundus, pylorus", "Cecum, appendix, sigmoid"], "A ureteric stone is likely to lodge at one of three normal narrowings. Which set is correct?", "The ureter narrows at PUJ, crossing of iliac vessels/pelvic brim, and UVJ."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-05": u("T11-L2 visceral afferents", ["C3-C5 phrenic afferents", "S2-S4 parasympathetics only", "C8-T1 brachial plexus"], "Renal colic radiates from loin to groin instead of staying at the flank. Which segmental pathway explains it?", "Ureteric pain follows sympathetic afferents to T11-L2, referring along groin/genital territories."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-06": u("Right suprarenal vein drains directly to IVC", ["Right suprarenal vein drains to portal vein", "Left suprarenal vein drains to cecum", "Both drain to splenic artery"], "Why is bleeding from the right suprarenal vein especially risky during adrenal surgery?", "The right suprarenal vein is short and drains directly into the IVC."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-07": u("Ureter passes under uterine artery", ["Ureter passes above uterine artery", "Ureter passes through ovary", "Uterine artery is inside ureter"], "During hysterectomy, the ureter is protected by remembering 'water under the bridge'. What does this mean?", "The ureter passes inferior to the uterine artery near the cervix."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-08": u("Renal fascia and perinephric fat", ["Rectus sheath", "Pleura only", "Femoral sheath"], "A kidney remains relatively fixed despite respiration and body movement. Which covering contributes to this support?", "Renal fascia and perinephric fat help hold kidney in position."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-09": u("12th rib, diaphragm and pleura", ["Clavicle and first rib", "Patella and femur", "Scapula and humerus"], "A posterior stab wound near the 12th rib may injure kidney and pleura. Which relation explains the risk?", "The upper posterior kidney is related to diaphragm and costodiaphragmatic pleura near the 12th rib."),
    "anatomy-abdomen-kidneys-suprarenals-ureters-10": u("Left gonadal vein", ["Right gonadal vein", "Cystic vein", "Great saphenous vein"], "Left-sided varicocele is more common partly because which vein drains into the left renal vein?", "The left gonadal vein drains into the left renal vein, which may have higher pressure or compression."),

    "anatomy-abdomen-posterior-wall-vessels-nerves-01": u("Celiac trunk", ["Superior mesenteric artery", "Inferior mesenteric artery", "Internal iliac artery"], "Pain and ischemia involving stomach, liver and spleen point to disease of which unpaired anterior aortic branch?", "The celiac trunk supplies foregut derivatives including stomach, liver and spleen."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-02": u("Superior mesenteric artery", ["Celiac trunk", "Inferior mesenteric artery", "Renal artery"], "Midgut volvulus twists around the vascular axis to jejunum, ileum and proximal colon. Which artery forms this axis?", "The SMA supplies midgut and forms the axis of midgut rotation."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-03": u("Inferior mesenteric artery", ["Celiac trunk", "Superior mesenteric artery", "Hepatic artery proper"], "Ischemia from distal transverse colon to upper anal canal implicates which unpaired aortic branch?", "The IMA supplies hindgut structures."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-04": u("Common iliac arteries at L4", ["Renal arteries at S3", "Femoral arteries at T12", "Hepatic arteries at C6"], "A pulsatile aneurysm at the aortic bifurcation is described at the level of the umbilicus. Into what does the aorta divide?", "The abdominal aorta bifurcates into common iliac arteries at L4."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-05": u("Femoral nerve", ["Obturator nerve", "Sciatic nerve", "Pudendal nerve"], "A psoas abscess affects a nerve emerging from the lateral border of psoas and weakens knee extension. Which nerve is involved?", "Femoral nerve emerges lateral to psoas major and supplies quadriceps."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-06": u("Obturator nerve", ["Femoral nerve", "Iliohypogastric nerve", "Subcostal nerve"], "A pelvic mass compresses a nerve emerging from the medial border of psoas, causing weak thigh adduction. Which nerve is affected?", "Obturator nerve emerges medial to psoas and supplies thigh adductors."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-07": u("Genitofemoral nerve", ["Femoral nerve", "Obturator nerve", "Tibial nerve"], "A nerve seen running on the anterior surface of psoas major is irritated, causing groin and genital sensory symptoms. Which nerve is this?", "Genitofemoral nerve descends on the anterior surface of psoas major."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-08": u("Sympathetic fibers via lumbar splanchnic pathways", ["Facial nerve fibers", "Median nerve fibers", "Phrenic motor fibers only"], "Pain from abdominal vascular disease may follow autonomic plexuses around the aorta. Which fiber system carries much of this visceral pain?", "Visceral pain from abdominal organs travels with sympathetic afferents through prevertebral plexuses and splanchnic nerves."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-09": u("Psoas major", ["Rectus abdominis", "Gluteus maximus", "Soleus"], "A patient with appendicitis has pain on passive extension of the right hip. Irritation of which posterior abdominal-wall muscle explains the psoas sign?", "A retrocecal inflamed appendix may irritate psoas major."),
    "anatomy-abdomen-posterior-wall-vessels-nerves-10": u("IVC lies to the right of the aorta", ["IVC lies in inguinal canal", "Aorta lies inside stomach", "Both vessels lie anterior to rectus muscle"], "During para-aortic lymph node dissection, why must the surgeon distinguish the large vessel immediately right of the aorta?", "The inferior vena cava ascends on the right side of the abdominal aorta."),

    "anatomy-abdomen-diaphragm-surface-clinical-01": u("IVC at T8, esophagus at T10, aorta at T12", ["Aorta at T8, IVC at T10, esophagus at T12", "Esophagus at L4, aorta at S1, IVC at C6", "All pass through T10"], "A viva asks for the classic diaphragm openings. Which level sequence is correct?", "Mnemonic: I 8, 10 Eggs, At 12 for IVC T8, esophagus T10, aorta T12."),
    "anatomy-abdomen-diaphragm-surface-clinical-02": u("Phrenic nerve C3-C5", ["Vagus nerve only", "Subcostal nerve only", "Femoral nerve"], "A subphrenic abscess produces shoulder-tip pain. Which nerve carries the referred pain pathway?", "Central diaphragmatic peritoneum is supplied by phrenic nerve C3-C5."),
    "anatomy-abdomen-diaphragm-surface-clinical-03": u("Gallbladder fundus", ["Appendix base", "Spleen hilum", "Pylorus only"], "Tenderness at the point where the right midclavicular line meets the costal margin suggests disease of which structure?", "The fundus of gallbladder is marked at the right 9th costal cartilage/costal margin near midclavicular line."),
    "anatomy-abdomen-diaphragm-surface-clinical-04": u("Base of appendix", ["Fundus of stomach", "Head of pancreas", "Left kidney hilum"], "McBurney point lies one-third of the way from right ASIS to umbilicus. What structure does it approximate?", "McBurney point overlies the base of appendix."),
    "anatomy-abdomen-diaphragm-surface-clinical-05": u("L1 transpyloric plane", ["T4 sternal angle plane", "L5 transtubercular plane", "S3 pelvic plane"], "A CT report describes the pylorus, pancreatic neck and renal hila near the same horizontal plane. Which plane is this?", "The transpyloric plane at L1 crosses several upper abdominal landmarks."),
    "anatomy-abdomen-diaphragm-surface-clinical-06": u("L3 subcostal plane", ["T8 caval plane", "C6 cricoid plane", "S2 sacral plane"], "The lowest points of the costal margin define a named abdominal plane. Which vertebral level is classically used?", "The subcostal plane passes through the inferior border of the 10th costal cartilage, around L3."),
    "anatomy-abdomen-diaphragm-surface-clinical-07": u("L5 transtubercular plane", ["T12 aortic plane", "T10 esophageal plane", "C7 vertebral plane"], "A surface anatomy question uses the iliac tubercles to draw a lower abdominal plane. What level is expected?", "The transtubercular plane passes through iliac tubercles and L5."),
    "anatomy-abdomen-diaphragm-surface-clinical-08": u("Parietal peritoneum", ["Visceral peritoneum only", "Gastric mucosa", "Renal medulla"], "Rebound tenderness localizes sharply in the right iliac fossa. Which pain-sensitive layer is irritated?", "Parietal peritoneum has somatic innervation and produces localized tenderness."),
    "anatomy-abdomen-diaphragm-surface-clinical-09": u("Murphy sign", ["Kehr sign", "Rovsing sign", "Tinel sign"], "A patient stops inspiration when the examiner palpates under the right costal margin. Which named sign is positive?", "Murphy sign suggests inflamed gallbladder contacting the examiner's hand during inspiration."),
    "anatomy-abdomen-diaphragm-surface-clinical-10": u("Right lower quadrant pain due to peritoneal irritation from appendicitis", ["Left shoulder pain from splenic rupture", "Groin pain from ureteric stone", "Foot drop from fibular nerve injury"], "Deep palpation of the left iliac fossa causes pain in the right iliac fossa. What does Rovsing sign suggest?", "Rovsing sign supports appendicitis due to peritoneal irritation transmitted to the right iliac fossa."),
}


def main():
    data = json.loads(DATA.read_text(encoding="utf-8-sig"))
    found = set()
    for question in data.get("questions", []):
        item = UPDATES.get(question.get("id"))
        if not item:
            continue
        found.add(question["id"])
        options = list(item["wrong"])
        options.insert(question["answerIndex"], item["answer"])
        question["prompt"] = item["prompt"]
        question["answer"] = item["answer"]
        question["options"] = options
        question["explanation"] = item["explanation"]
        question["difficulty"] = "high" if question["id"].endswith(("-06", "-07", "-08", "-09", "-10")) else "moderate"

    missing = sorted(set(UPDATES) - found)
    if missing:
        raise AssertionError(f"Missing IDs: {missing}")

    qs = [q for q in data.get("questions", []) if q.get("subjectId") == "anatomy" and q.get("chapterTitle") == CHAPTER]
    if len(qs) != 135:
        raise AssertionError(f"Expected 135 Abdomen questions, got {len(qs)}")
    if any(q["answer"] != q["options"][q["answerIndex"]] for q in qs):
        raise AssertionError("Bad answer index")

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Upgraded {len(UPDATES)} Abdomen first-ten questions.")


if __name__ == "__main__":
    main()
