import json
from pathlib import Path

DATA = Path("runtime-data/users.json")
CHAPTER = "Upper Limb"


def u(answer, wrong, prompt, explanation):
    return {"answer": answer, "wrong": wrong, "prompt": prompt, "explanation": explanation}


UPDATES = {
    "anatomy-upper-limb-introduction-11": u("C6 root/radial-side pattern", ["C8 root/ulnar-side pattern", "T4 intercostal pattern", "L5 root pattern"], "A patient has sensory loss over the thumb and lateral forearm after a neck injury. Which developmental/anatomical logic best localizes the deficit?", "The radial/thumb side is preaxial and commonly maps to C6; clinical sensory loss here suggests C6 involvement."),
    "anatomy-upper-limb-introduction-12": u("Sternoclavicular joint", ["Acromioclavicular joint", "Glenohumeral joint", "Scapulothoracic articulation"], "A fall drives the shoulder medially, but the force reaches the axial skeleton through only one true bony joint. Which joint is the critical link?", "The sternoclavicular joint is the only true bony articulation connecting the upper limb to the axial skeleton."),
    "anatomy-upper-limb-introduction-13": u("Mobility is prioritized over stability", ["Weight bearing is prioritized over manipulation", "The limb is fixed to the trunk", "The thumb is postaxial"], "Why are shoulder dislocations much more common than hip dislocations despite both being ball-and-socket joints?", "The upper limb is designed for mobility and reach, while the lower limb sacrifices mobility for weight-bearing stability."),
    "anatomy-upper-limb-introduction-14": u("Radioulnar joints", ["Elbow humeroulnar joint only", "Wrist radiocarpal joint", "Intercarpal joints"], "A patient can flex and extend the elbow but cannot turn a key because pronation-supination is painful. Which joints are primarily involved?", "Pronation and supination occur at proximal and distal radioulnar joints, not the hinge component of the elbow."),
    "anatomy-upper-limb-introduction-15": u("Loss of opposition", ["Loss of elbow extension", "Loss of shoulder shrug", "Loss of scapular retraction"], "A laceration damages the recurrent motor branch of the median nerve. Which functional loss most directly explains inability to pick up a pin?", "Precision grip depends heavily on thumb opposition, supplied mainly by median-innervated thenar muscles."),

    "anatomy-upper-limb-bones-upper-limb-11": u("Proximal scaphoid avascular necrosis", ["Distal radius malunion", "Olecranon bursitis", "Capitate dislocation only"], "A young adult has snuffbox tenderness after a fall. Initial X-ray is subtle, but untreated injury later causes wrist pain from loss of blood supply. What complication is most expected?", "Scaphoid blood supply is largely retrograde, so fracture through the waist can devascularize the proximal fragment."),
    "anatomy-upper-limb-bones-upper-limb-12": u("Radial nerve in spiral groove", ["Axillary nerve at surgical neck", "Median nerve in carpal tunnel", "Ulnar nerve in Guyon's canal"], "After a midshaft humeral fracture, the patient develops wrist drop but deltoid function is normal. Which structure was most likely injured?", "The radial nerve winds in the spiral groove of the humeral shaft and supplies wrist extensors."),
    "anatomy-upper-limb-bones-upper-limb-13": u("Axillary nerve", ["Radial nerve", "Median nerve", "Ulnar nerve"], "A fracture through the surgical neck of humerus causes flattened shoulder contour and numbness over the regimental badge area. Which nerve is injured?", "Axillary nerve winds around the surgical neck with posterior circumflex humeral vessels."),
    "anatomy-upper-limb-bones-upper-limb-14": u("Medial epicondyle", ["Lateral epicondyle", "Radial tuberosity", "Deltoid tuberosity"], "A child hits the inner side of the elbow and feels tingling in the little finger and medial half of ring finger. Which bony landmark was struck?", "The ulnar nerve passes behind the medial epicondyle and supplies medial one and half fingers."),
    "anatomy-upper-limb-bones-upper-limb-15": u("Clavicle acts as a strut keeping upper limb away from trunk", ["Clavicle forms the glenoid cavity", "Clavicle prevents all scapular rotation", "Clavicle transmits no force"], "After clavicular fracture, the shoulder droops and the lateral fragment is pulled downward. Which anatomical role explains this deformity?", "The clavicle acts as a strut; when fractured, the upper limb weight and muscle pull displace fragments."),

    "anatomy-upper-limb-pectoral-region-11": u("Cutaneous lymphatic obstruction", ["Axillary artery thrombosis", "Long thoracic nerve palsy", "Cephalic vein obstruction only"], "A breast carcinoma patient develops thickened pitted skin resembling orange peel. What is the anatomical basis?", "Peau d'orange occurs due to edema from obstruction of cutaneous lymphatics tethered by skin attachments."),
    "anatomy-upper-limb-pectoral-region-12": u("Radial incision", ["Circular incision around nipple", "Transverse incision cutting across ducts", "Random zigzag incision"], "A lactating woman needs drainage of a breast abscess. Which incision best preserves lactiferous ducts?", "Radial incisions run parallel to lactiferous ducts and reduce duct damage."),
    "anatomy-upper-limb-pectoral-region-13": u("Axillary lymph nodes", ["Deep inguinal nodes", "Popliteal nodes", "Preaortic nodes"], "A malignant lump in the upper outer quadrant of breast is evaluated for nodal spread. Which nodes are most important first?", "Most breast lymph, especially from lateral quadrants, drains to axillary nodes."),
    "anatomy-upper-limb-pectoral-region-14": u("Long thoracic nerve injury causing serratus anterior paralysis", ["Thoracodorsal nerve injury causing latissimus paralysis", "Axillary nerve injury causing deltoid paralysis", "Median nerve injury causing thenar wasting"], "After mastectomy with axillary clearance, a patient cannot push against a wall without the medial border of scapula protruding. What happened?", "Long thoracic nerve supplies serratus anterior; injury causes winging of scapula."),
    "anatomy-upper-limb-pectoral-region-15": u("Clavipectoral fascia", ["Flexor retinaculum", "Palmar aponeurosis", "Pectoralis major tendon"], "During surgery in the deltopectoral groove, the cephalic vein is traced deeply to enter the axillary vein. Which fascial layer does it pierce?", "The cephalic vein pierces clavipectoral fascia to drain into axillary vein."),

    "anatomy-upper-limb-axilla-11": u("Second part of axillary artery", ["First part of subclavian artery", "Brachial artery in cubital fossa", "Radial artery at wrist"], "A surgeon identifies lateral, medial and posterior cords of the brachial plexus. These cords are named by relation to which vessel segment?", "The cords are arranged around the second part of the axillary artery."),
    "anatomy-upper-limb-axilla-12": u("Long thoracic nerve", ["Thoracodorsal nerve", "Axillary nerve", "Ulnar nerve"], "During axillary node dissection, the patient later shows winged scapula but normal wrist extension. Which nerve was injured?", "Long thoracic nerve injury paralyzes serratus anterior, causing winging."),
    "anatomy-upper-limb-axilla-13": u("Thoracodorsal nerve", ["Long thoracic nerve", "Medial pectoral nerve", "Suprascapular nerve"], "A patient after axillary surgery has weakness in climbing and crutch walking due to latissimus dorsi paralysis. Which nerve is damaged?", "Thoracodorsal nerve supplies latissimus dorsi."),
    "anatomy-upper-limb-axilla-14": u("Axillary nerve and posterior circumflex humeral artery", ["Radial nerve and profunda brachii artery", "Median nerve and brachial artery", "Ulnar nerve and superior ulnar collateral artery"], "A mass in the quadrangular space compresses its contents. Which neurovascular bundle is at risk?", "Quadrangular space transmits axillary nerve and posterior circumflex humeral artery."),
    "anatomy-upper-limb-axilla-15": u("Posterior cord", ["Lateral cord", "Medial cord", "Upper trunk"], "A lesion behind the second part of axillary artery affects both axillary and radial nerves. Which part of plexus is involved?", "Axillary and radial nerves are terminal branches of the posterior cord."),

    "anatomy-upper-limb-back-11": u("Spinal accessory nerve", ["Long thoracic nerve", "Thoracodorsal nerve", "Dorsal scapular nerve"], "After lymph node biopsy in the posterior triangle, a patient has shoulder droop and cannot shrug strongly. Which nerve was injured?", "The spinal accessory nerve supplies trapezius and is vulnerable in the posterior triangle."),
    "anatomy-upper-limb-back-12": u("Thoracodorsal nerve", ["Dorsal scapular nerve", "Axillary nerve", "Median nerve"], "A patient using crutches cannot lift the trunk effectively because latissimus dorsi is paralyzed. Which nerve lesion explains this?", "Thoracodorsal nerve supplies latissimus dorsi, important in climbing and crutch walking."),
    "anatomy-upper-limb-back-13": u("Dorsal scapular nerve", ["Long thoracic nerve", "Radial nerve", "Musculocutaneous nerve"], "Weak retraction of scapula with wasting of rhomboids suggests damage to which nerve?", "Rhomboids retract scapula and are supplied by dorsal scapular nerve."),
    "anatomy-upper-limb-back-14": u("Triangle of auscultation", ["Quadrangular space", "Cubital fossa", "Carpal tunnel"], "A clinician asks the patient to fold arms across the chest and lean forward to listen to posterior lung sounds through a thin muscular area. Which space is used?", "The triangle of auscultation is bounded by trapezius, latissimus dorsi and medial scapular border."),
    "anatomy-upper-limb-back-15": u("Trapezius and serratus anterior force couple", ["Biceps and brachialis", "Rhomboids alone", "Flexor-pronator mass"], "A patient cannot abduct the arm above horizontal even though deltoid contracts. Which scapular mechanism is likely deficient?", "Overhead abduction requires upward rotation of scapula by trapezius and serratus anterior."),

    "anatomy-upper-limb-scapular-region-11": u("Supraspinatus tendon", ["Teres major tendon", "Long head of triceps", "Coracobrachialis"], "An elderly patient has painful arc syndrome and difficulty initiating abduction after repeated overhead activity. Which tendon is most likely torn?", "Supraspinatus is the commonly torn rotator cuff tendon and initiates abduction."),
    "anatomy-upper-limb-scapular-region-12": u("Axillary nerve", ["Radial nerve", "Median nerve", "Suprascapular nerve"], "Anterior-inferior shoulder dislocation is reduced, but the patient has deltoid weakness and numbness over lateral shoulder. Which nerve was injured?", "Axillary nerve supplies deltoid and superior lateral cutaneous area."),
    "anatomy-upper-limb-scapular-region-13": u("Radial nerve and profunda brachii artery", ["Axillary nerve and posterior circumflex humeral artery", "Suprascapular nerve and artery", "Median nerve and brachial artery"], "A stab wound passes through the triangular interval. Which structures are most likely injured?", "The triangular interval transmits radial nerve and profunda brachii artery."),
    "anatomy-upper-limb-scapular-region-14": u("Scapular arterial anastomosis", ["Palmar arches", "Circle of Willis", "Trochanteric anastomosis"], "If the third part of axillary artery is ligated proximal to subscapular artery, collateral flow to the limb can occur mainly through which network?", "Anastomoses around scapula provide collateral circulation between subclavian and axillary systems."),
    "anatomy-upper-limb-scapular-region-15": u("Rotator cuff muscles compress humeral head into glenoid", ["Deltoid alone deepens the glenoid", "Biceps inserts into the humeral shaft", "Teres major forms the capsule"], "Why does rotator cuff weakness predispose the shoulder to instability even if deltoid is strong?", "Rotator cuff stabilizes the humeral head in the shallow glenoid during movement."),

    "anatomy-upper-limb-cutaneous-veins-lymph-11": u("Bicipital aponeurosis", ["Flexor retinaculum", "Palmar aponeurosis", "Pronator quadratus"], "During venepuncture of the median cubital vein, which structure protects the brachial artery and median nerve deep to it?", "The bicipital aponeurosis separates superficial veins from deeper brachial artery and median nerve."),
    "anatomy-upper-limb-cutaneous-veins-lymph-12": u("Intercostobrachial nerve", ["Radial nerve", "Median nerve", "Posterior interosseous nerve"], "After axillary lymph node clearance, a patient complains of numbness over the medial upper arm and axilla. Which nerve was likely sacrificed?", "The intercostobrachial nerve supplies skin of axilla and medial upper arm and is vulnerable in axillary surgery."),
    "anatomy-upper-limb-cutaneous-veins-lymph-13": u("C6", ["C8", "T1", "C5"], "A disc prolapse causes paresthesia over the thumb and lateral forearm. Which dermatome is most consistent?", "Thumb and lateral forearm are classic C6 sensory territory."),
    "anatomy-upper-limb-cutaneous-veins-lymph-14": u("Supratrochlear nodes", ["Apical axillary nodes directly", "Parasternal nodes", "Deep cervical nodes"], "An infected wound on the medial hand first enlarges small nodes just above the medial epicondyle. Which nodes are these?", "Superficial lymphatics from medial hand may drain to supratrochlear/epitrochlear nodes."),
    "anatomy-upper-limb-cutaneous-veins-lymph-15": u("Axillary nerve", ["Musculocutaneous nerve", "Median nerve", "Ulnar nerve"], "A patient has sensory loss over the regimental badge area but normal hand sensation. Which nerve is implicated?", "The superior lateral cutaneous nerve of arm is a branch of axillary nerve."),

    "anatomy-upper-limb-arm-11": u("Radial nerve", ["Median nerve", "Ulnar nerve", "Musculocutaneous nerve"], "After a fracture in the radial groove, the patient cannot extend wrist and fingers. Which nerve is injured?", "Radial nerve supplies posterior arm/forearm extensors and lies in the spiral groove."),
    "anatomy-upper-limb-arm-12": u("Brachial artery", ["Ulnar artery", "Radial artery at wrist", "Axillary vein"], "A supracondylar fracture in a child produces a cold pulseless hand. Which vessel is most at risk in the cubital fossa?", "The brachial artery lies in cubital fossa and may be injured in supracondylar humeral fractures."),
    "anatomy-upper-limb-arm-13": u("Musculocutaneous nerve", ["Radial nerve", "Median nerve", "Ulnar nerve"], "A stab wound through coracobrachialis causes weak elbow flexion and sensory loss on lateral forearm. Which nerve is damaged?", "Musculocutaneous nerve pierces coracobrachialis and continues as lateral cutaneous nerve of forearm."),
    "anatomy-upper-limb-arm-14": u("Biceps tendon, brachial artery, median nerve", ["Median nerve, brachial artery, biceps tendon", "Brachial artery, median nerve, ulnar nerve", "Radial nerve, ulnar nerve, median nerve"], "In the cubital fossa from lateral to medial, which order helps avoid the artery during procedures?", "The classic lateral-to-medial order is TAN: tendon, artery, nerve."),
    "anatomy-upper-limb-arm-15": u("Ulnar nerve", ["Radial nerve", "Median nerve", "Axillary nerve"], "A medial epicondyle fracture leads to clawing tendency and numbness in the little finger. Which nerve is injured?", "Ulnar nerve passes posterior to medial epicondyle and supplies intrinsic hand muscles and medial hand skin."),

    "anatomy-upper-limb-forearm-and-hand-11": u("Median nerve compression in carpal tunnel", ["Ulnar nerve compression in Guyon's canal", "Radial nerve compression in spiral groove", "Axillary nerve lesion"], "A patient has nocturnal paresthesia in lateral three and half digits with thenar weakness, but sensation over thenar eminence is spared. What is the lesion?", "Palmar cutaneous branch of median nerve arises proximal to carpal tunnel, so thenar skin may be spared in carpal tunnel syndrome."),
    "anatomy-upper-limb-forearm-and-hand-12": u("Anterior interosseous nerve", ["Recurrent median nerve", "Deep ulnar nerve", "Posterior interosseous nerve"], "A patient cannot make an OK sign due to paralysis of flexor pollicis longus and lateral FDP, but has no sensory loss. Which nerve is affected?", "AIN is a motor branch of median nerve supplying FPL, pronator quadratus and lateral FDP."),
    "anatomy-upper-limb-forearm-and-hand-13": u("Deep branch of ulnar nerve", ["Recurrent branch of median nerve", "Superficial radial nerve", "Musculocutaneous nerve"], "A cyclist develops weakness of interossei and adductor pollicis after pressure over the hook of hamate. Which nerve branch is compressed?", "Ulnar nerve in Guyon's canal, especially deep branch, supplies most intrinsic hand muscles."),
    "anatomy-upper-limb-forearm-and-hand-14": u("Ulnar artery dominant superficial palmar arch", ["Radial artery dominant superficial arch", "Brachial artery arch", "Anterior interosseous artery arch"], "Allen test suggests poor ulnar flow before radial artery cannulation. Why is this clinically important?", "The superficial palmar arch is mainly ulnar; inadequate ulnar flow risks hand ischemia if radial flow is compromised."),
    "anatomy-upper-limb-forearm-and-hand-15": u("Posterior interosseous nerve", ["Superficial radial nerve", "Median nerve", "Ulnar nerve"], "A patient has finger drop without cutaneous sensory loss after compression near the supinator. Which nerve is involved?", "Posterior interosseous nerve is motor; lesion causes extensor weakness without sensory loss."),

    "anatomy-upper-limb-joints-upper-limb-11": u("Axillary nerve", ["Median nerve", "Ulnar nerve", "Long thoracic nerve"], "After anterior shoulder dislocation, which nerve must be tested by deltoid power and lateral shoulder sensation?", "Axillary nerve is closely related to inferior shoulder capsule and surgical neck."),
    "anatomy-upper-limb-joints-upper-limb-12": u("Radial head subluxation from annular ligament", ["Olecranon fracture", "Scaphoid dislocation", "Median nerve entrapment"], "A toddler pulled by the hand refuses to use the limb, holding elbow slightly flexed and pronated. What is the lesion?", "Pulled elbow is subluxation of radial head from annular ligament."),
    "anatomy-upper-limb-joints-upper-limb-13": u("Dorsal displacement of distal radius fragment", ["Anterior shoulder dislocation", "Radial head dislocation", "Olecranon avulsion"], "A fall on outstretched hand in an elderly woman produces dinner-fork deformity. What anatomical displacement causes it?", "Colles fracture is distal radius fracture with dorsal displacement/tilt of distal fragment."),
    "anatomy-upper-limb-joints-upper-limb-14": u("Coracoclavicular ligament", ["Annular ligament", "Transverse humeral ligament", "Palmar radiocarpal ligament"], "A shoulder-tip injury causes acromioclavicular separation with the clavicle riding upward. Which ligament failure is most responsible for vertical instability?", "Coracoclavicular ligament is the main suspensory ligament of the upper limb and stabilizes AC region."),
    "anatomy-upper-limb-joints-upper-limb-15": u("Saddle shape permits opposition", ["Hinge shape permits only flexion", "Pivot shape permits pronation only", "Plane shape prevents movement"], "Why does osteoarthritis of the first carpometacarpal joint severely impair pinch grip?", "The first CMC saddle joint allows opposition, a key movement for pinch and precision grip."),

    "anatomy-upper-limb-surface-radiological-comparison-11": u("Radial artery lateral to flexor carpi radialis tendon", ["Ulnar artery medial to palmaris longus", "Brachial artery lateral to biceps tendon", "Cephalic vein in carpal tunnel"], "Before arterial cannulation at the wrist, where is the radial pulse best located?", "Radial artery is palpated lateral to flexor carpi radialis tendon at the wrist."),
    "anatomy-upper-limb-surface-radiological-comparison-12": u("Median nerve", ["Ulnar nerve", "Radial nerve", "Musculocutaneous nerve"], "A transverse cut just medial to palmaris longus at the wrist injures the nerve entering the carpal tunnel. Which nerve is it?", "Median nerve lies between palmaris longus and flexor carpi radialis and enters carpal tunnel."),
    "anatomy-upper-limb-surface-radiological-comparison-13": u("Humerus to femur, radius to tibia, ulna to fibula", ["Humerus to tibia, radius to femur, ulna to patella", "Clavicle to femur, scapula to tibia, humerus to fibula", "Radius to fibula and ulna to tibia"], "In comparing upper and lower limbs developmentally, which homology is correct?", "Preaxial radius corresponds to tibia, postaxial ulna to fibula, and humerus to femur."),
    "anatomy-upper-limb-surface-radiological-comparison-14": u("Side and projection/view", ["Patient diet", "Skin color", "Pulse rate only"], "Before diagnosing a fracture on upper-limb radiograph, what should be checked first to avoid wrong interpretation?", "Radiological anatomy begins with confirming side, view/projection and normal alignment."),
    "anatomy-upper-limb-surface-radiological-comparison-15": u("Axillary nerve around surgical neck of humerus", ["Median nerve behind medial epicondyle", "Ulnar nerve in spiral groove", "Radial nerve in carpal tunnel"], "A surface marking question asks which nerve is endangered in intramuscular deltoid injections placed too low. Which relation explains this?", "Axillary nerve winds around the surgical neck deep to deltoid; injections should be in safe central deltoid area."),
}


def main():
    data = json.loads(DATA.read_text(encoding="utf-8-sig"))
    found = set()
    for question in data.get("questions", []):
        item = UPDATES.get(question.get("id"))
        if not item:
            continue
        found.add(question["id"])
        answer_index = question["answerIndex"]
        options = list(item["wrong"])
        options.insert(answer_index, item["answer"])
        question["prompt"] = item["prompt"]
        question["answer"] = item["answer"]
        question["options"] = options
        question["explanation"] = item["explanation"]
        question["difficulty"] = "very high"

    missing = sorted(set(UPDATES) - found)
    if missing:
        raise AssertionError(f"Missing IDs: {missing}")

    qs = [q for q in data.get("questions", []) if q.get("subjectId") == "anatomy" and q.get("chapterTitle") == CHAPTER]
    if len(qs) != 165:
        raise AssertionError(f"Expected 165 Upper Limb questions, got {len(qs)}")
    if any(q["answer"] != q["options"][q["answerIndex"]] for q in qs):
        raise AssertionError("Bad answer index")

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Updated {len(UPDATES)} last-five Upper Limb questions with clinical/logic-based questions.")


if __name__ == "__main__":
    main()
